#ifndef __ANTARGISGUI_H
#define __ANTARGISGUI_H

#include "ag_main.h"
#include "ag_gsurface.h"
#include "ag_surface.h"
#include "ag_messageobject.h"
#include "ag_widget.h"
#include "ag_geometry.h"
#include "ag_color.h"
#include "ag_font.h"
#include "ag_fontengine.h"
#include "ag_button.h"
#include "ag_application.h"
#include "ag_text.h"
#include "ag_vtiler.h"
#include "ag_theme.h"
#include "ag_menu.h"
#include "ag_screen.h"
#include "ag_edit.h"
#include "ag_checkbox.h"
#include "ag_radio.h"
#include "ag_table.h"
#include "ag_window.h"
#include "ag_image.h"
#include "ag_caption.h"
#include "ag_background.h"
#include "ag_layout.h"
#include "ag_xml.h"

#ifdef SWIG
%include "ag_main.h"
%include "ag_gsurface.h"
%include "ag_surface.h"
%include "ag_messageobject.h"
%include "ag_widget.h"
%include "ag_geometry.h"
%include "ag_color.h"
%include "ag_font.h"
%include "ag_fontengine.h"
%include "ag_button.h"
%include "ag_application.h"
%include "ag_text.h"
%include "ag_vtiler.h"
%include "ag_theme.h"
%include "ag_menu.h"
%include "ag_screen.h"
%include "ag_edit.h"
%include "ag_checkbox.h"
%include "ag_radio.h"
%include "ag_table.h"
%include "ag_window.h"
%include "ag_image.h"
%include "ag_caption.h"
%include "ag_background.h"
%include "ag_layout.h"
%include "ag_xml.h"
#endif

#endif

