/*
 * Copyright (c) 2005 by David Kamphausen. All rights reserved.
 *
 * config.h
 * by David Kamphausen (david.kamphausen@web.de)
 *
 * The "Antargis" project, including all files needed to compile it,
 * is free software; you can redistribute it and/or use it and/or modify it
 * under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program.
 */

/* config.h. Generated by SConstruct */


#define PACKAGE_BUGREPORT "none"
#define HAVE_STRING_H ""
#define PACKAGE_NAME "LincityNG"
#define PACKAGE "lincityng"
#define HAVE_UNISTD_H ""
#define PACKAGE_VERSION "0.1-svn"
#define SIZEOF_LONG 4
#define HAVE_GZIP ""
#define HAVE_SYS_TIME_H ""
#define SIZEOF_CHAR 1
#define HAVE_POPEN ""
#define SIZEOF_INT 4
#define HAVE_DIRENT_H ""
#define PACKAGE_STRING "LincityNG 0.1-svn"
#define SIZEOF_SHORT 2

