require File.join(File.split(__FILE__)[0],'rookey','tasks.rb')

$rspec=Rookey.checkedRequire('spec/rake/spectask')

# basic version

inits=[
  "external",
  "basic",
  "math",
  "video",
  "sound",
  "gui",
  "3dengine",
  "game"
      ].map{|f|"AG_Init_libantargis"+f}
lib=Rookey::ruby_ext("antargis",Dir["ext/*/*.cc"]+Dir["ext/*/*.c"]+Dir["ext/*/*.h"]+Dir["ext/*/templates.i"],inits)

ts=Rookey::compile(Dir["main/starter.cc"])
main=Rookey::link_exe("starter",ts)


task :default=>[lib,main] do
  puts "Done."
end


alias :oldSystem :system
def system(cmd)
  #puts Dir.pwd
  if cmd=~/ruby .*/
    cmd=cmd.gsub(/^ruby/,"./starter")
  end
  #puts cmd
  oldSystem(cmd)
end

if $rspec
  # rspec
  Spec::Rake::SpecTask.new(:spec=>:default) do |t|
    t.spec_files = FileList['ruby/**/spec_*.rb'].map{|f|File.expand_path(f)}
    t.warning = true
    t.rcov = true
    t.spec_opts=["--format html:"+File.expand_path("spec_output.html")]
  end
end


