require 'rookey.rb'

tests=Dir["*_spec.cc"]

baseFiles=["../rk_singleton.cc","../rk_logging.cc"]

test_exes=tests.map{|test|
  name=test.sub(/_spec.cc/,"")
  files=[test]+baseFiles
  objs=Rookey::compile(files)
  Rookey::link_exe(name, objs)
}

task :runTests=>test_exes do
  test_exes.each{|exe|
    sh "./"+exe
  }
end

CLEAN << "rk_log.txt"


task :default=>:runTests do

end