/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.34
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_File3_WRAP_H_
#define SWIG_File3_WRAP_H_

namespace Swig {
  class Director;
}


class SwigDirector_AGRubyObject : public AGRubyObject, public Swig::Director {

public:
    SwigDirector_AGRubyObject(VALUE self);
    virtual ~SwigDirector_AGRubyObject();
};


class SwigDirector_B : public B, public Swig::Director {

public:
    SwigDirector_B(VALUE self);
    virtual ~SwigDirector_B();
    virtual void x();
};


#endif
