require '../tasks.rb'
require 'rake/clean.rb'
var1=Rookey.swig_interface('file3'=>['a.h'])
var2=Rookey.swig('file3_swig.cc'=>[var1])
var4=Rookey.compile(['main.cc',var2])
var5=Rookey.link_dll(File.split(var4.flatten.select{|f|f=~/swig/}[0])[1].sub(/_swig.*/,''),var4)
task :default=>var5
