.TH "gui/src/ag_aes.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_aes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <ag_base.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string AGEXPORT \fBaes_enc\fP (const std::string &key, const std::string &c)"
.br
.ti -1c
.RI "std::string AGEXPORT \fBaes_dec\fP (const std::string &key, const std::string &c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string AGEXPORT aes_dec (const std::string & key, const std::string & c)"
.PP
.SS "std::string AGEXPORT aes_enc (const std::string & key, const std::string & c)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
