.TH "gui/src/ag_button.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_button.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_widget.h'\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_background.h'\fP
.br
\fC#include 'ag_border.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGButton\fP"
.br
.RI "\fIimplements push-buttons
.PP
\fBAGButton\fP represents a button, which can hold a text-caption or an image-caption, but not both. Further it can have following states: \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGButton\fP & \fBtoAGButton\fP (\fBAGWidget\fP &pWidget)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGButton\fP& toAGButton (\fBAGWidget\fP & pWidget)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
