.TH "gui/src/ag_base.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_base.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAGEXPORT\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define AGEXPORT"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
