.TH "gui/src/ag_color.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_color.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SDL.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <ag_base.h>\fP
.br
\fC#include <ag_string.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGColor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBAGColor\fP &c1, const \fBAGColor\fP &c2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAGColor\fP &c1, const \fBAGColor\fP &c2)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBAGColor\fP &c1, const \fBAGColor\fP &c2)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAGColor\fP &c)"
.br
.ti -1c
.RI "int \fBtoInt\fP (Uint8 u)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool operator!= (const \fBAGColor\fP & c1, const \fBAGColor\fP & c2)"
.PP
.SS "bool operator< (const \fBAGColor\fP & c1, const \fBAGColor\fP & c2)"
.PP
.SS "std::ostream& operator<< (std::ostream & o, const \fBAGColor\fP & c)"
.PP
.SS "bool operator== (const \fBAGColor\fP & c1, const \fBAGColor\fP & c2)"
.PP
.SS "int toInt (Uint8 u)\fC [inline]\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
