.TH "gui/src/ag_colorbutton.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_colorbutton.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_colorbutton.h'\fP
.br
\fC#include 'ag_layoutfactory.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGColorButtonLayoutCreator\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGColorButton\fP & \fBtoAGColorButton\fP (\fBAGWidget\fP &pWidget)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (ColorButton)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "IMPLEMENT_COMPONENT_FACTORY (ColorButton)"
.PP
.SS "\fBAGColorButton\fP& toAGColorButton (\fBAGWidget\fP & pWidget)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
