.TH "gui/src/ag_caption.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_caption.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_text.h'\fP
.br
\fC#include 'ag_background.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGCaption\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
