.TH "gui/src/ag_edit.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_edit.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_widget.h'\fP
.br
\fC#include 'ag_font.h'\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_background.h'\fP
.br
\fC#include 'ag_utf8.h'\fP
.br
\fC#include 'ag_string_utf8.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGEditLine\fP"
.br
.ti -1c
.RI "class \fBAGEdit\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAGAlign\fP { \fBEDIT_LEFT\fP, \fBEDIT_RIGHT\fP, \fBEDIT_JUSTIFY\fP, \fBEDIT_CENTER\fP }"
.br
.ti -1c
.RI "enum \fBAGVAlign\fP { \fBEDIT_TOP\fP, \fBEDIT_BOTTOM\fP, \fBEDIT_VCENTER\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGEdit\fP & \fBtoAGEdit\fP (\fBAGWidget\fP &w)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAGAlign\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIEDIT_LEFT \fP\fP
.TP
\fB\fIEDIT_RIGHT \fP\fP
.TP
\fB\fIEDIT_JUSTIFY \fP\fP
.TP
\fB\fIEDIT_CENTER \fP\fP

.SS "enum \fBAGVAlign\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIEDIT_TOP \fP\fP
.TP
\fB\fIEDIT_BOTTOM \fP\fP
.TP
\fB\fIEDIT_VCENTER \fP\fP

.SH "Function Documentation"
.PP 
.SS "\fBAGEdit\fP& toAGEdit (\fBAGWidget\fP & w)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
