.TH "gui/src/ag_fontengine.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_fontengine.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_fontengine.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_kill.h'\fP
.br
\fC#include 'ag_texture.h'\fP
.br
\fC#include 'ag_fs.h'\fP
.br
\fC#include 'ag_sgeexport.h'\fP
.br
\fC#include <SDL_ttf.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFontInfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "TTF_Font * \fBgetFont\fP (std::string s, int i)"
.br
.ti -1c
.RI "void \fBborder\fP (\fBAGSurface\fP &s, \fBAGColor\fP bc)"
.br
.ti -1c
.RI "void \fBembossSurface\fP (\fBAGSurface\fP &s, float depth=1.0f)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static std::map< \fBFontInfo\fP, TTF_Font * > \fBfontEngineFonts\fP"
.br
.ti -1c
.RI "bool \fBfontEngineInited\fP = false"
.br
.ti -1c
.RI "\fBAGFontEngine\fP \fBmyFontEngine\fP"
.br
.ti -1c
.RI "std::map< std::pair< \fBAGFont\fP, \fBAGStringUtf8\fP >, \fBAGTexture\fP > \fBfontCache\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void border (\fBAGSurface\fP & s, \fBAGColor\fP bc)"
.PP
.SS "void embossSurface (\fBAGSurface\fP & s, float depth = \fC1.0f\fP)"
.PP
.SS "TTF_Font* getFont (std::string s, int i)"
.PP
.SH "Variable Documentation"
.PP 
.SS "std::map<std::pair<\fBAGFont\fP,\fBAGStringUtf8\fP>,\fBAGTexture\fP> \fBfontCache\fP"
.PP
.SS "std::map<\fBFontInfo\fP,TTF_Font*> \fBfontEngineFonts\fP\fC [static]\fP"
.PP
.SS "bool \fBfontEngineInited\fP = false"
.PP
.SS "\fBAGFontEngine\fP \fBmyFontEngine\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
