.TH "gui/src/ag_fbo.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_fbo.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GLee.h'\fP
.br
\fC#include 'ag_fbo.h'\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_config.h'\fP
.br
\fC#include <stdexcept>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUSE_FBO\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcanFBO\fP ()"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define USE_FBO"
.PP
.SH "Function Documentation"
.PP 
.SS "bool canFBO ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
