.TH "gui/src/ag_gltexture.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_gltexture.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br
\fC#include 'ag_gltexture.h'\fP
.br
\fC#include 'ag_surfacemanager.h'\fP
.br
\fC#include 'ag_rendercontext.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "size_t \fBgUsedTexMemory\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "size_t \fBgUsedTexMemory\fP = 0"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
