.TH "gui/src/ag_glsurface.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_glsurface.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GLee.h'\fP
.br
\fC#include <SDL_opengl.h>\fP
.br
\fC#include 'ag_glsurface.h'\fP
.br
\fC#include 'ag_color.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_fontengine.h'\fP
.br
\fC#include 'ag_surfacemanager.h'\fP
.br
\fC#include <GL/gl.h>\fP
.br
\fC#include <GL/glext.h>\fP
.br
\fC#include <GL/glu.h>\fP
.br
\fC#include <assert.h>\fP
.br
\fC#include <set>\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'ag_sgeexport.h'\fP
.br
\fC#include 'SDL_image.h'\fP
.br
\fC#include <ag_rendercontext.h>\fP
.br
\fC#include <SDL.h>\fP
.br
\fC#include <ag_fs.h>\fP
.br
\fC#include <ag_geometry.h>\fP
.br
\fC#include <ag_texture.h>\fP
.br
\fC#include <ag_profiler.h>\fP
.br
\fC#include <ag_glpainter.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSIMPLE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitDraw\fP ()"
.br
.ti -1c
.RI "void \fBinitGUIView\fP (int w, int h)"
.br
.ti -1c
.RI "void \fBmyFlip\fP ()"
.br
.ti -1c
.RI "size_t \fBnext2pow\fP (size_t i)"
.br
.ti -1c
.RI "void \fBglColor\fP (const \fBAGColor\fP &c)"
.br
.ti -1c
.RI "bool \fBopengl\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::set< SDL_Surface * > \fBglTestSurfaces\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define SIMPLE"
.PP
.SH "Function Documentation"
.PP 
.SS "void glColor (const \fBAGColor\fP & c)"
.PP
.SS "void initDraw ()"
.PP
.SS "void initGUIView (int w, int h)"
.PP
.SS "void myFlip ()"
.PP
.SS "size_t next2pow (size_t i)"
.PP
.SS "bool opengl ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "std::set<SDL_Surface *> \fBglTestSurfaces\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
