.TH "gui/src/ag_geometry.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_geometry.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SDL.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <list>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <ag_base.h>\fP
.br
\fC#include <ag_string.h>\fP
.br
\fC#include 'ag_geometry_inline.cc'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAGAngle\fP"
.br
.RI "\fISimple structure holding an angle in degrees. \fP"
.ti -1c
.RI "class \fBAGVector2\fP"
.br
.ti -1c
.RI "class \fBAGVector3\fP"
.br
.ti -1c
.RI "class \fBAGMatrix3\fP"
.br
.ti -1c
.RI "struct \fBAGMatrix3::Row\fP"
.br
.ti -1c
.RI "class \fBAGLine2\fP"
.br
.ti -1c
.RI "class \fBAGLine3\fP"
.br
.ti -1c
.RI "class \fBAGCollisionData\fP"
.br
.ti -1c
.RI "class \fBAGTriangle2\fP"
.br
.ti -1c
.RI "class \fBAGCircle2\fP"
.br
.ti -1c
.RI "class \fBAGTriangle3\fP"
.br
.ti -1c
.RI "class \fBAGRect2\fP"
.br
.ti -1c
.RI "class \fBAGVector4\fP"
.br
.ti -1c
.RI "class \fBAGMatrix4\fP"
.br
.ti -1c
.RI "struct \fBAGMatrix4::MRow\fP"
.br
.ti -1c
.RI "class \fBAGRect3\fP"
.br
.ti -1c
.RI "class \fBAGBox3\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAGVector2\fP &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAGVector3\fP &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAGVector4\fP &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAGRect2\fP &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAGBox3\fP &v)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & o, const \fBAGBox3\fP & v)"
.PP
.SS "std::ostream& operator<< (std::ostream & o, const \fBAGRect2\fP & v)"
.PP
.SS "std::ostream& operator<< (std::ostream & o, const \fBAGVector4\fP & v)"
.PP
.SS "std::ostream& operator<< (std::ostream & o, const \fBAGVector3\fP & v)"
.PP
.SS "std::ostream& operator<< (std::ostream & o, const \fBAGVector2\fP & v)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
