.TH "gui/src/ag_kill.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_kill.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_kill.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnewInstanceKiller\fP ()"
.br
.ti -1c
.RI "void \fBdeleteInstanceKiller\fP ()"
.br
.ti -1c
.RI "\fBAGInstanceKiller\fP * \fBgetInstanceKiller\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAGInstanceKiller\fP * \fBmInstanceKiller\fP = 0"
.br
.ti -1c
.RI "bool \fBmIndirectInstance\fP = false"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void deleteInstanceKiller ()"
.PP
.SS "\fBAGInstanceKiller\fP* getInstanceKiller ()"
.PP
.SS "void newInstanceKiller ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "bool \fBmIndirectInstance\fP = false"
.PP
.SS "\fBAGInstanceKiller\fP* \fBmInstanceKiller\fP = 0"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
