.TH "gui/src/ag_layout.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_layout.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_widget.h'\fP
.br
\fC#include 'ag_xml.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGLayout\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGWidget\fP * \fBparseNode\fP (\fBAGWidget\fP *pParent, const \fBNode\fP &pNode)"
.br
.ti -1c
.RI "void \fBparseChildren\fP (\fBAGWidget\fP *pParent, const \fBNode\fP &pNode)"
.br
.ti -1c
.RI "\fBAGRect2\fP \fBgetLayoutGeometry\fP (\fBAGWidget\fP *pParent, const \fBNode\fP &pNode)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGRect2\fP getLayoutGeometry (\fBAGWidget\fP * pParent, const \fBNode\fP & pNode)"
.PP
.SS "void parseChildren (\fBAGWidget\fP * pParent, const \fBNode\fP & pNode)"
.PP
.SS "\fBAGWidget\fP* parseNode (\fBAGWidget\fP * pParent, const \fBNode\fP & pNode)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
