.TH "gui/src/ag_local.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_local.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_local.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetLocalizer\fP (\fBAGLocalizer\fP *p)"
.br
.ti -1c
.RI "\fBAGLocalizer\fP * \fBgetLocalizer\fP ()"
.br
.ti -1c
.RI "\fBAGStringUtf8\fP \fBtranslate\fP (const \fBAGString\fP &s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAGLocalizer\fP * \fBgLocalizer\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGLocalizer\fP* getLocalizer ()"
.PP
.SS "void setLocalizer (\fBAGLocalizer\fP * p)"
.PP
.SS "\fBAGStringUtf8\fP translate (const \fBAGString\fP & s)"
.PP
.SH "Variable Documentation"
.PP 
.SS "\fBAGLocalizer\fP* \fBgLocalizer\fP = 0"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
