.TH "gui/src/ag_mixer.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_mixer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <ag_widget.h>\fP
.br
\fC#include <ag_surface.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGSound\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGSound\fP * \fBgetSoundManager\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGSound\fP* getSoundManager ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
