.TH "gui/src/ag_profiler.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_profiler.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <SDL.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSTACKTRACE\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define STACKTRACE"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
