.TH "gui/src/ag_plugin.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_plugin.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_plugin.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <dlfcn.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBAGPlugin\fP * \fBCreatePluginType\fP ()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGPlugin\fP * \fBloadPlugin\fP (const std::string &pFile)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAGPlugin\fP* \fBCreatePluginType\fP()"
.PP
.SH "Function Documentation"
.PP 
.SS "\fBAGPlugin\fP* loadPlugin (const std::string & pFile)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
