.TH "gui/src/ag_regex.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_regex.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '/usr/include/regex.h'\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRegEx\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
