.TH "gui/src/ag_string_utf8.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_string_utf8.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_string_utf8.h>\fP
.br
\fC#include <ag_debug.h>\fP
.br
\fC#include <ag_utf8.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAGStringUtf8\fP &s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & o, const \fBAGStringUtf8\fP & s)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
