.TH "gui/src/ag_screen.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_screen.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_config.h>\fP
.br
\fC#include <ag_base.h>\fP
.br
\fC#include <ag_painttarget.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGScreen\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGScreen\fP &AGEXPORT \fBgetScreen\fP ()"
.br
.ti -1c
.RI "void \fBsetScreen\fP (\fBAGScreen\fP *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGScreen\fP& AGEXPORT getScreen ()"
.PP
.SS "void setScreen (\fBAGScreen\fP * s)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
