.TH "gui/src/ag_sdlsurface.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_sdlsurface.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_sdlsurface.h'\fP
.br
\fC#include 'ag_texture.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_fs.h'\fP
.br
\fC#include 'ag_draw.h'\fP
.br
\fC#include 'ag_fontengine.h'\fP
.br
\fC#include 'SDL_image.h'\fP
.br
\fC#include 'ag_sgeexport.h'\fP
.br
\fC#include <math.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "SDL_Surface * \fBAGCreate32BitSurface\fP (size_t width, size_t height)"
.br
.ti -1c
.RI "bool \fBvideoInited\fP ()"
.br
.ti -1c
.RI "\fBAGScreen\fP &AGEXPORT \fBgetScreen\fP ()"
.br
.ti -1c
.RI "void \fBsetScreen\fP (\fBAGScreen\fP *s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAGScreen\fP * \fBmAGGScreen\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SDL_Surface* AGCreate32BitSurface (size_t width, size_t height)"
.PP
.SS "\fBAGScreen\fP& AGEXPORT getScreen ()"
.PP
.SS "void setScreen (\fBAGScreen\fP * s)"
.PP
.SS "bool videoInited ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "\fBAGScreen\fP* \fBmAGGScreen\fP = 0"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
