.TH "gui/src/ag_surfacemanager.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_surfacemanager.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_surfacemanager.h'\fP
.br
\fC#include 'ag_rendercontext.h'\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_texture.h'\fP
.br
\fC#include 'ag_kill.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_config.h'\fP
.br
\fC#include 'ag_glsurface.h'\fP
.br
\fC#include <map>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGSurfaceManager\fP * \fBgetSurfaceManager\fP ()"
.br
.ti -1c
.RI "size_t \fBgetTexMem\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAGSurfaceManager\fP * \fBmSurfaceManager\fP = 0"
.br
.ti -1c
.RI "bool \fBmSurfaceManagerDeleted\fP = false"
.br
.ti -1c
.RI "long \fBglobalTexMem\fP = -1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGSurfaceManager\fP* getSurfaceManager ()"
.PP
.SS "size_t getTexMem ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "long \fBglobalTexMem\fP = -1"
.PP
.SS "\fBAGSurfaceManager\fP* \fBmSurfaceManager\fP = 0"
.PP
.SS "bool \fBmSurfaceManagerDeleted\fP = false"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
