.TH "gui/src/ag_sgeexport.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_sgeexport.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SDL.h>\fP
.br
\fC#include 'sge_surface.h'\fP
.br
\fC#include 'sge_primitives.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
