.TH "gui/src/ag_surfacemanager.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_surfacemanager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGSurfaceManager\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGSurfaceManager\fP * \fBgetSurfaceManager\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGSurfaceManager\fP* getSurfaceManager ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
