.TH "gui/src/ag_serial.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_serial.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_serial.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <ag_debug.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBlittleEndian\fP ()"
.br
.ti -1c
.RI "void \fBcheckParentDirs\fP (const std::string &s)"
.br
.ti -1c
.RI "unsigned char \fBfromHexBS\fP (unsigned char c)"
.br
.ti -1c
.RI "void \fBtoHexBS\fP (char c, std::ostream &os)"
.br
.ti -1c
.RI "std::string \fBbinaryToHex\fP (const std::string &s)"
.br
.ti -1c
.RI "std::string \fBhexToBinary\fP (const std::string &s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBmLittleEndian\fP = -1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string binaryToHex (const std::string & s)"
.PP
.SS "void checkParentDirs (const std::string & s)"
.PP
.SS "unsigned char fromHexBS (unsigned char c)"
.PP
.SS "std::string hexToBinary (const std::string & s)"
.PP
.SS "bool littleEndian ()"
.PP
.SS "void toHexBS (char c, std::ostream & os)"
.PP
.SH "Variable Documentation"
.PP 
.SS "int \fBmLittleEndian\fP = -1"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
