.TH "gui/src/ag_string.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_string.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <SDL.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGString\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::string \fBAGFilename\fP"
.br
.ti -1c
.RI "typedef std::string \fBAGData\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::string \fBAGData\fP"
.PP
.SS "typedef std::string \fBAGFilename\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
