.TH "gui/src/ag_text.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_text.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_widget.h'\fP
.br
\fC#include 'ag_font.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGText\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGText\fP & \fBtoAGText\fP (\fBAGWidget\fP &w)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGText\fP& toAGText (\fBAGWidget\fP & w)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
