.TH "gui/src/ag_texture.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_texture.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_texture.h'\fP
.br
\fC#include 'ag_glsurface.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_rendercontext.h'\fP
.br
\fC#include 'ag_sgeexport.h'\fP
.br
\fC#include 'ag_surfacemanager.h'\fP
.br
\fC#include 'ag_profiler.h'\fP
.br
\fC#include 'ag_glpainter.h'\fP
.br
\fC#include 'ag_fbo.h'\fP
.br
\fC#include <stdexcept>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBnextpow2\fP (size_t i)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "size_t \fBgUsedTexMemory\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t nextpow2 (size_t i)"
.PP
.SH "Variable Documentation"
.PP 
.SS "size_t \fBgUsedTexMemory\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
