.TH "gui/src/ag_theme.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_theme.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_font.h'\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGTheme\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGTheme\fP * \fBgetTheme\fP ()"
.br
.ti -1c
.RI "void \fBsetTheme\fP (const \fBAGTheme\fP &aTheme)"
.br
.ti -1c
.RI "void \fBloadTheme\fP (const \fBAGData\fP &pXML)"
.br
.ti -1c
.RI "bool \fBloadThemeFile\fP (const \fBAGFilename\fP &pFilename)"
.br
.ti -1c
.RI "\fBAGString\fP \fBaddPoint\fP (const \fBAGString\fP &pTheme)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGString\fP addPoint (const \fBAGString\fP & pTheme)"
.PP
.SS "\fBAGTheme\fP* getTheme ()"
.PP
.SS "void loadTheme (const \fBAGData\fP & pXML)"
.PP
.SS "bool loadThemeFile (const \fBAGFilename\fP & pFilename)"
.PP
.SS "void setTheme (const \fBAGTheme\fP & aTheme)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
