.TH "AGAngle" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGAngle \- Simple structure holding an angle in degrees.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGAngle\fP (float a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBangle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple structure holding an angle in degrees. 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGAngle::AGAngle (float a)\fC [explicit]\fP"
.PP
\fBParameters:\fP
.RS 4
\fIan\fP angle in degrees 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "float \fBAGAngle::angle\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
