.TH "AGBox3" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGBox3 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGBox3\fP ()"
.br
.ti -1c
.RI "\fBAGBox3\fP (const \fBAGVector3\fP &pBase, const \fBAGVector3\fP &pDir)"
.br
.ti -1c
.RI "void \fBinclude\fP (const \fBAGVector3\fP &p)"
.br
.ti -1c
.RI "bool \fBincludes\fP (const \fBAGBox3\fP &b)"
.br
.ti -1c
.RI "bool \fBcollides\fP (const \fBAGVector3\fP &p) const "
.br
.ti -1c
.RI "bool \fBcollides\fP (const \fBAGLine3\fP &p) const "
.br
.ti -1c
.RI "bool \fBcollides\fP (const \fBAGBox3\fP &b) const "
.br
.ti -1c
.RI "bool \fBcontains\fP (const \fBAGTriangle3\fP &t) const "
.br
.ti -1c
.RI "std::vector< \fBAGRect3\fP > \fBgetSides\fP () const "
.br
.ti -1c
.RI "\fBAGString\fP \fBtoString\fP () const "
.br
.ti -1c
.RI "std::vector< \fBAGBox3\fP > \fBsplit\fP () const "
.br
.ti -1c
.RI "bool \fBcollides\fP (const \fBAGMatrix4\fP &frustum) const "
.br
.ti -1c
.RI "std::vector< \fBAGVector3\fP > \fBgetVertices\fP () const "
.br
.ti -1c
.RI "void \fBcalcVertices\fP (std::vector< \fBAGVector3\fP > &vs) const "
.br
.ti -1c
.RI "\fBAGBox3\fP \fBoperator+\fP (const \fBAGVector3\fP &v) const "
.br
.ti -1c
.RI "\fBAGBox3\fP \fBoperator-\fP (const \fBAGVector3\fP &v) const "
.br
.ti -1c
.RI "bool \fBvalid\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGVector3\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBAGVector3\fP \fBdir\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGBox3::AGBox3 ()"
.PP
.SS "AGBox3::AGBox3 (const \fBAGVector3\fP & pBase, const \fBAGVector3\fP & pDir)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGBox3::calcVertices (std::vector< \fBAGVector3\fP > & vs) const\fC [inline]\fP"
.PP
.SS "bool AGBox3::collides (const \fBAGMatrix4\fP & frustum) const"
.PP
.SS "bool AGBox3::collides (const \fBAGBox3\fP & b) const"
.PP
.SS "bool AGBox3::collides (const \fBAGLine3\fP & p) const"
.PP
.SS "bool AGBox3::collides (const \fBAGVector3\fP & p) const"
.PP
.SS "bool AGBox3::contains (const \fBAGTriangle3\fP & t) const"
.PP
.SS "std::vector< \fBAGRect3\fP > AGBox3::getSides () const"
.PP
.SS "std::vector< \fBAGVector3\fP > AGBox3::getVertices () const"
.PP
.SS "void AGBox3::include (const \fBAGVector3\fP & p)"
.PP
.SS "bool AGBox3::includes (const \fBAGBox3\fP & b)"
.PP
.SS "\fBAGBox3\fP AGBox3::operator+ (const \fBAGVector3\fP & v) const"
.PP
.SS "\fBAGBox3\fP AGBox3::operator- (const \fBAGVector3\fP & v) const"
.PP
.SS "std::vector< \fBAGBox3\fP > AGBox3::split () const"
.PP
.SS "\fBAGString\fP AGBox3::toString () const"
.PP
.SS "bool AGBox3::valid () const"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBAGVector3\fP \fBAGBox3::base\fP"
.PP
.SS "\fBAGVector3\fP \fBAGBox3::dir\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
