.TH "AGCheckBox" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGCheckBox \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_checkbox.h>\fP
.PP
Inherits \fBAGButton\fP.
.PP
Inherited by \fBAGRadio\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGCheckBox\fP (\fBAGWidget\fP *pParent, \fBAGRect2\fP pRect)"
.br
.ti -1c
.RI "void \fBsetSurfaces\fP (\fBAGSurface\fP pDisabledSurface, \fBAGSurface\fP pEnabledSurface)"
.br
.ti -1c
.RI "void \fBsetState\fP (const \fBState\fP &pState)"
.br
.ti -1c
.RI "virtual bool \fBeventMouseClick\fP (\fBAGEvent\fP *m)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGCheckBox::AGCheckBox (\fBAGWidget\fP * pParent, \fBAGRect2\fP pRect)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool AGCheckBox::eventMouseClick (\fBAGEvent\fP * m)\fC [virtual]\fP"
.PP
Reimplemented from \fBAGWidget\fP.
.PP
Reimplemented in \fBAGRadio\fP.
.SS "void AGCheckBox::setState (const \fBState\fP & pState)"
.PP
.SS "void AGCheckBox::setSurfaces (\fBAGSurface\fP pDisabledSurface, \fBAGSurface\fP pEnabledSurface)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
