.TH "AGCircle2" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGCircle2 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGCircle2\fP (const \fBAGVector3\fP &v, float rad)"
.br
.ti -1c
.RI "bool \fBinCircle\fP (const \fBAGTriangle2\fP &t) const "
.br
.ti -1c
.RI "bool \fBoutCircle\fP (const \fBAGTriangle2\fP &t) const "
.br
.ti -1c
.RI "bool \fBinCircle\fP (const \fBAGVector3\fP &v) const "
.br
.ti -1c
.RI "bool \fBoutCircle\fP (const \fBAGVector3\fP &v) const "
.br
.ti -1c
.RI "\fBAGVector3\fP \fBgetPos\fP () const "
.br
.ti -1c
.RI "float \fBgetRadius\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGCircle2::AGCircle2 (const \fBAGVector3\fP & v, float rad)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGVector3\fP AGCircle2::getPos () const"
.PP
.SS "float AGCircle2::getRadius () const"
.PP
.SS "bool AGCircle2::inCircle (const \fBAGVector3\fP & v) const"
.PP
.SS "bool AGCircle2::inCircle (const \fBAGTriangle2\fP & t) const"
.PP
.SS "bool AGCircle2::outCircle (const \fBAGVector3\fP & v) const"
.PP
.SS "bool AGCircle2::outCircle (const \fBAGTriangle2\fP & t) const"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
