.TH "AGConfig" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGConfig \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_config.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGConfig\fP ()"
.br
.ti -1c
.RI "\fBAGString\fP \fBget\fP (const \fBAGString\fP &pValue, const \fBAGString\fP &pDefault, const \fBAGString\fP &pComment)"
.br
.ti -1c
.RI "\fBAGString\fP \fBget\fP (const \fBAGString\fP &pValue) const "
.br
.ti -1c
.RI "void \fBset\fP (const \fBAGString\fP &pName, const \fBAGString\fP &pValue)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGConfig::AGConfig ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGString\fP AGConfig::get (const \fBAGString\fP & pValue) const"
.PP
.SS "\fBAGString\fP AGConfig::get (const \fBAGString\fP & pValue, const \fBAGString\fP & pDefault, const \fBAGString\fP & pComment)"
.PP
.SS "void AGConfig::set (const \fBAGString\fP & pName, const \fBAGString\fP & pValue)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
