.TH "AGCPPListener" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGCPPListener \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_messageobject.h>\fP
.PP
Inherited by \fBAGSlot0< T >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AGCPPListener\fP ()"
.br
.ti -1c
.RI "virtual bool \fBsignal\fP (\fBAGEvent\fP *m) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
some syntactic sugar for simple connecting of slots and signals. 
.PP
\fBSee also:\fP
.RS 4
\fBAGSignal\fP 
.PP
\fBAGMessageObject\fP 
.RE
.PP

.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGCPPListener::~AGCPPListener ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual bool AGCPPListener::signal (\fBAGEvent\fP * m) const\fC [pure virtual]\fP"
.PP
Implemented in \fBAGSlot0< T >\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
