.TH "AGDecryptorPlugin" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGDecryptorPlugin \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_surface.h>\fP
.PP
Inherits \fBAGPlugin\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AGDecryptorPlugin\fP ()"
.br
.ti -1c
.RI "virtual \fBAGDecryptor\fP * \fBgetDecryptor\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual AGDecryptorPlugin::~AGDecryptorPlugin ()\fC [inline, virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBAGDecryptor\fP* AGDecryptorPlugin::getDecryptor ()\fC [inline, virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
