.TH "AGDialog" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGDialog \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_dialog.h>\fP
.PP
Inherits \fBAGLayout\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGDialog\fP (\fBAGWidget\fP *pgParent)"
.br
.ti -1c
.RI "void \fBloadXML\fP (const std::string &pXMLData)"
.br
.ti -1c
.RI "virtual bool \fBeventOk\fP (\fBAGEvent\fP *event)"
.br
.ti -1c
.RI "virtual bool \fBeventCancel\fP (\fBAGEvent\fP *event)"
.br
.ti -1c
.RI "virtual bool \fBeventClose\fP (\fBAGEvent\fP *event)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGDialog::AGDialog (\fBAGWidget\fP * pgParent)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool AGDialog::eventCancel (\fBAGEvent\fP * event)\fC [virtual]\fP"
.PP
.SS "bool AGDialog::eventClose (\fBAGEvent\fP * event)\fC [virtual]\fP"
.PP
.SS "bool AGDialog::eventOk (\fBAGEvent\fP * event)\fC [virtual]\fP"
.PP
.SS "void AGDialog::loadXML (const std::string & pXMLData)\fC [virtual]\fP"
.PP
Reimplemented from \fBAGLayout\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
