.TH "AGEditNewLine" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGEditNewLine \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_editcontent.h>\fP
.PP
Inherits \fBAGEditElement\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "size_t AGEditNewLine::size ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBAGEditElement\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
