.TH "AGEditSurface" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGEditSurface \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_editcontent.h>\fP
.PP
Inherits \fBAGEditElement\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGEditSurface\fP (const \fBAGSurface\fP &pSurface)"
.br
.ti -1c
.RI "size_t \fBsize\fP ()"
.br
.ti -1c
.RI "int \fBwidth\fP ()"
.br
.ti -1c
.RI "int \fBheight\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP (\fBAGPainter\fP &p, int x, int y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGSurface\fP \fBsurface\fP"
.br
.ti -1c
.RI "\fBAGTexture\fP \fBtexture\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGEditSurface::AGEditSurface (const \fBAGSurface\fP & pSurface)\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "int AGEditSurface::height ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBAGEditElement\fP.
.SS "void AGEditSurface::render (\fBAGPainter\fP & p, int x, int y)\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBAGEditElement\fP.
.SS "size_t AGEditSurface::size ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBAGEditElement\fP.
.SS "int AGEditSurface::width ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBAGEditElement\fP.
.SH "Member Data Documentation"
.PP 
.SS "\fBAGSurface\fP \fBAGEditSurface::surface\fP"
.PP
.SS "\fBAGTexture\fP \fBAGEditSurface::texture\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
