.TH "AGException" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGException \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_exception.h>\fP
.PP
Inherits std::exception.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGException\fP (const std::string &e)"
.br
.ti -1c
.RI "virtual \fB~AGException\fP ()  throw ()"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGException::AGException (const std::string & e)\fC [inline]\fP"
.PP
.SS "virtual AGException::~AGException ()  throw ()\fC [inline, virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "const char* AGException::what () const  throw ()\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
