.TH "AGLayoutCreator" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGLayoutCreator \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_layoutfactory.h>\fP
.PP
Inherited by \fBAGButtonLayoutCreator\fP, \fBAGCellLayoutCreator\fP, \fBAGCheckBoxLayoutCreator\fP, \fBAGColorButtonLayoutCreator\fP, \fBAGComboBoxLayoutCreator\fP, \fBAGEditLayoutCreator\fP, \fBAGFrameLayoutCreator\fP, \fBAGImageLayoutCreator\fP, \fBAGLayoutLayoutCreator\fP, \fBAGListBoxLayoutCreator\fP, \fBAGMiniMapLayoutCreator\fP, \fBAGRadioGroupLayoutCreator\fP, \fBAGRadioLayoutCreator\fP, \fBAGTableLayoutCreator\fP, \fBAGTextLayoutCreator\fP, and \fBAGWindowLayoutCreator\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGLayoutCreator\fP (const \fBAGString\fP &pName)"
.br
.ti -1c
.RI "virtual \fB~AGLayoutCreator\fP ()"
.br
.ti -1c
.RI "virtual \fBAGWidget\fP * \fBcreate\fP (\fBAGWidget\fP *pParent, const \fBAGRect2\fP &pRect, const \fBNode\fP &pNode)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGLayoutCreator::AGLayoutCreator (const \fBAGString\fP & pName)"
.PP
.SS "virtual AGLayoutCreator::~AGLayoutCreator ()\fC [inline, virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGWidget\fP * AGLayoutCreator::create (\fBAGWidget\fP * pParent, const \fBAGRect2\fP & pRect, const \fBNode\fP & pNode)\fC [virtual]\fP"
.PP
Reimplemented in \fBAGMiniMapLayoutCreator\fP, \fBAGCheckBoxLayoutCreator\fP, \fBAGColorButtonLayoutCreator\fP, \fBAGButtonLayoutCreator\fP, \fBAGTableLayoutCreator\fP, \fBAGWindowLayoutCreator\fP, \fBAGTextLayoutCreator\fP, \fBAGEditLayoutCreator\fP, \fBAGListBoxLayoutCreator\fP, \fBAGComboBoxLayoutCreator\fP, \fBAGLayoutLayoutCreator\fP, \fBAGImageLayoutCreator\fP, \fBAGFrameLayoutCreator\fP, \fBAGCellLayoutCreator\fP, \fBAGRadioGroupLayoutCreator\fP, and \fBAGRadioLayoutCreator\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
