.TH "AGMatrix3::Row" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGMatrix3::Row \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float & \fBoperator[]\fP (size_t x)"
.br
.ti -1c
.RI "float \fBoperator[]\fP (size_t x) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGMatrix3\fP * \fBmatrix\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float AGMatrix3::Row::operator[] (size_t x) const\fC [inline]\fP"
.PP
.SS "float& AGMatrix3::Row::operator[] (size_t x)\fC [inline]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBAGMatrix3\fP* \fBAGMatrix3::Row::matrix\fP"
.PP
.SS "int \fBAGMatrix3::Row::y\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
