.TH "AGMoveWidget" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGMoveWidget \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_movewidget.h>\fP
.PP
Inherits \fBAGWidget\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGMoveWidget\fP (\fBAGWidget\fP *pParent, const \fBAGRect2\fP &pRect)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGMoveWidget::AGMoveWidget (\fBAGWidget\fP * pParent, const \fBAGRect2\fP & pRect)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
