.TH "AGMutex" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGMutex \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_mutex.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGMutex\fP ()"
.br
.ti -1c
.RI "\fB~AGMutex\fP ()"
.br
.ti -1c
.RI "void \fBenter\fP ()"
.br
.ti -1c
.RI "void \fBleave\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGMutex::AGMutex ()"
.PP
.SS "AGMutex::~AGMutex ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGMutex::enter ()"
.PP
.SS "void AGMutex::leave ()"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
