.TH "AGProjection" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGProjection \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_painter.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGProjection\fP (const \fBAGRect2\fP &pClip)"
.br
.ti -1c
.RI "\fBAGVector2\fP \fBproject\fP (const \fBAGVector2\fP &p) const "
.br
.ti -1c
.RI "bool \fBpointOk\fP (const \fBAGVector2\fP &p) const "
.br
.ti -1c
.RI "\fBAGRect2\fP \fBproject\fP (const \fBAGRect2\fP &p) const "
.br
.ti -1c
.RI "std::pair< \fBAGRect2\fP, \fBAGRect2\fP > \fBclipRect\fP (\fBAGRect2\fP target, \fBAGRect2\fP src) const "
.br
.ti -1c
.RI "\fBAGRect2\fP \fBclipRect\fP (\fBAGRect2\fP target) const "
.br
.ti -1c
.RI "\fBAGLine2\fP \fBclipLine\fP (\fBAGLine2\fP l) const "
.br
.ti -1c
.RI "void \fBtranslate\fP (const \fBAGVector2\fP &v)"
.br
.ti -1c
.RI "void \fBsetClip\fP (const \fBAGRect2\fP &p)"
.br
.ti -1c
.RI "\fBAGRect2\fP \fBgetRect\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGMatrix3\fP \fBa\fP"
.br
.ti -1c
.RI "\fBAGRect2\fP \fBclip\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGProjection::AGProjection (const \fBAGRect2\fP & pClip)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGLine2\fP AGProjection::clipLine (\fBAGLine2\fP l) const"
.PP
.SS "\fBAGRect2\fP AGProjection::clipRect (\fBAGRect2\fP target) const"
.PP
.SS "std::pair< \fBAGRect2\fP, \fBAGRect2\fP > AGProjection::clipRect (\fBAGRect2\fP target, \fBAGRect2\fP src) const"
.PP
.SS "\fBAGRect2\fP AGProjection::getRect () const"
.PP
.SS "bool AGProjection::pointOk (const \fBAGVector2\fP & p) const"
.PP
.SS "\fBAGRect2\fP AGProjection::project (const \fBAGRect2\fP & p) const"
.PP
.SS "\fBAGVector2\fP AGProjection::project (const \fBAGVector2\fP & p) const"
.PP
.SS "void AGProjection::setClip (const \fBAGRect2\fP & p)"
.PP
.SS "void AGProjection::translate (const \fBAGVector2\fP & v)"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBAGMatrix3\fP \fBAGProjection::a\fP"
.PP
.SS "\fBAGRect2\fP \fBAGProjection::clip\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
