.TH "AGRadioGroup" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGRadioGroup \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_radio.h>\fP
.PP
Inherits \fBAGWidget\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGRadioGroup\fP (\fBAGWidget\fP *pParent, const \fBAGRect2\fP &pr)"
.br
.ti -1c
.RI "virtual \fB~AGRadioGroup\fP ()"
.br
.ti -1c
.RI "virtual void \fBeventChange\fP (const \fBAGString\fP &p)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBAGRadio\fP *r)"
.br
.ti -1c
.RI "void \fBerase\fP (\fBAGRadio\fP *r)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGSignal\fP \fBsigChanged\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGRadioGroup::AGRadioGroup (\fBAGWidget\fP * pParent, const \fBAGRect2\fP & pr)"
.PP
.SS "AGRadioGroup::~AGRadioGroup ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGRadioGroup::add (\fBAGRadio\fP * r)"
.PP
.SS "void AGRadioGroup::erase (\fBAGRadio\fP * r)"
.PP
.SS "void AGRadioGroup::eventChange (const \fBAGString\fP & p)\fC [virtual]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBAGSignal\fP \fBAGRadioGroup::sigChanged\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
