.TH "AGRenderContext" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGRenderContext \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_rendercontext.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGRenderContext\fP ()"
.br
.ti -1c
.RI "\fBAGRenderContext\fP (const \fBAGRenderContext\fP &c)"
.br
.ti -1c
.RI "virtual \fB~AGRenderContext\fP ()"
.br
.ti -1c
.RI "virtual void \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual void \fBend\fP ()"
.br
.ti -1c
.RI "void \fBsetColor\fP (const \fBAGVector4\fP &pColor)"
.br
.ti -1c
.RI "void \fBsetColor\fP (const \fBAGColor\fP &pColor)"
.br
.ti -1c
.RI "void \fBsetTexture\fP (\fBAGGLTexture\fP *pTexture)"
.br
.ti -1c
.RI "void \fBsetLighting\fP (bool pLight)"
.br
.ti -1c
.RI "void \fBsetDepthWrite\fP (bool w)"
.br
.ti -1c
.RI "void \fBsetDepthTest\fP (bool t)"
.br
.ti -1c
.RI "void \fBsetCulling\fP (bool c)"
.br
.ti -1c
.RI "void \fBsetAlpha\fP (float v, GLuint g)"
.br
.ti -1c
.RI "\fBAGGLTexture\fP * \fBgetTexture\fP ()"
.br
.ti -1c
.RI "\fBAGVector4\fP * \fBgetColor\fP ()"
.br
.ti -1c
.RI "\fBAGRenderContext\fP & \fBoperator=\fP (const \fBAGRenderContext\fP &c)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAGRenderContext\fP * \fBgetCurrent\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGRenderContext::AGRenderContext ()"
.PP
.SS "AGRenderContext::AGRenderContext (const \fBAGRenderContext\fP & c)"
.PP
.SS "AGRenderContext::~AGRenderContext ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGRenderContext::begin ()\fC [virtual]\fP"
.PP
.SS "void AGRenderContext::end ()\fC [virtual]\fP"
.PP
.SS "\fBAGVector4\fP * AGRenderContext::getColor ()"
.PP
.SS "\fBAGRenderContext\fP * AGRenderContext::getCurrent ()\fC [static]\fP"
.PP
.SS "\fBAGGLTexture\fP * AGRenderContext::getTexture ()"
.PP
.SS "\fBAGRenderContext\fP & AGRenderContext::operator= (const \fBAGRenderContext\fP & c)"
.PP
.SS "void AGRenderContext::setAlpha (float v, GLuint g)"
.PP
.SS "void AGRenderContext::setColor (const \fBAGColor\fP & pColor)"
.PP
.SS "void AGRenderContext::setColor (const \fBAGVector4\fP & pColor)"
.PP
.SS "void AGRenderContext::setCulling (bool c)"
.PP
.SS "void AGRenderContext::setDepthTest (bool t)"
.PP
.SS "void AGRenderContext::setDepthWrite (bool w)"
.PP
.SS "void AGRenderContext::setLighting (bool pLight)"
.PP
.SS "void AGRenderContext::setTexture (\fBAGGLTexture\fP * pTexture)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
