.TH "AGScreen" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGScreen \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_screen.h>\fP
.PP
Inherits \fBAGPaintTarget\fP.
.PP
Inherited by \fBAGGLScreen\fP, and \fBAGSDLScreen\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual void \fBflip\fP ()"
.br
.ti -1c
.RI "virtual size_t \fBgetWidth\fP () const "
.br
.ti -1c
.RI "virtual size_t \fBgetHeight\fP () const "
.br
.ti -1c
.RI "virtual \fBAGSurface\fP \fBscreenshot\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AGScreen::begin ()\fC [virtual]\fP"
.PP
Reimplemented in \fBAGGLScreen\fP.
.SS "void AGScreen::flip ()\fC [virtual]\fP"
.PP
Reimplemented in \fBAGGLScreen\fP, and \fBAGSDLScreen\fP.
.SS "size_t AGScreen::getHeight () const\fC [virtual]\fP"
.PP
Reimplemented in \fBAGGLScreen\fP, and \fBAGSDLScreen\fP.
.SS "size_t AGScreen::getWidth () const\fC [virtual]\fP"
.PP
Reimplemented in \fBAGGLScreen\fP, and \fBAGSDLScreen\fP.
.SS "\fBAGSurface\fP AGScreen::screenshot ()\fC [virtual]\fP"
.PP
Reimplemented in \fBAGGLScreen\fP, and \fBAGSDLScreen\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
