.TH "AGScreenWidget" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGScreenWidget \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_screenwidget.h>\fP
.PP
Inherits \fBAGWidget\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGScreenWidget\fP ()"
.br
.ti -1c
.RI "virtual \fB~AGScreenWidget\fP ()"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBAGPainter\fP &p)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGScreenWidget::AGScreenWidget ()"
.PP
.SS "AGScreenWidget::~AGScreenWidget ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGScreenWidget::draw (\fBAGPainter\fP & p)\fC [virtual]\fP"
.PP
Reimplemented from \fBAGWidget\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
