.TH "AGShaderProgram" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGShaderProgram \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_glsl.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGShaderProgram\fP (const std::string &pVertexFile, const std::string &pFragFile)"
.br
.ti -1c
.RI "virtual \fB~AGShaderProgram\fP ()"
.br
.ti -1c
.RI "virtual void \fBenable\fP ()"
.br
.ti -1c
.RI "virtual void \fBdisable\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP (float time)"
.br
.ti -1c
.RI "virtual void \fBdoUpdate\fP (float time)"
.br
.ti -1c
.RI "GLint \fBgetLoc\fP (const std::string &pName)"
.br
.ti -1c
.RI "GLint \fBgetAttr\fP (const std::string &pName)"
.br
.ti -1c
.RI "void \fBsendUniform\fP (const std::string &pName, int i)"
.br
.ti -1c
.RI "void \fBsendUniform\fP (const std::string &pName, float f)"
.br
.ti -1c
.RI "void \fBsendUniform\fP (const std::string &pName, const \fBAGVector3\fP &m)"
.br
.ti -1c
.RI "void \fBsendUniform\fP (const std::string &pName, const \fBAGVector4\fP &m)"
.br
.ti -1c
.RI "void \fBsendUniform\fP (const std::string &pName, const \fBAGMatrix4\fP &m)"
.br
.ti -1c
.RI "void \fBsendUniform\fP (const std::string &pName, const std::vector< \fBAGMatrix4\fP > &m)"
.br
.ti -1c
.RI "void \fBsendAttribute\fP (const std::string &pName, const std::vector< float > &vf)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "GLhandleARB \fBp\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGShaderProgram::AGShaderProgram (const std::string & pVertexFile, const std::string & pFragFile)"
.PP
.SS "AGShaderProgram::~AGShaderProgram ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGShaderProgram::disable ()\fC [virtual]\fP"
.PP
.SS "void AGShaderProgram::doUpdate (float time)\fC [virtual]\fP"
.PP
.SS "void AGShaderProgram::enable ()\fC [virtual]\fP"
.PP
.SS "GLint AGShaderProgram::getAttr (const std::string & pName)"
.PP
.SS "GLint AGShaderProgram::getLoc (const std::string & pName)"
.PP
.SS "void AGShaderProgram::sendAttribute (const std::string & pName, const std::vector< float > & vf)"
.PP
.SS "void AGShaderProgram::sendUniform (const std::string & pName, const std::vector< \fBAGMatrix4\fP > & m)"
.PP
.SS "void AGShaderProgram::sendUniform (const std::string & pName, const \fBAGMatrix4\fP & m)"
.PP
.SS "void AGShaderProgram::sendUniform (const std::string & pName, const \fBAGVector4\fP & m)"
.PP
.SS "void AGShaderProgram::sendUniform (const std::string & pName, const \fBAGVector3\fP & m)"
.PP
.SS "void AGShaderProgram::sendUniform (const std::string & pName, float f)"
.PP
.SS "void AGShaderProgram::sendUniform (const std::string & pName, int i)"
.PP
.SS "void AGShaderProgram::update (float time)"
.PP
.SH "Member Data Documentation"
.PP 
.SS "GLhandleARB \fBAGShaderProgram::p\fP\fC [protected]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
