.TH "AGTriangle3" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGTriangle3 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGTriangle3\fP (const \fBAGVector3\fP &v0, const \fBAGVector3\fP &v1, const \fBAGVector3\fP &v2)"
.br
.ti -1c
.RI "\fBAGVector4\fP \fBcollide\fP (const \fBAGLine3\fP &pLine) const "
.br
.ti -1c
.RI "\fBAGString\fP \fBtoString\fP () const "
.br
.ti -1c
.RI "\fBAGVector3\fP \fBoperator[]\fP (int index) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGTriangle3::AGTriangle3 (const \fBAGVector3\fP & v0, const \fBAGVector3\fP & v1, const \fBAGVector3\fP & v2)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGVector4\fP AGTriangle3::collide (const \fBAGLine3\fP & pLine) const"
.PP
.SS "\fBAGVector3\fP AGTriangle3::operator[] (int index) const"
.PP
.SS "\fBAGString\fP AGTriangle3::toString () const"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
