.TH "Animation" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animation \- 
.SH SYNOPSIS
.br
.PP
\fC#include <anim_mesh_data.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimation\fP ()"
.br
.ti -1c
.RI "\fBAnimation\fP (float b, float e, float f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBbegin\fP"
.br
.ti -1c
.RI "float \fBend\fP"
.br
.ti -1c
.RI "float \fBfps\fP"
.br
.ti -1c
.RI "float \fBlen\fP"
.br
.ti -1c
.RI "bool \fBloop\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Animation::Animation ()\fC [inline]\fP"
.PP
.SS "Animation::Animation (float b, float e, float f)\fC [inline]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "float \fBAnimation::begin\fP"
.PP
.SS "float \fBAnimation::end\fP"
.PP
.SS "float \fBAnimation::fps\fP"
.PP
.SS "float \fBAnimation::len\fP"
.PP
.SS "bool \fBAnimation::loop\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
