.TH "src/anim_mesh.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/anim_mesh.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'scene.h'\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_geometry.h'\fP
.br
\fC#include 'scenenode.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'anim_mesh_data.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnimMesh\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
