.TH "src/ant_renderer.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ant_renderer.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ant_renderer.h'\fP
.br
\fC#include 'scene.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_kill.h'\fP
.br
\fC#include 'ag_config.h'\fP
.br
\fC#include 'ag_fbo.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRenderer\fP * \fBgetRenderer\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRenderer\fP * \fBgRenderer\fP = 0"
.br
.ti -1c
.RI "bool \fBusePlainGL\fP = true"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBRenderer\fP* getRenderer ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "\fBRenderer\fP* \fBgRenderer\fP = 0"
.PP
.SS "bool \fBusePlainGL\fP = true"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
