.TH "AntargisGUI" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AntargisGUI \- the GUI-library of the game Battles of Antargis  

.PP
This library consists of different mechanisms to make your life easier with graphical user interfaces: 
.PP
\fBSee also:\fP
.RS 4
\fBWidgets\fP 
.PP
\fBApplication\fP 
.PP
\fBEvent handling\fP 
.RE
.PP

