.TH "AntCamera" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AntCamera \- a camera object for moving over a height map
.PP
This function provides functions for moving a camera about and computation of the used 4x4-matrixes for camera-view and lighting (mainly used for shadows)  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ant_camera.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAntCamera\fP (int w, int h)"
.br
.ti -1c
.RI "void \fBincCameraDistance\fP ()"
.br
.ti -1c
.RI "void \fBdecCameraDistance\fP ()"
.br
.ti -1c
.RI "\fBViewport\fP \fBgetViewport\fP () const "
.br
.ti -1c
.RI "\fBAGMatrix4\fP \fBgetModelview\fP () const "
.br
.ti -1c
.RI "\fBAGMatrix4\fP \fBgetProjection\fP () const "
.br
.ti -1c
.RI "void \fBsetPosition\fP (const \fBAGVector3\fP &p)"
.br
.RI "\fIaffects scenePosition \fP"
.ti -1c
.RI "\fBAGVector4\fP \fBgetCameraPosition\fP () const "
.br
.RI "\fIreturns absolute camera position \fP"
.ti -1c
.RI "\fBAGVector4\fP \fBgetCameraPositionR\fP () const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBgetLightPosition\fP () const "
.br
.ti -1c
.RI "\fBAGVector3\fP \fBgetPosition\fP () const "
.br
.ti -1c
.RI "int \fBgetWidth\fP () const "
.br
.ti -1c
.RI "int \fBgetHeight\fP () const "
.br
.ti -1c
.RI "void \fBsetWidth\fP (int w)"
.br
.ti -1c
.RI "void \fBsetHeight\fP (int h)"
.br
.ti -1c
.RI "\fBAGMatrix4\fP \fBgetLightComplete\fP () const "
.br
.ti -1c
.RI "\fBAGMatrix4\fP \fBgetLightView\fP () const "
.br
.ti -1c
.RI "\fBAGMatrix4\fP \fBgetLightProjectionMatrix\fP () const "
.br
.ti -1c
.RI "\fBAntProjection\fP \fBgetCameraProjection\fP () const "
.br
.ti -1c
.RI "\fBAntProjection\fP \fBgetLightProjection\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
a camera object for moving over a height map
.PP
This function provides functions for moving a camera about and computation of the used 4x4-matrixes for camera-view and lighting (mainly used for shadows) 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AntCamera::AntCamera (int w, int h)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AntCamera::decCameraDistance ()"
.PP
.SS "\fBAGVector4\fP AntCamera::getCameraPosition () const"
.PP
returns absolute camera position 
.PP
.SS "\fBAGVector4\fP AntCamera::getCameraPositionR () const"
.PP
.SS "\fBAntProjection\fP AntCamera::getCameraProjection () const"
.PP
.SS "int AntCamera::getHeight () const"
.PP
.SS "\fBAGMatrix4\fP AntCamera::getLightComplete () const"
.PP
.SS "\fBAGVector4\fP AntCamera::getLightPosition () const"
.PP
.SS "\fBAntProjection\fP AntCamera::getLightProjection () const"
.PP
.SS "\fBAGMatrix4\fP AntCamera::getLightProjectionMatrix () const"
.PP
.SS "\fBAGMatrix4\fP AntCamera::getLightView () const"
.PP
.SS "\fBAGMatrix4\fP AntCamera::getModelview () const"
.PP
.SS "\fBAGVector3\fP AntCamera::getPosition () const"
.PP
.SS "\fBAGMatrix4\fP AntCamera::getProjection () const"
.PP
.SS "\fBViewport\fP AntCamera::getViewport () const"
.PP
.SS "int AntCamera::getWidth () const"
.PP
.SS "void AntCamera::incCameraDistance ()"
.PP
.SS "void AntCamera::setHeight (int h)"
.PP
.SS "void AntCamera::setPosition (const \fBAGVector3\fP & p)"
.PP
affects scenePosition 
.PP
.SS "void AntCamera::setWidth (int w)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
