.TH "AntFragProgram" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AntFragProgram \- 
.SH SYNOPSIS
.br
.PP
\fC#include <glsl.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAntFragProgram\fP (const std::string &pFile)"
.br
.ti -1c
.RI "\fBAntFragProgram\fP ()"
.br
.ti -1c
.RI "\fB~AntFragProgram\fP ()"
.br
.ti -1c
.RI "bool \fBvalid\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAntShaderProgram\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AntFragProgram::AntFragProgram (const std::string & pFile)"
.PP
.SS "AntFragProgram::AntFragProgram ()"
.PP
.SS "AntFragProgram::~AntFragProgram ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool AntFragProgram::valid () const"
.PP
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBAntShaderProgram\fP\fC [friend]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
