.TH "AntPlane" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AntPlane \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ant_frustum.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAntPlane\fP (const \fBAGVector3\fP &dir, float offset)"
.br
.ti -1c
.RI "bool \fBinside\fP (const \fBAGVector3\fP &v) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAntPlane\fP &p)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AntPlane::AntPlane (const \fBAGVector3\fP & dir, float offset)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool AntPlane::inside (const \fBAGVector3\fP & v) const\fC [inline]\fP"
.PP
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & o, const \fBAntPlane\fP & p)\fC [friend]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
