.TH "AntShadowShader" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AntShadowShader \- 
.SH SYNOPSIS
.br
.PP
\fC#include <glsl.h>\fP
.PP
Inherits \fBAntShaderProgram\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAntShadowShader\fP (const std::string &pVertexFile, const std::string &pFragFile)"
.br
.ti -1c
.RI "void \fBdoUpdate\fP (float time)"
.br
.ti -1c
.RI "virtual void \fBenable\fP ()"
.br
.ti -1c
.RI "virtual void \fBdisable\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AntShadowShader::AntShadowShader (const std::string & pVertexFile, const std::string & pFragFile)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AntShadowShader::disable ()\fC [virtual]\fP"
.PP
Reimplemented from \fBAntShaderProgram\fP.
.SS "void AntShadowShader::doUpdate (float time)\fC [virtual]\fP"
.PP
Reimplemented from \fBAntShaderProgram\fP.
.SS "void AntShadowShader::enable ()\fC [virtual]\fP"
.PP
Reimplemented from \fBAntShaderProgram\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
