.TH "BinaryStringOut" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryStringOut \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_serial.h>\fP
.PP
Inherits \fBBinaryOut\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryStringOut\fP ()"
.br
.ti -1c
.RI "virtual \fB~BinaryStringOut\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (char c)"
.br
.ti -1c
.RI "std::string \fBgetString\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BinaryStringOut::BinaryStringOut ()"
.PP
.SS "BinaryStringOut::~BinaryStringOut ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "std::string BinaryStringOut::getString () const"
.PP
.SS "void BinaryStringOut::write (char c)\fC [virtual]\fP"
.PP
Reimplemented from \fBBinaryOut\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
