.TH "BinaryStringIn" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryStringIn \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_serial.h>\fP
.PP
Inherits \fBBinaryIn\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryStringIn\fP (const std::string &pText)"
.br
.ti -1c
.RI "virtual bool \fBeof\fP ()"
.br
.ti -1c
.RI "virtual char \fBread\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BinaryStringIn::BinaryStringIn (const std::string & pText)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool BinaryStringIn::eof ()\fC [virtual]\fP"
.PP
Reimplemented from \fBBinaryIn\fP.
.SS "char BinaryStringIn::read ()\fC [virtual]\fP"
.PP
Reimplemented from \fBBinaryIn\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
