.TH "BinaryFileIn" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryFileIn \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_serial.h>\fP
.PP
Inherits \fBBinaryIn\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryFileIn\fP (const std::string &pName)"
.br
.ti -1c
.RI "virtual \fB~BinaryFileIn\fP ()"
.br
.ti -1c
.RI "virtual bool \fBeof\fP ()"
.br
.ti -1c
.RI "virtual char \fBread\fP ()"
.br
.ti -1c
.RI "size_t \fBpos\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BinaryFileIn::BinaryFileIn (const std::string & pName)"
.PP
.SS "BinaryFileIn::~BinaryFileIn ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool BinaryFileIn::eof ()\fC [virtual]\fP"
.PP
Reimplemented from \fBBinaryIn\fP.
.SS "size_t BinaryFileIn::pos () const"
.PP
.SS "char BinaryFileIn::read ()\fC [virtual]\fP"
.PP
Reimplemented from \fBBinaryIn\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
