.TH "BinaryFileOut" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryFileOut \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_serial.h>\fP
.PP
Inherits \fBBinaryOut\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryFileOut\fP (const std::string &pName)"
.br
.ti -1c
.RI "virtual \fB~BinaryFileOut\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (char c)"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.ti -1c
.RI "size_t \fBpos\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BinaryFileOut::BinaryFileOut (const std::string & pName)"
.PP
.SS "BinaryFileOut::~BinaryFileOut ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void BinaryFileOut::flush ()"
.PP
.SS "size_t BinaryFileOut::pos () const"
.PP
.SS "void BinaryFileOut::write (char c)\fC [virtual]\fP"
.PP
Reimplemented from \fBBinaryOut\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
