.TH "D" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_debug.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBD\fP (std::string text)"
.br
.RI "\fIthe given text will be output on creation and deletion of this object \fP"
.ti -1c
.RI "\fB~D\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A helper class for tracing the program's flow Use it by instantiating it with a proper name, or simply use TRACE; (or CTRACE for classes) in your functions 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "D::D (std::string text)"
.PP
the given text will be output on creation and deletion of this object 
.PP
.SS "AGEXPORT D::~D ()"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
