.TH "3d-engine of BoA" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3d-engine of BoA \- a very small 3d-engine used within BoA  

.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAntCamera\fP"
.br
.RI "\fIa camera object for moving over a height map
.PP
This function provides functions for moving a camera about and computation of the used 4x4-matrixes for camera-view and lighting (mainly used for shadows) \fP"
.ti -1c
.RI "class \fBScene\fP"
.br
.RI "\fIquad-tree based scene-manager
.PP
\fBScene\fP is scene-manager. it holds all the 3d-objects (meshes and particles). These objects are stored in a \fBQuadTree\fP (could easily be exchanged for an octree, if needed). It takes further for drawing modes like picking, shadow-rendering and depth-drawing (for shadow-depth-computation). It contains a camera-object! So in the current state it's not possible to render the same scene from to places at the same time. \fP"
.in -1c
.SH "Detailed Description"
.PP 
a very small 3d-engine used within BoA 
.PP
For more information go to
.PP
\fBSee also:\fP
.RS 4
\fBScene\fP 
.RE
.PP

