.TH "Heuristic" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Heuristic \- 
.SH SYNOPSIS
.br
.PP
\fC#include <path.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHeuristic\fP (const \fBAGVector2\fP &pTo, \fBHeuristicFunction\fP *f)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBPath\fP &a, const \fBPath\fP &b)"
.br
.ti -1c
.RI "float \fBdistance\fP (const \fBAGVector2\fP &from)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Heuristic::Heuristic (const \fBAGVector2\fP & pTo, \fBHeuristicFunction\fP * f)\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "float Heuristic::distance (const \fBAGVector2\fP & from)"
.PP
.SS "bool Heuristic::operator() (const \fBPath\fP & a, const \fBPath\fP & b)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
