.TH "src/jobs.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/jobs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJob\fP"
.br
.ti -1c
.RI "class \fBRestJob\fP"
.br
.ti -1c
.RI "class \fBMoveJob\fP"
.br
.ti -1c
.RI "class \fBFightJob\fP"
.br
.ti -1c
.RI "class \fBFetchJob\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
