.TH "src/mesh.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mesh.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'scene.h'\fP
.br
\fC#include 'vertex_array.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include 'mesh_data.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMesh\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
