.TH "MeshOptimizer" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeshOptimizer \- 
.SH SYNOPSIS
.br
.PP
\fC#include <mesh_optimizer.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeshOptimizer\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (const \fBMeshVertex\fP &v)"
.br
.ti -1c
.RI "\fBVertexArray\fP \fBgetArray\fP ()"
.br
.ti -1c
.RI "\fBAGVector4\fP \fBgetV\fP (size_t i)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MeshOptimizer::MeshOptimizer ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void MeshOptimizer::add (const \fBMeshVertex\fP & v)"
.PP
.SS "\fBVertexArray\fP MeshOptimizer::getArray ()"
.PP
.SS "\fBAGVector4\fP MeshOptimizer::getV (size_t i)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
