.TH "src/mesh_optimizer.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mesh_optimizer.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mesh_optimizer.h'\fP
.br
\fC#include <ag_debug.h>\fP
.br
\fC#include <ag_serial.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMeshTriangle\fP"
.br
.ti -1c
.RI "struct \fBTriCompare\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBMeshOptimizer\fP \fBloadFromText\fP (const std::string &pText, bool withTex, float zoom)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBMeshOptimizer\fP loadFromText (const std::string & pText, bool withTex, float zoom)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
