.TH "src/minimap.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/minimap.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'minimap.h'\fP
.br
\fC#include <ag_layoutfactory.h>\fP
.br
\fC#include <ag_screen.h>\fP
.br
\fC#include <ag_profiler.h>\fP
.br
\fC#include 'ant_app.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGMiniMapLayoutCreator\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAP_BORDER\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (\fBMiniMap\fP)"
.br
.ti -1c
.RI "\fBMiniMap\fP * \fBtoMiniMap\fP (\fBAGWidget\fP *w)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MAP_BORDER"
.PP
.SH "Function Documentation"
.PP 
.SS "IMPLEMENT_COMPONENT_FACTORY (\fBMiniMap\fP)"
.PP
.SS "\fBMiniMap\fP* toMiniMap (\fBAGWidget\fP * w)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
