.TH "src/minimap.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/minimap.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'map.h'\fP
.br
\fC#include <ag_widget.h>\fP
.br
\fC#include <ag_texture.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMiniMap\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBMiniMap\fP * \fBtoMiniMap\fP (\fBAGWidget\fP *w)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBMiniMap\fP* toMiniMap (\fBAGWidget\fP * w)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
