.TH "MWidgetSet" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MWidgetSet \- 
.SH SYNOPSIS
.br
.PP
Inherits std::set< AGWidget * >.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~MWidgetSet\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MWidgetSet::~MWidgetSet ()\fC [virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
