.TH "NewDecal" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewDecal \- 
.SH SYNOPSIS
.br
.PP
\fC#include <new_decal.h>\fP
.PP
Inherits \fBSceneNode\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewDecal\fP (\fBScene\fP *pScene, \fBAGVector2\fP pos, float size, \fBHeightMap\fP *pMap, const std::string &pTexture)"
.br
.ti -1c
.RI "void \fBsetPos\fP (const \fBAGVector3\fP &pPos)"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "virtual void \fBmapChanged\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
not yet used decals are currently a little bad in BoA. Should be reworked!!! 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NewDecal::NewDecal (\fBScene\fP * pScene, \fBAGVector2\fP pos, float size, \fBHeightMap\fP * pMap, const std::string & pTexture)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void NewDecal::draw ()\fC [virtual]\fP"
.PP
Reimplemented from \fBSceneNode\fP.
.SS "void NewDecal::init ()"
.PP
.SS "void NewDecal::mapChanged ()\fC [virtual]\fP"
.PP
.SS "void NewDecal::setPos (const \fBAGVector3\fP & pPos)\fC [virtual]\fP"
.PP
Reimplemented from \fBSceneNode\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
