.TH "Parser" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_xml.h>\fP
.PP
Inherited by \fBDomParser\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Parser\fP ()"
.br
.ti -1c
.RI "void \fBparse\fP (const std::string &pData)"
.br
.ti -1c
.RI "size_t \fBgetLine\fP () const "
.br
.ti -1c
.RI "virtual void \fBsimpleTag\fP (const \fBAGString\fP &pName, const \fBNode::Attributes\fP &pAttributes)"
.br
.ti -1c
.RI "virtual void \fBstartTag\fP (const \fBAGString\fP &pName, const \fBNode::Attributes\fP &pAttributes)"
.br
.ti -1c
.RI "virtual void \fBendTag\fP (const \fBAGString\fP &pName)"
.br
.ti -1c
.RI "virtual void \fBtext\fP (const \fBAGString\fP &pText)"
.br
.ti -1c
.RI "virtual void \fBcomment\fP (const \fBAGString\fP &pText)"
.br
.ti -1c
.RI "virtual void \fBheader\fP (const \fBAGString\fP &pText)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Parser::~Parser ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void Parser::comment (const \fBAGString\fP & pText)\fC [virtual]\fP"
.PP
Reimplemented in \fBDomParser\fP.
.SS "void Parser::endTag (const \fBAGString\fP & pName)\fC [virtual]\fP"
.PP
Reimplemented in \fBDomParser\fP.
.SS "size_t Parser::getLine () const"
.PP
.SS "void Parser::header (const \fBAGString\fP & pText)\fC [virtual]\fP"
.PP
Reimplemented in \fBDomParser\fP.
.SS "void Parser::parse (const std::string & pData)"
.PP
Reimplemented in \fBDomParser\fP.
.SS "void Parser::simpleTag (const \fBAGString\fP & pName, const \fBNode::Attributes\fP & pAttributes)\fC [virtual]\fP"
.PP
Reimplemented in \fBDomParser\fP.
.SS "void Parser::startTag (const \fBAGString\fP & pName, const \fBNode::Attributes\fP & pAttributes)\fC [virtual]\fP"
.PP
Reimplemented in \fBDomParser\fP.
.SS "void Parser::text (const \fBAGString\fP & pText)\fC [virtual]\fP"
.PP
Reimplemented in \fBDomParser\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
