.TH "Path" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Path \- 
.SH SYNOPSIS
.br
.PP
\fC#include <path.h>\fP
.PP
Inherits std::list< SimpleGraph::Node * >.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPath\fP ()"
.br
.ti -1c
.RI "float \fBgetWeight\fP (\fBHeuristic\fP *h) const "
.br
.ti -1c
.RI "void \fBpush\fP (\fBSimpleGraph::Node\fP *n, float w)"
.br
.ti -1c
.RI "void \fBpaint\fP (const \fBAGRect2\fP &r, \fBAGPaintTarget\fP &t, float scale)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBweight\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Path::Path ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "float Path::getWeight (\fBHeuristic\fP * h) const"
.PP
.SS "void Path::paint (const \fBAGRect2\fP & r, \fBAGPaintTarget\fP & t, float scale)"
.PP
.SS "void Path::push (\fBSimpleGraph::Node\fP * n, float w)"
.PP
.SH "Member Data Documentation"
.PP 
.SS "float \fBPath::weight\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
