.TH "PathWeighter" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PathWeighter \- 
.SH SYNOPSIS
.br
.PP
\fC#include <path.h>\fP
.PP
Inherits \fBAGRubyObject\fP.
.PP
Inherited by \fBMapPathWeighter\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~PathWeighter\fP ()"
.br
.ti -1c
.RI "virtual float \fBweight\fP (float h0, float h1)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PathWeighter::~PathWeighter ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "float PathWeighter::weight (float h0, float h1)\fC [virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
