.TH "src/quadtree.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/quadtree.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.br
\fC#include <ag_debug.h>\fP
.br
\fC#include <set>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQuadTree< T >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
