.TH "Resource" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Resource \- 
.SH SYNOPSIS
.br
.PP
\fC#include <resource.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResource\fP ()"
.br
.ti -1c
.RI "void \fBsaveXML\fP (\fBNode\fP &node) const "
.br
.ti -1c
.RI "void \fBloadXML\fP (const \fBNode\fP &node)"
.br
.ti -1c
.RI "float \fBget\fP (const std::string &pName)"
.br
.ti -1c
.RI "void \fBadd\fP (const std::string &pName, float value)"
.br
.ti -1c
.RI "void \fBsub\fP (const std::string &pName, float value)"
.br
.ti -1c
.RI "void \fBset\fP (const std::string &pName, float value)"
.br
.ti -1c
.RI "std::map< std::string, float > \fBgetAll\fP () const "
.br
.ti -1c
.RI "void \fBtakeAll\fP (\fBResource\fP &r)"
.br
.RI "\fItake everything, that's in r and put it into 'this' \fP"
.ti -1c
.RI "void \fBtake\fP (\fBResource\fP &r, const std::string &pName)"
.br
.RI "\fItake everything of type pname, that's in r and put it into 'this' \fP"
.ti -1c
.RI "bool \fBempty\fP () const "
.br
.RI "\fIcheck if the 'bag' is empty \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBResource\fP manages resources with BoA. Every entity has some kind of 'bag', where everything is stored. This is it. Resources are identified by strings. You can get,set,sub and add resources.
.PP
FIXME: maybe remove \fBResource\fP from c++?? 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Resource::Resource ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void Resource::add (const std::string & pName, float value)"
.PP
.SS "bool Resource::empty () const"
.PP
check if the 'bag' is empty 
.PP
.SS "float Resource::get (const std::string & pName)"
.PP
.SS "std::map< std::string, float > Resource::getAll () const"
.PP
.SS "void Resource::loadXML (const \fBNode\fP & node)"
.PP
.SS "void Resource::saveXML (\fBNode\fP & node) const"
.PP
.SS "void Resource::set (const std::string & pName, float value)"
.PP
.SS "void Resource::sub (const std::string & pName, float value)"
.PP
.SS "void Resource::take (\fBResource\fP & r, const std::string & pName)"
.PP
take everything of type pname, that's in r and put it into 'this' 
.PP
.SS "void Resource::takeAll (\fBResource\fP & r)"
.PP
take everything, that's in r and put it into 'this' 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
