.TH "RestJob" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RestJob \- 
.SH SYNOPSIS
.br
.PP
\fC#include <jobs.h>\fP
.PP
Inherits \fBJob\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRestJob\fP ()"
.br
.ti -1c
.RI "\fBRestJob\fP (float pTime)"
.br
.ti -1c
.RI "virtual \fB~RestJob\fP ()"
.br
.ti -1c
.RI "void \fBmove\fP (\fBAntEntity\fP *e, float ptime)"
.br
.ti -1c
.RI "virtual void \fBsaveXML\fP (\fBNode\fP &pNode) const "
.br
.ti -1c
.RI "virtual void \fBloadXML\fP (const \fBNode\fP &pNode)"
.br
.ti -1c
.RI "virtual \fBAGString\fP \fBxmlName\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RestJob::RestJob ()"
.PP
.SS "RestJob::RestJob (float pTime)"
.PP
.SS "RestJob::~RestJob ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void RestJob::loadXML (const \fBNode\fP & pNode)\fC [virtual]\fP"
.PP
Reimplemented from \fBJob\fP.
.SS "void RestJob::move (\fBAntEntity\fP * e, float ptime)\fC [virtual]\fP"
.PP
Reimplemented from \fBJob\fP.
.SS "void RestJob::saveXML (\fBNode\fP & pNode) const\fC [virtual]\fP"
.PP
Reimplemented from \fBJob\fP.
.SS "\fBAGString\fP RestJob::xmlName () const\fC [virtual]\fP"
.PP
Reimplemented from \fBJob\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
