.TH "gui/src/sge_config.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/sge_config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSGE_VER\fP   030809"
.br
.ti -1c
.RI "#define \fB_SGE_C_AND_CPP\fP"
.br
.ti -1c
.RI "#define \fB_SGE_HAVE_IMG\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _SGE_C_AND_CPP"
.PP
.SS "#define _SGE_HAVE_IMG"
.PP
.SS "#define SGE_VER   030809"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
