.TH "SimpleGraph::Node" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleGraph::Node \- 
.SH SYNOPSIS
.br
.PP
\fC#include <path.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Node\fP ()"
.br
.ti -1c
.RI "std::map< \fBNode\fP *, float > \fBgetNextNodes\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGVector2\fP \fBp\fP"
.br
.ti -1c
.RI "\fBEdges\fP \fBedges\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SimpleGraph::Node::~Node ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "std::map< \fBSimpleGraph::Node\fP *, float > SimpleGraph::Node::getNextNodes ()"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBEdges\fP \fBSimpleGraph::Node::edges\fP"
.PP
.SS "\fBAGVector2\fP \fBSimpleGraph::Node::p\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
