.TH "SimpleGraph::EdgeSort" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleGraph::EdgeSort \- 
.SH SYNOPSIS
.br
.PP
\fC#include <path.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBEdge\fP *a, const \fBEdge\fP *b)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool SimpleGraph::EdgeSort::operator() (const \fBEdge\fP * a, const \fBEdge\fP * b)\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
