.TH "Smoke" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Smoke \- 
.SH SYNOPSIS
.br
.PP
\fC#include <smoke.h>\fP
.PP
Inherits \fBSceneNode\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSmoke\fP (\fBScene\fP *pScene, float f)"
.br
.RI "\fImake some smoke (or fire) in \fBScene\fP pScene with output frequency f \fP"
.ti -1c
.RI "void \fBsetFire\fP (bool f)"
.br
.ti -1c
.RI "void \fBsetMaxTime\fP (float m)"
.br
.RI "\fImaximal time for a particle to live \fP"
.ti -1c
.RI "void \fBadvance\fP (float time)"
.br
.RI "\fIadvance the smoke-particles; generate new ones; discard old ones \fP"
.ti -1c
.RI "virtual bool \fBtransparent\fP ()"
.br
.RI "\fIlet \fBScene\fP take care of drawing order for transparency \fP"
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBsetEnabled\fP (bool f)"
.br
.RI "\fIdisable the generation of new particles (smoke will fade slowly) \fP"
.in -1c
.SH "Detailed Description"
.PP 
some very simple particle engine for displaying smoke and ugly fire. 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Smoke::Smoke (\fBScene\fP * pScene, float f)"
.PP
make some smoke (or fire) in \fBScene\fP pScene with output frequency f 
.PP
.SH "Member Function Documentation"
.PP 
.SS "void Smoke::advance (float time)\fC [virtual]\fP"
.PP
advance the smoke-particles; generate new ones; discard old ones 
.PP
Reimplemented from \fBSceneNode\fP.
.SS "void Smoke::draw ()\fC [virtual]\fP"
.PP
Reimplemented from \fBSceneNode\fP.
.SS "void Smoke::setEnabled (bool f)"
.PP
disable the generation of new particles (smoke will fade slowly) 
.PP
.SS "void Smoke::setFire (bool f)"
.PP
if f is true this object will display a fire - otherwise it's smoke default is smoke 
.SS "void Smoke::setMaxTime (float m)"
.PP
maximal time for a particle to live 
.PP
.SS "virtual bool Smoke::transparent ()\fC [inline, virtual]\fP"
.PP
let \fBScene\fP take care of drawing order for transparency 
.PP
Reimplemented from \fBSceneNode\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
