.TH "src/smoke.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/smoke.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ant_renderer.h'\fP
.br
\fC#include 'scene.h'\fP
.br
\fC#include 'smoke.h'\fP
.br
\fC#include 'ag_texturecache.h'\fP
.br
\fC#include 'ag_rendercontext.h'\fP
.br
\fC#include 'ag_main.h'\fP
.br
\fC#include 'map.h'\fP
.br
\fC#include 'ag_config.h'\fP
.br
\fC#include 'ag_profiler.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsmokeEnabled\fP ()"
.br
.ti -1c
.RI "float \fBrandf\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBgSmoke\fP"
.br
.ti -1c
.RI "long \fBlastSmokeTest\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float randf ()"
.PP
.SS "bool smokeEnabled ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "bool \fBgSmoke\fP"
.PP
.SS "long \fBlastSmokeTest\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
