.TH "src/smoke.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/smoke.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'scenenode.h'\fP
.br
\fC#include 'ag_texture.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSmoke\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
