.TH "SortOrder" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SortOrder \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSortOrder\fP ()"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBSceneNode\fP *n1, const \fBSceneNode\fP *n2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a sorting class, too. It sorts by the given 'SortOrder' of the scene-nodes 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SortOrder::SortOrder ()\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool SortOrder::operator() (const \fBSceneNode\fP * n1, const \fBSceneNode\fP * n2)\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
