.TH "src/terrain.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/terrain.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'terrain.h'\fP
.br
\fC#include <ag_texturecache.h>\fP
.br
\fC#include <ag_rendercontext.h>\fP
.br
\fC#include <ag_profiler.h>\fP
.br
\fC#include <ag_config.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgetTerrainTriangleSize\fP ()"
.br
.ti -1c
.RI "int \fBgetTerrainDownScale\fP ()"
.br
.ti -1c
.RI "int \fBgetTerrainDownScaleZ\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int getTerrainDownScale ()"
.PP
.SS "int getTerrainDownScaleZ ()"
.PP
.SS "int getTerrainTriangleSize ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
