.TH "TriCompare" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TriCompare \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriCompare\fP (\fBMeshOptimizer\fP *p, \fBAGVector3\fP cam)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBMeshTriangle\fP &t1, const \fBMeshTriangle\fP &t2)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMeshOptimizer\fP * \fBo\fP"
.br
.ti -1c
.RI "\fBAGVector3\fP \fBc\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TriCompare::TriCompare (\fBMeshOptimizer\fP * p, \fBAGVector3\fP cam)\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool TriCompare::operator() (const \fBMeshTriangle\fP & t1, const \fBMeshTriangle\fP & t2)\fC [inline]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBAGVector3\fP \fBTriCompare::c\fP"
.PP
.SS "\fBMeshOptimizer\fP* \fBTriCompare::o\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
