.TH "VertexArrayShader" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VertexArrayShader \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vertex_array.h>\fP
.PP
Inherits \fBVertexArray\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVertexArrayShader\fP (\fBAntShaderProgram\fP *_p)"
.br
.ti -1c
.RI "\fB~VertexArrayShader\fP ()"
.br
.ti -1c
.RI "void \fBaddAttribute\fP (const std::string &pName, const std::vector< float > &a)"
.br
.RI "\fIadds attributes to each vertex. the size of a should equal the vertex count \fP"
.ti -1c
.RI "virtual void \fBdraw\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBVertexArrayShader\fP adds shader-support to vertex-arrays. You might need to attach data to each vertex. You can do so by calling addAttribute(.,.). 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VertexArrayShader::VertexArrayShader (\fBAntShaderProgram\fP * _p)"
.PP
.SS "VertexArrayShader::~VertexArrayShader ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void VertexArrayShader::addAttribute (const std::string & pName, const std::vector< float > & a)"
.PP
adds attributes to each vertex. the size of a should equal the vertex count 
.PP
.SS "void VertexArrayShader::draw ()\fC [virtual]\fP"
.PP
Reimplemented from \fBVertexArray\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
