.TH "Viewport" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Viewport \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ant_projection.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator GLint *)\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBviewport\fP [4]"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Viewport::operator GLint *) () const\fC [inline]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "GLint \fBViewport::viewport\fP[4]"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
