.TH "src/water.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/water.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'water.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_kill.h'\fP
.br
\fC#include 'ag_rendercontext.h'\fP
.br
\fC#include 'ag_profiler.h'\fP
.br
\fC#include 'ag_config.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAntWaterShader\fP * \fBgetWaterShader\fP ()"
.br
.ti -1c
.RI "bool \fBuseWaterAnimation\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAntWaterShader\fP * \fBgWaterShader\fP = 0"
.br
.ti -1c
.RI "static int \fBgWaterAnim\fP = -10"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAntWaterShader\fP* getWaterShader ()"
.PP
.SS "bool useWaterAnimation ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "int \fBgWaterAnim\fP = -10\fC [static]\fP"
.PP
.SS "\fBAntWaterShader\fP* \fBgWaterShader\fP = 0"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
