require 'rake/clean.rb'


Dir.chdir(File.split(File.split(__FILE__)[0])[0])


task './starter'=>File.join("main","starter.cc") do
	require 'antconfig.rb'
	debug="antargis.so -g"
	debug="-g"
  cmd="g++ -o starter -L. -lantargis main/starter.cc #{debug} "+$CONFIG["CFLAGS"]+" "+$CONFIG["INCLUDEPATH"]+" "+`#{$CONFIG["SDL_CONFIG"]} --libs`.chomp+" -l"+CONFIG["RUBY_SO_NAME"]
  cmd="g++ -ggdb -o starter libantargis.a main/starter.cc #{debug} "+$CONFIG["CFLAGS"]+" "+$CONFIG["LIBS"]+" -framework OpenGL  "+$CONFIG["INCLUDEPATH"]+" "+`#{$CONFIG["SDL_CONFIG"]} --libs`.chomp+" -l"+CONFIG["RUBY_SO_NAME"]
	cmd.gsub!("-arch ppc","")
	sh cmd
end

task :starterPrg=>'./starter'

CLEAN << Dir["starter"]