require 'rake/clean.rb'


Dir.chdir(File.split(File.split(__FILE__)[0])[0])


task 'starter'=>"main/starter.cc" do
	require 'antconfig.rb'
	cmd="g++ -o starter main/starter.cc "+$CONFIG["CFLAGS"]+" "+$CONFIG["INCLUDEPATH"]+" "+`sdl-config --libs`.chomp+" -l"+CONFIG["RUBY_SO_NAME"]
	cmd.gsub!("-arch ppc","")
	sh cmd
end

#task :starter=>'starter'

CLEAN << Dir["starter"]