/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Libantargis_WRAP_H_
#define SWIG_Libantargis_WRAP_H_

class Swig::Director;


class SwigDirector_MiniMap : public MiniMap, public Swig::Director {

public:
    SwigDirector_MiniMap(VALUE self, AGWidget *pParent, AGRect const &r, AntargisMap *pMap, AGRect const &pViewRect);
    virtual void draw(AGPainter &p);
};


class SwigDirector_CompleteIsoView : public CompleteIsoView, public Swig::Director {

public:
    SwigDirector_CompleteIsoView(VALUE self, AGWidget *parent, AGRect r, Pos3D p, AntargisMap *map);
    virtual bool eventDragBy(AGEvent const *event, AGPoint const &pDiff);
};


class SwigDirector_EditIsoView : public EditIsoView, public Swig::Director {

public:
    SwigDirector_EditIsoView(VALUE self, AGWidget *parent, AGRect r, Pos3D p, AntargisMap *map);
    virtual bool eventDragBy(AGEvent const *event, AGPoint const &pDiff);
};


#endif
