/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Libantargis_WRAP_H_
#define SWIG_Libantargis_WRAP_H_

class Swig::Director;


class SwigDirector_AGRubyObject : public AGRubyObject, public Swig::Director {

public:
    SwigDirector_AGRubyObject(VALUE self);
    virtual ~SwigDirector_AGRubyObject();
};


class SwigDirector_AGEvent : public AGEvent, public Swig::Director {

public:
    SwigDirector_AGEvent(VALUE self, AGListener *pCaller, std::string const &pName, SDL_Event const *pEvent = 0);
    virtual ~SwigDirector_AGEvent();
};


class SwigDirector_AGListener : public AGListener, public Swig::Director {

public:
    SwigDirector_AGListener(VALUE self);
    virtual ~SwigDirector_AGListener();
    virtual bool signal(AGEvent *m);
};


class SwigDirector_AGCPPListener : public AGCPPListener, public Swig::Director {

public:
    SwigDirector_AGCPPListener(VALUE self);
    virtual ~SwigDirector_AGCPPListener();
    virtual bool signal(AGEvent *m) const;
};


class SwigDirector_AGSignal : public AGSignal, public Swig::Director {

public:
    SwigDirector_AGSignal(VALUE self);
    SwigDirector_AGSignal(VALUE self, AGMessageObject *pCaller);
    SwigDirector_AGSignal(VALUE self, AGMessageObject *pCaller, std::string const &pName);
    virtual ~SwigDirector_AGSignal();
};


class SwigDirector_AGMessageObject : public AGMessageObject, public Swig::Director {

public:
    SwigDirector_AGMessageObject(VALUE self);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventActive(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool signal(AGEvent *m);
    virtual ~SwigDirector_AGMessageObject();
    virtual Uint8 getButtonState() const;
    virtual AGVector2 getMousePosition() const;
};


class SwigDirector_AGWidget : public AGWidget, public Swig::Director {

public:
    SwigDirector_AGWidget(VALUE self, AGWidget *pParent, AGRect2 const &r);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGWidget();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGColorButton : public AGColorButton, public Swig::Director {

public:
    SwigDirector_AGColorButton(VALUE self, AGWidget *pParent, AGRect2 const &r, int x, int y);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGColorButton();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGGLWidget : public AGGLWidget, public Swig::Director {

public:
    SwigDirector_AGGLWidget(VALUE self, AGWidget *pParent, AGRect2 const &r);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGGLWidget();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawGL();
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual void drawAll(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_Parser : public Parser, public Swig::Director {

public:
    SwigDirector_Parser(VALUE self);
    virtual void simpleTag(std::string const &pName, Node::Attributes const &pAttributes);
    virtual ~SwigDirector_Parser();
    virtual void startTag(std::string const &pName, Node::Attributes const &pAttributes);
    virtual void endTag(std::string const &pName);
    virtual void text(std::string const &pText);
    virtual void comment(std::string const &pText);
    virtual void header(std::string const &pText);
};


class SwigDirector_DomParser : public DomParser, public Swig::Director {

public:
    SwigDirector_DomParser(VALUE self);
    virtual void simpleTag(std::string const &pName, Node::Attributes const &pAttributes);
    virtual ~SwigDirector_DomParser();
    virtual void startTag(std::string const &pName, Node::Attributes const &pAttributes);
    virtual void endTag(std::string const &pName);
    virtual void text(std::string const &pText);
    virtual void comment(std::string const &pText);
    virtual void header(std::string const &pText);
};


class SwigDirector_AGLayout : public AGLayout, public Swig::Director {

public:
    SwigDirector_AGLayout(VALUE self, AGWidget *pgParent, std::string const &pXMLData);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGLayout();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGDialog : public AGDialog, public Swig::Director {

public:
    SwigDirector_AGDialog(VALUE self, AGWidget *pgParent, std::string const &pXMLData);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGDialog();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventOk(AGEvent *event);
    virtual bool eventCancel(AGEvent *event);
    virtual bool eventClose(AGEvent *event);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGApplication : public AGApplication, public Swig::Director {

public:
    SwigDirector_AGApplication(VALUE self);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventActive(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool signal(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m2);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual void mark();
    virtual bool eventFrame(float pTime);
    virtual bool eventFrameEnd(float pTime);
    virtual void eventChangedRes();
    virtual ~SwigDirector_AGApplication();
    virtual bool eventIdle();
    virtual void tryQuit();
    virtual Uint8 getButtonState() const;
    virtual AGVector2 getMousePosition() const;
    virtual void draw();
    virtual void prepareDraw();
};


class SwigDirector_AGButton : public AGButton, public Swig::Director {

public:
    SwigDirector_AGButton(VALUE self, AGWidget *pParent, AGRect2 const &r, std::string const &pText, int id = -1);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual void setChecked(bool pChecked);
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void setWidth(float w);
    virtual void setHeight(float w);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual std::string getCaption() const;
    virtual bool canFocus() const;
    virtual ~SwigDirector_AGButton();
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual void clear();
    virtual bool eventMouseEnter();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventHide();
    virtual bool eventMouseLeave();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGText : public AGText, public Swig::Director {

public:
    SwigDirector_AGText(VALUE self, AGWidget *pParent, AGRect2 const &pRect, std::string const &pText, AGFont const &pFont);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGText();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGCaption : public AGCaption, public Swig::Director {

public:
    SwigDirector_AGCaption(VALUE self, AGWidget *pParent, AGRect2 const &pRect, std::string const &pText, AGFont const &pFont, AGBackground const &pBG);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGCaption();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGCheckBox : public AGCheckBox, public Swig::Director {

public:
    SwigDirector_AGCheckBox(VALUE self, AGWidget *pParent, AGRect2 pRect);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual void setChecked(bool pChecked);
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void setWidth(float w);
    virtual void setHeight(float w);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual std::string getCaption() const;
    virtual bool canFocus() const;
    virtual ~SwigDirector_AGCheckBox();
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual void clear();
    virtual bool eventMouseEnter();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventHide();
    virtual bool eventMouseLeave();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGEditLine : public AGEditLine, public Swig::Director {

public:
    SwigDirector_AGEditLine(VALUE self, std::string const &pText, AGFont pFont, bool pHardEnd);
    virtual ~SwigDirector_AGEditLine();
    virtual void draw(AGPainter &p, AGVector2 const &pPoint, AGRect2 const &pClip);
    virtual void drawCursor(AGPainter &p, int cx, AGVector2 const &pPoint, AGRect2 const &pClip, AGColor const &c);
};


class SwigDirector_AGEdit : public AGEdit, public Swig::Director {

public:
    SwigDirector_AGEdit(VALUE self, AGWidget *pParent, AGRect2 const &pRect);
    virtual void useTextures();
    virtual bool eventGotFocus();
    virtual bool eventLostFocus();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void prepareDraw();
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual bool canFocus() const;
    virtual ~SwigDirector_AGEdit();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual void drawBackground(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGPaintTarget : public AGPaintTarget, public Swig::Director {

public:
    SwigDirector_AGPaintTarget(VALUE self);
    virtual void fillRects(std::vector<std::pair<AGRect2,AGVector4 > > const &pr);
    virtual AGRect2 getRect() const;
    virtual ~SwigDirector_AGPaintTarget();
    virtual void drawLine(AGVector2 const &p0, AGVector2 const &p1, AGColor const &c);
    virtual void blitTri(AGTexture const &pSource, AGTriangle2 const &pSrc, AGTriangle2 const &pDest);
    virtual void fillRect(AGRect2 const &pr, AGColor const &c);
    virtual void putPixel(int x, int y, AGColor const &c);
    virtual AGColor getPixel(int x, int y) const;
    virtual void blit(AGTexture const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc, AGColor const &pColor);
    virtual void blit(AGTexture const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc);
    virtual void blit(AGSurface const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc);
    virtual void beginPaint();
    virtual void endPaint();
};


class SwigDirector_AGDecryptor : public AGDecryptor, public Swig::Director {

public:
    SwigDirector_AGDecryptor(VALUE self);
    virtual ~SwigDirector_AGDecryptor();
    virtual std::string decrypt(std::string const &s, std::string const &n);
};


class SwigDirector_AGSurface : public AGSurface, public Swig::Director {

public:
    SwigDirector_AGSurface(VALUE self);
    SwigDirector_AGSurface(VALUE self, int w, int h);
    SwigDirector_AGSurface(VALUE self, AGSurface const &p);
    virtual void endPaint();
    virtual void beginPaint();
    virtual void drawLine(AGVector2 const &p0, AGVector2 const &p1, AGColor const &c);
    virtual ~SwigDirector_AGSurface();
    virtual AGRect2 getRect() const;
    virtual AGColor getPixel(int x, int y) const;
    virtual void fillRects(std::vector<std::pair<AGRect2,AGVector4 > > const &pr);
    virtual void blit(AGSurface const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc, AGColor const &pColor);
    virtual void blit(AGSurface const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc);
    virtual void blit(AGTexture const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc);
    virtual void blit(AGTexture const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc, AGColor const &pColor);
    virtual void fillRect(AGRect2 const &pr, AGColor const &c);
    virtual void putPixel(int x, int y, AGColor const &c);
    virtual void blitTri(AGTexture const &pSource, AGTriangle2 const &pSrc, AGTriangle2 const &pDest);
};


class SwigDirector_AGTexture : public AGTexture, public Swig::Director {

public:
    SwigDirector_AGTexture(VALUE self);
    SwigDirector_AGTexture(VALUE self, AGSurface const &pSurface, bool p3d = false);
    SwigDirector_AGTexture(VALUE self, AGTexture const &t);
    SwigDirector_AGTexture(VALUE self, int W, int H);
    virtual void endPaint();
    virtual void beginPaint();
    virtual void drawLine(AGVector2 const &p0, AGVector2 const &p1, AGColor const &c);
    virtual ~SwigDirector_AGTexture();
    virtual void drawGradientAlpha(AGRect2 const &rect, AGColor const &ul, AGColor const &ur, AGColor const &dl, AGColor const &dr);
    virtual AGColor getPixel(int x, int y) const;
    virtual AGRect2 getRect() const;
    virtual void drawGradient(AGRect2 const &rect, AGColor const &ul, AGColor const &ur, AGColor const &dl, AGColor const &dr);
    virtual void fillRects(std::vector<std::pair<AGRect2,AGVector4 > > const &pr);
    virtual void blit(AGTexture const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc, AGColor const &pColor);
    virtual void blit(AGTexture const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc);
    virtual void blit(AGSurface const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc);
    virtual void fillRect(AGRect2 const &pRect, AGColor const &c);
    virtual void putPixel(int x, int y, AGColor const &c);
    virtual void blitTri(AGTexture const &pSource, AGTriangle2 const &pSrc, AGTriangle2 const &pDest);
};


class SwigDirector_AGImage : public AGImage, public Swig::Director {

public:
    SwigDirector_AGImage(VALUE self, AGWidget *pParent, AGRect2 const &r, AGSurface pSurface, bool pTile, AGRect2 const &pRect = AGRect2(0,0,0,0));
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGImage();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGLayoutCreator : public AGLayoutCreator, public Swig::Director {

public:
    SwigDirector_AGLayoutCreator(VALUE self, std::string const &pName);
    virtual ~SwigDirector_AGLayoutCreator();
    virtual AGWidget *create(AGWidget *pParent, AGRect2 const &pRect, xmlpp::Node const &pNode);
};


class SwigDirector_AGListBox : public AGListBox, public Swig::Director {

public:
    SwigDirector_AGListBox(VALUE self, AGWidget *pParent, AGRect2 const &pRect);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGListBox();
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGMain : public AGMain, public Swig::Director {

public:
    SwigDirector_AGMain(VALUE self, int w, int h, int d, bool fs, bool gl);
    virtual ~SwigDirector_AGMain();
};


class SwigDirector_AGMenuItem : public AGMenuItem, public Swig::Director {

public:
    SwigDirector_AGMenuItem(VALUE self, AGWidget *pParent, std::string const &pText);
    virtual bool eventMouseEnter();
    virtual ~SwigDirector_AGMenuItem();
    virtual bool eventMouseLeave();
    virtual void eventSelect();
    virtual void eventUnselect();
    virtual bool eventMouseClick(AGEvent *m);
};


class SwigDirector_AGSubMenu : public AGSubMenu, public Swig::Director {

public:
    SwigDirector_AGSubMenu(VALUE self, AGWidget *pParent, std::string const &ptext);
    virtual bool eventMouseEnter();
    virtual ~SwigDirector_AGSubMenu();
    virtual bool eventMouseLeave();
    virtual void eventSelect();
    virtual void eventUnselect();
    virtual bool eventMouseClick(AGEvent *m);
};


class SwigDirector_AGSound : public AGSound, public Swig::Director {

public:
    SwigDirector_AGSound(VALUE self);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGSound();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGRadioGroup : public AGRadioGroup, public Swig::Director {

public:
    SwigDirector_AGRadioGroup(VALUE self, AGWidget *pParent, AGRect2 const &pr);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual void eventChange(std::string const &p);
    virtual ~SwigDirector_AGRadioGroup();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGRadio : public AGRadio, public Swig::Director {

public:
    SwigDirector_AGRadio(VALUE self, AGWidget *pParent, AGRect2 pRect);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual void setChecked(bool pChecked);
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void setWidth(float w);
    virtual void setHeight(float w);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual std::string getCaption() const;
    virtual bool canFocus() const;
    virtual ~SwigDirector_AGRadio();
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual void clear();
    virtual bool eventMouseEnter();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventHide();
    virtual bool eventMouseLeave();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGScreen : public AGScreen, public Swig::Director {

public:
    SwigDirector_AGScreen(VALUE self);
    virtual void endPaint();
    virtual void beginPaint();
    virtual void drawLine(AGVector2 const &p0, AGVector2 const &p1, AGColor const &c);
    virtual ~SwigDirector_AGScreen();
    virtual AGColor getPixel(int x, int y) const;
    virtual AGRect2 getRect() const;
    virtual size_t getWidth() const;
    virtual size_t getHeight() const;
    virtual void fillRects(std::vector<std::pair<AGRect2,AGVector4 > > const &pr);
    virtual void begin();
    virtual void blit(AGSurface const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc);
    virtual void blit(AGTexture const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc);
    virtual void blit(AGTexture const &pSource, AGRect2 const &pDest, AGRect2 const &pSrc, AGColor const &pColor);
    virtual void putPixel(int x, int y, AGColor const &c);
    virtual void fillRect(AGRect2 const &pr, AGColor const &c);
    virtual void flip();
    virtual void blitTri(AGTexture const &pSource, AGTriangle2 const &pSrc, AGTriangle2 const &pDest);
};


class SwigDirector_AGTable : public AGTable, public Swig::Director {

public:
    SwigDirector_AGTable(VALUE self, AGWidget *pWidget, AGRect2 const &pRect);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void setWidth(float w);
    virtual void setHeight(float w);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_AGTable();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_AGTheme : public AGTheme, public Swig::Director {

public:
    SwigDirector_AGTheme(VALUE self);
    virtual ~SwigDirector_AGTheme();
};


class SwigDirector_AGWindow : public AGWindow, public Swig::Director {

public:
    SwigDirector_AGWindow(VALUE self, AGWidget *pWidget, AGRect2 const &pRect, std::string const &pTitle = "", std::string const &pTheme = "");
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void prepareDraw();
    virtual void setWidth(float w);
    virtual void setHeight(float w);
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual AGRect2 getClientRect() const;
    virtual ~SwigDirector_AGWindow();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void addChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_SceneNode : public SceneNode, public Swig::Director {

public:
    SwigDirector_SceneNode(VALUE self, Scene *s, AGVector4 const &pPos, AGBox3 const &pBox);
    virtual void setPos(AGVector3 const &pPos);
    virtual bool transparent();
    virtual void clear();
    virtual void setRotation(float r);
    virtual void advance(float time);
    virtual void sort(AGVector4 const &pCamera);
    virtual void drawPick();
    virtual void resetScene();
    virtual ~SwigDirector_SceneNode();
    virtual size_t getTriangles() const;
    virtual AGVector4 lineHit(AGLine3 const &pLine) const;
    virtual void draw();
    virtual void drawShadow();
    virtual void drawDepth();
};


class SwigDirector_AnimMesh : public AnimMesh, public Swig::Director {

public:
    SwigDirector_AnimMesh(VALUE self, Scene *pScene, AnimMeshData *data);
    virtual void setPos(AGVector3 const &p);
    virtual void mark();
    virtual bool transparent();
    virtual void clear();
    virtual void setRotation(float r);
    virtual void advance(float time);
    virtual void sort(AGVector4 const &pCamera);
    virtual void drawPick();
    virtual void resetScene();
    virtual ~SwigDirector_AnimMesh();
    virtual size_t getTriangles() const;
    virtual AGVector4 lineHit(AGLine3 const &pLine) const;
    virtual void drawShadow();
    virtual void draw();
    virtual void drawDepth();
};


class SwigDirector_AnimMeshData : public AnimMeshData, public Swig::Director {

public:
    SwigDirector_AnimMeshData(VALUE self, std::string const &xmlfile);
    virtual ~SwigDirector_AnimMeshData();
};


class SwigDirector_GLApp : public GLApp, public Swig::Director {

public:
    SwigDirector_GLApp(VALUE self, int w, int h);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventActive(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool signal(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual void mark();
    virtual bool eventFrameEnd(float pTime);
    virtual bool eventFrame(float t);
    virtual void eventChangedRes();
    virtual void eventClick(Scene::PickResult const &pNodes, int button);
    virtual void eventHover(Scene::PickResult const &pNodes, int button);
    virtual ~SwigDirector_GLApp();
    virtual bool eventIdle();
    virtual void tryQuit();
    virtual Uint8 getButtonState() const;
    virtual AGVector2 getMousePosition() const;
    virtual void prepareDraw();
    virtual void draw();
    virtual void setCamera(AGVector2 const &p);
};


class SwigDirector_BinaryIn : public BinaryIn, public Swig::Director {

public:
    SwigDirector_BinaryIn(VALUE self);
    virtual char read();
    virtual ~SwigDirector_BinaryIn();
    virtual bool eof();
};


class SwigDirector_BinaryOut : public BinaryOut, public Swig::Director {

public:
    SwigDirector_BinaryOut(VALUE self);
    virtual ~SwigDirector_BinaryOut();
    virtual void write(char c);
};


class SwigDirector_BinaryFileIn : public BinaryFileIn, public Swig::Director {

public:
    SwigDirector_BinaryFileIn(VALUE self, std::string const &pName);
    virtual char read();
    virtual ~SwigDirector_BinaryFileIn();
    virtual bool eof();
};


class SwigDirector_BinaryFileOut : public BinaryFileOut, public Swig::Director {

public:
    SwigDirector_BinaryFileOut(VALUE self, std::string const &pName);
    virtual ~SwigDirector_BinaryFileOut();
    virtual void write(char c);
};


class SwigDirector_BinaryStringIn : public BinaryStringIn, public Swig::Director {

public:
    SwigDirector_BinaryStringIn(VALUE self, std::string const &pText);
    virtual char read();
    virtual ~SwigDirector_BinaryStringIn();
    virtual bool eof();
};


class SwigDirector_BinaryStringOut : public BinaryStringOut, public Swig::Director {

public:
    SwigDirector_BinaryStringOut(VALUE self);
    virtual ~SwigDirector_BinaryStringOut();
    virtual void write(char c);
};


class SwigDirector_AntEntity : public AntEntity, public Swig::Director {

public:
    SwigDirector_AntEntity(VALUE self);
    SwigDirector_AntEntity(VALUE self, AGVector3 const &p);
    SwigDirector_AntEntity(VALUE self, AGVector2 const &p);
    virtual void mark();
    virtual void animationEvent(std::string const &pName);
    virtual void clear();
    virtual void newRestJob(float pTime);
    virtual void move(float pTime);
    virtual void eventNoJob();
    virtual void delJob();
    virtual void eventGotNewJob();
    virtual void newFetchJob(int p, AntEntity *pTarget, std::string const &pWhat);
    virtual void newFetchJob(int p, AGVector2 &pTarget, std::string const &pWhat);
    virtual ~SwigDirector_AntEntity();
    virtual void newMoveJob(int p, AGVector2 const &pTarget, int pnear = 0);
    virtual std::string xmlName() const;
    virtual void resourceChanged();
    virtual void eventJobFinished();
    virtual void eventDefeated();
    virtual void eventDie();
    virtual void loadXML(xmlpp::Node const &node);
    virtual void saveXML(xmlpp::Node &node) const;
    virtual void newFightJob(int p, AntEntity *target);
    virtual void eventGotFight(AntEntity *pOther);
    virtual void eventHaveDefeated(AntEntity *e);
    virtual void setPos(AGVector2 const &p);
};


class SwigDirector_AntShaderProgram : public AntShaderProgram, public Swig::Director {

public:
    SwigDirector_AntShaderProgram(VALUE self, std::string const &pVertexFile, std::string const &pFragFile);
    virtual void doUpdate(float time);
    virtual ~SwigDirector_AntShaderProgram();
    virtual void enable();
    virtual void disable();
};


class SwigDirector_AntShadowShader : public AntShadowShader, public Swig::Director {

public:
    SwigDirector_AntShadowShader(VALUE self, std::string const &pVertexFile, std::string const &pFragFile);
    virtual void doUpdate(float time);
    virtual ~SwigDirector_AntShadowShader();
    virtual void enable();
    virtual void disable();
};


class SwigDirector_AntWaterShader : public AntWaterShader, public Swig::Director {

public:
    SwigDirector_AntWaterShader(VALUE self);
    virtual void doUpdate(float time);
    virtual ~SwigDirector_AntWaterShader();
    virtual void enable();
    virtual void disable();
};


class SwigDirector_HeightMap : public HeightMap, public Swig::Director {

public:
    SwigDirector_HeightMap(VALUE self, Scene *pScene, int w, int h);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventActive(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool signal(AGEvent *m);
    virtual ~SwigDirector_HeightMap();
    virtual Uint8 getButtonState() const;
    virtual AGVector2 getMousePosition() const;
    virtual void newMap(int w, int h);
    virtual void mapChanged();
    virtual void saveXML(Node &node) const;
    virtual void loadXML(Node const &node);
};


class SwigDirector_AntMap : public AntMap, public Swig::Director {

public:
    SwigDirector_AntMap(VALUE self, Scene *pScene, int w, int h);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventActive(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool signal(AGEvent *m);
    virtual void loadMap(std::string const &pFilename);
    virtual void mark();
    virtual void clear();
    virtual ~SwigDirector_AntMap();
    virtual Uint8 getButtonState() const;
    virtual AGVector2 getMousePosition() const;
    virtual void newMap(int w, int h);
    virtual void mapChanged();
    virtual AntEntity *loadEntity(xmlpp::Node const &node);
    virtual void insertEntity(AntEntity *e);
    virtual void removeEntity(AntEntity *p);
    virtual void saveXML(xmlpp::Node &node) const;
    virtual void loadXML(xmlpp::Node const &node);
};


class SwigDirector_MeshData : public MeshData, public Swig::Director {

public:
    SwigDirector_MeshData(VALUE self, std::string const &filename, float zoom, std::string const &pTexture = "", bool pShadow = true);
    SwigDirector_MeshData(VALUE self, VertexArray const &va, std::string const &pTexture, bool pShadow = true);
    virtual size_t getTriangles() const;
    virtual ~SwigDirector_MeshData();
    virtual AGVector4 lineHit(AGLine3 const &pLine) const;
    virtual bool transparent();
};


class SwigDirector_Mesh : public Mesh, public Swig::Director {

public:
    SwigDirector_Mesh(VALUE self, Scene *pScene);
    SwigDirector_Mesh(VALUE self, Scene *pScene, MeshData &data, AGVector4 const &pPos, float pRot);
    virtual void setPos(AGVector3 const &pPos);
    virtual void mark();
    virtual void clear();
    virtual bool transparent();
    virtual void advance(float time);
    virtual void setRotation(float r);
    virtual void sort(AGVector4 const &pCamera);
    virtual void drawPick();
    virtual void resetScene();
    virtual ~SwigDirector_Mesh();
    virtual size_t getTriangles() const;
    virtual void draw();
    virtual void drawDepth();
    virtual void drawShadow();
    virtual AGVector4 lineHit(AGLine3 const &pLine) const;
};


class SwigDirector_MiniMap : public MiniMap, public Swig::Director {

public:
    SwigDirector_MiniMap(VALUE self, AGWidget *p, AGRect2 const &r, AntMap *pMap);
    virtual bool eventLostFocus();
    virtual bool eventGotFocus();
    virtual void useTextures();
    virtual bool eventShow();
    virtual void setLeft(float x);
    virtual void setTop(float y);
    virtual void setHeight(float w);
    virtual void setWidth(float w);
    virtual void prepareDraw();
    virtual bool eventDragBy(AGEvent *event, AGVector2 const &pDiff);
    virtual void initHandlers();
    virtual float minHeight() const;
    virtual float minWidth() const;
    virtual bool canFocus() const;
    virtual AGRect2 getClientRect() const;
    virtual AGVector2 getMousePosition() const;
    virtual Uint8 getButtonState() const;
    virtual bool redraw() const;
    virtual ~SwigDirector_MiniMap();
    virtual bool eventMouseButtonUp(AGEvent *m);
    virtual bool eventMouseButtonDown(AGEvent *m);
    virtual bool eventMouseMotion(AGEvent *m);
    virtual bool signal(AGEvent *m);
    virtual bool acceptEvent(SDL_Event const *pEvent);
    virtual bool eventActive(AGEvent *m);
    virtual bool eventKeyDown(AGEvent *m);
    virtual bool eventKeyUp(AGEvent *m);
    virtual bool eventQuit(AGEvent *m);
    virtual bool eventQuitModal(AGEvent *m);
    virtual bool eventSysWM(AGEvent *m);
    virtual bool eventResize(AGEvent *m);
    virtual bool eventMouseClick(AGEvent *m);
    virtual bool eventMouseEnter();
    virtual void clear();
    virtual void drawAll(AGPainter &p);
    virtual void drawAfter(AGPainter &p);
    virtual void draw(AGPainter &p);
    virtual bool eventMouseLeave();
    virtual bool eventHide();
    virtual void addChild(AGWidget *w);
    virtual void addChildBack(AGWidget *w);
    virtual void removeChild(AGWidget *w);
    virtual void mark();
};


class SwigDirector_NewDecal : public NewDecal, public Swig::Director {

public:
    SwigDirector_NewDecal(VALUE self, Scene *pScene, AGVector2 pos, float size, HeightMap *pMap, std::string const &pTexture);
    virtual void setPos(AGVector3 const &pPos);
    virtual bool transparent();
    virtual void clear();
    virtual void setRotation(float r);
    virtual void advance(float time);
    virtual void sort(AGVector4 const &pCamera);
    virtual void drawPick();
    virtual void resetScene();
    virtual ~SwigDirector_NewDecal();
    virtual size_t getTriangles() const;
    virtual void mapChanged();
    virtual AGVector4 lineHit(AGLine3 const &pLine) const;
    virtual void drawShadow();
    virtual void drawDepth();
    virtual void draw();
};


class SwigDirector_Scene : public Scene, public Swig::Director {

public:
    SwigDirector_Scene(VALUE self, int w, int h);
    virtual void clear();
    virtual ~SwigDirector_Scene();
    virtual void mark();
};


class SwigDirector_Smoke : public Smoke, public Swig::Director {

public:
    SwigDirector_Smoke(VALUE self, Scene *pScene, float f);
    virtual void setPos(AGVector3 const &pPos);
    virtual void clear();
    virtual bool transparent();
    virtual void setRotation(float r);
    virtual void advance(float time);
    virtual void sort(AGVector4 const &pCamera);
    virtual void drawPick();
    virtual void resetScene();
    virtual ~SwigDirector_Smoke();
    virtual size_t getTriangles() const;
    virtual AGVector4 lineHit(AGLine3 const &pLine) const;
    virtual void drawShadow();
    virtual void drawDepth();
    virtual void draw();
};


class SwigDirector_TerrainPieceVA : public TerrainPieceVA, public Swig::Director {

public:
    SwigDirector_TerrainPieceVA(VALUE self, Scene *pScene, Terrain *t, HeightMap &map, int x, int y, int w, int h, AGVector4 const &pPos, int scale);
    virtual void setPos(AGVector3 const &pPos);
    virtual bool transparent();
    virtual void clear();
    virtual void setRotation(float r);
    virtual void advance(float time);
    virtual void sort(AGVector4 const &pCamera);
    virtual void drawPick();
    virtual void resetScene();
    virtual ~SwigDirector_TerrainPieceVA();
    virtual size_t getTriangles() const;
    virtual void mapChanged();
    virtual void draw();
    virtual void drawShadow();
    virtual void drawDepth();
    virtual AGVector4 lineHit(AGLine3 const &pLine) const;
};


class SwigDirector_Terrain : public Terrain, public Swig::Director {

public:
    SwigDirector_Terrain(VALUE self, Scene *pScene, HeightMap &map);
    virtual void mapChanged();
    virtual ~SwigDirector_Terrain();
    virtual void mapChangedComplete();
    virtual bool slotMapChanged(AGEvent *e);
    virtual bool slotMapChangedComplete(AGEvent *e);
};


class SwigDirector_VertexArray : public VertexArray, public Swig::Director {

public:
    SwigDirector_VertexArray(VALUE self);
    virtual ~SwigDirector_VertexArray();
    virtual void draw();
};


class SwigDirector_VertexArrayShader : public VertexArrayShader, public Swig::Director {

public:
    SwigDirector_VertexArrayShader(VALUE self, AntShaderProgram *_p);
    virtual ~SwigDirector_VertexArrayShader();
    virtual void draw();
};


class SwigDirector_WaterPiece : public WaterPiece, public Swig::Director {

public:
    SwigDirector_WaterPiece(VALUE self, Scene *pScene, HeightMap &map, int x, int y, int w, int h, AGVector4 const &pos);
    virtual void setPos(AGVector3 const &pPos);
    virtual void clear();
    virtual bool transparent();
    virtual void setRotation(float r);
    virtual void advance(float t);
    virtual void sort(AGVector4 const &pCamera);
    virtual void drawPick();
    virtual void resetScene();
    virtual ~SwigDirector_WaterPiece();
    virtual size_t getTriangles() const;
    virtual void mapChanged();
    virtual AGVector4 lineHit(AGLine3 const &pLine) const;
    virtual void drawShadow();
    virtual void drawDepth();
    virtual void draw();
};


#endif
