.TH "gui/src/ag_border.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_border.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_border.h'\fP
.br
\fC#include 'ag_painter.h'\fP
.br
\fC#include 'ag_theme.h'\fP
.br
\fC#include 'ag_texturecache.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
