.TH "gui/src/ag_color.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_color.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_color.h'\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_tools.h'\fP
.br
\fC#include <sstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBAGColor\fP &c1, const \fBAGColor\fP &c2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAGColor\fP &c1, const \fBAGColor\fP &c2)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBAGColor\fP &c1, const \fBAGColor\fP &c2)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAGColor\fP &c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool operator!= (const \fBAGColor\fP & c1, const \fBAGColor\fP & c2)"
.PP
.SS "bool operator< (const \fBAGColor\fP & c1, const \fBAGColor\fP & c2)"
.PP
.SS "std::ostream& operator<< (std::ostream & o, const \fBAGColor\fP & c)"
.PP
.SS "bool operator== (const \fBAGColor\fP & c1, const \fBAGColor\fP & c2)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
