.TH "gui/src/ag_colorbutton.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_colorbutton.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_widget.h'\fP
.br
\fC#include 'ag_color.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGColorButton\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGColorButton\fP & \fBtoAGColorButton\fP (\fBAGWidget\fP &pWidget)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGColorButton\fP& toAGColorButton (\fBAGWidget\fP & pWidget)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
