.TH "gui/src/ag_edit.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_edit.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_edit.h'\fP
.br
\fC#include 'ag_fontengine.h'\fP
.br
\fC#include 'ag_theme.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_menu.h'\fP
.br
\fC#include 'ag_sgeexport.h'\fP
.br
\fC#include 'ag_glsurface.h'\fP
.br
\fC#include 'ag_tools.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSMALL_CHUNKS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGEdit\fP & \fBtoAGEdit\fP (\fBAGWidget\fP &w)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define SMALL_CHUNKS"
.PP
.SH "Function Documentation"
.PP 
.SS "\fBAGEdit\fP& toAGEdit (\fBAGWidget\fP & w)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
