.TH "gui/src/ag_glpainter.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_glpainter.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAGGLPainter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAGGLPainter::blit\fP (const \fBAGTexture\fP &pSource, const \fBAGRect2\fP &pRect, const \fBAGRect2\fP &pSrc, const \fBAGColor\fP &pColor)"
.br
.ti -1c
.RI "void \fBAGGLPainter::blit\fP (const \fBAGTexture\fP &pSource, const std::vector< std::pair< \fBAGRect2\fP, \fBAGRect2\fP > > &pSrcDestRects, const \fBAGColor\fP &pColor)"
.br
.ti -1c
.RI "void \fBAGGLPainter::tile\fP (const \fBAGTexture\fP &pSource, const \fBAGRect2\fP &pTarget, const \fBAGColor\fP &pColor)"
.br
.ti -1c
.RI "void \fBAGGLPainter::fillRect\fP (const \fBAGRect2\fP &pRect, const \fBAGColor\fP &c)"
.br
.ti -1c
.RI "void \fBAGGLPainter::fillRects\fP (const std::vector< std::pair< \fBAGRect2\fP, \fBAGVector4\fP > > &pRects)"
.br
.ti -1c
.RI "void \fBAGGLPainter::drawBorder\fP (const \fBAGRect2\fP &rect, int W, const \fBAGColor\fP &c1, const \fBAGColor\fP &c2)"
.br
.ti -1c
.RI "void \fBAGGLPainter::drawGradientAlpha\fP (const \fBAGRect2\fP &pRect, const \fBAGColor\fP &ul, const \fBAGColor\fP &ur, const \fBAGColor\fP &dl, const \fBAGColor\fP &dr)"
.br
.ti -1c
.RI "void \fBAGGLPainter::drawLine\fP (const \fBAGVector2\fP &p0, const \fBAGVector2\fP &p1, const \fBAGColor\fP &c, float pWidth)"
.br
.ti -1c
.RI "void \fBAGGLPainter::blitTri\fP (const \fBAGTexture\fP &pSource, const \fBAGTriangle2\fP &pSrc, const \fBAGTriangle2\fP &pDest)"
.br
.ti -1c
.RI "void \fBAGGLPainter::putPixel\fP (int x, int y, const \fBAGColor\fP &pc)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
