.TH "gui/src/ag_kill.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_kill.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGInstanceBase\fP"
.br
.ti -1c
.RI "class \fBAGInstance< T >\fP"
.br
.ti -1c
.RI "class \fBContentCompare\fP"
.br
.ti -1c
.RI "class \fBAGInstanceKiller\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBREGISTER_SINGLETON\fP(s)   getInstanceKiller()->reg(createKiller(s));"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T> \fBAGInstanceBase\fP * \fBcreateKiller\fP (T *t)"
.br
.ti -1c
.RI "\fBAGInstanceKiller\fP * \fBgetInstanceKiller\fP ()"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define REGISTER_SINGLETON(s)   getInstanceKiller()->reg(createKiller(s));"
.PP
.SH "Function Documentation"
.PP 
.SS "template<class T> \fBAGInstanceBase\fP* createKiller (T * t)"
.PP
.SS "\fBAGInstanceKiller\fP* getInstanceKiller ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
