.TH "gui/src/ag_layout.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_layout.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_layout.h'\fP
.br
\fC#include 'ag_xml.h'\fP
.br
\fC#include 'ag_tools.h'\fP
.br
\fC#include 'ag_theme.h'\fP
.br
\fC#include 'ag_listbox.h'\fP
.br
\fC#include 'ag_combo.h'\fP
.br
\fC#include 'ag_image.h'\fP
.br
\fC#include 'ag_frame.h'\fP
.br
\fC#include 'ag_button.h'\fP
.br
\fC#include 'ag_edit.h'\fP
.br
\fC#include 'ag_window.h'\fP
.br
\fC#include 'ag_text.h'\fP
.br
\fC#include 'ag_main.h'\fP
.br
\fC#include 'ag_layoutfactory.h'\fP
.br
\fC#include 'ag_local.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGButtonLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGTableLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGWindowLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGTextLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGEditLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGListBoxLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGComboBoxLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGLayoutLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGImageLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGFrameLayoutCreator\fP"
.br
.ti -1c
.RI "class \fBAGCellLayoutCreator\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGLayout\fP * \fBgetLayout\fP (\fBAGWidget\fP *pWidget)"
.br
.ti -1c
.RI "\fBAGWidget\fP * \fBparseNode\fP (\fBAGWidget\fP *pParent, const \fBNode\fP &pNode)"
.br
.ti -1c
.RI "\fBAGRect2\fP \fBgetLayoutGeometry\fP (\fBAGWidget\fP *pParent, const \fBNode\fP &pNode)"
.br
.ti -1c
.RI "void \fBparseChildren\fP (\fBAGWidget\fP *pParent, const \fBNode\fP &pNode)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (Table)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (Button)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (Window)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (Text)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (Edit)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (ListBox)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (ComboBox)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (Layout)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (Image)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (Frame)"
.br
.ti -1c
.RI "\fBIMPLEMENT_COMPONENT_FACTORY\fP (Cell)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGLayout\fP* getLayout (\fBAGWidget\fP * pWidget)"
.PP
.SS "\fBAGRect2\fP getLayoutGeometry (\fBAGWidget\fP * pParent, const \fBNode\fP & pNode)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (Cell)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (Frame)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (Image)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (Layout)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (ComboBox)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (ListBox)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (Edit)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (Text)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (Window)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (Button)"
.PP
.SS "IMPLEMENT_COMPONENT_FACTORY (Table)"
.PP
.SS "void parseChildren (\fBAGWidget\fP * pParent, const \fBNode\fP & pNode)"
.PP
.SS "\fBAGWidget\fP* parseNode (\fBAGWidget\fP * pParent, const \fBNode\fP & pNode)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
