.TH "gui/src/ag_listbox.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_listbox.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'ag_widget.h'\fP
.br
\fC#include 'ag_background.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAGListBoxItem\fP"
.br
.ti -1c
.RI "class \fBAGListBox\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGListBox\fP & \fBtoAGListBox\fP (\fBAGWidget\fP &w)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGListBox\fP& toAGListBox (\fBAGWidget\fP & w)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
