.TH "gui/src/ag_main.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_main.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'ag_base.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_tools.h'\fP
.br
\fC#include 'ag_main.h'\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_texture.h'\fP
.br
\fC#include 'ag_sdlsurface.h'\fP
.br
\fC#include 'ag_glsurface.h'\fP
.br
\fC#include 'ag_fs.h'\fP
.br
\fC#include 'ag_mixer.h'\fP
.br
\fC#include 'ag_surfacemanager.h'\fP
.br
\fC#include 'ag_fontengine.h'\fP
.br
\fC#include 'privates.h'\fP
.br
\fC#include <SDL.h>\fP
.br
\fC#include 'SDL_image.h'\fP
.br
\fC#include <SDL_mixer.h>\fP
.br
\fC#include <ruby.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnewInstanceKiller\fP ()"
.br
.ti -1c
.RI "void \fBdeleteInstanceKiller\fP ()"
.br
.ti -1c
.RI "void \fBinitSoundEngine\fP ()"
.br
.ti -1c
.RI "bool \fBhasQuit\fP ()"
.br
.ti -1c
.RI "bool \fBglMode\fP ()"
.br
.ti -1c
.RI "std::string \fBmyHash\fP (const std::string &p)"
.br
.ti -1c
.RI "\fBAGMain\fP * \fBgetMain\fP ()"
.br
.ti -1c
.RI "void \fBsetAppName\fP (const std::string &pName)"
.br
.ti -1c
.RI "std::string \fBgetAppName\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBlastWidth\fP = 0"
.br
.ti -1c
.RI "int \fBlastHeight\fP = 0"
.br
.ti -1c
.RI "int \fBlastVWidth\fP = 0"
.br
.ti -1c
.RI "int \fBlastVHeight\fP = 0"
.br
.ti -1c
.RI "int \fBlastDepth\fP = 0"
.br
.ti -1c
.RI "bool \fBfullScreen\fP = false"
.br
.ti -1c
.RI "bool \fBlastGL\fP = false"
.br
.ti -1c
.RI "\fBAGMain\fP * \fBmAGMain\fP = 0"
.br
.ti -1c
.RI "bool \fBquited\fP = false"
.br
.ti -1c
.RI "std::map< std::pair< \fBAGFont\fP, std::string >, \fBAGTexture\fP > \fBfontCache\fP"
.br
.ti -1c
.RI "std::map< std::string, Mix_Chunk * > \fBmSounds\fP"
.br
.ti -1c
.RI "std::string \fBgAppName\fP = 'Antargis'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void deleteInstanceKiller ()"
.PP
.SS "std::string getAppName ()"
.PP
.SS "\fBAGMain\fP* getMain ()"
.PP
.SS "bool glMode ()"
.PP
.SS "bool hasQuit ()"
.PP
.SS "void initSoundEngine ()"
.PP
.SS "std::string myHash (const std::string & p)"
.PP
.SS "void newInstanceKiller ()"
.PP
.SS "void setAppName (const std::string & pName)"
.PP
.SH "Variable Documentation"
.PP 
.SS "std::map<std::pair<\fBAGFont\fP,std::string>,\fBAGTexture\fP> \fBfontCache\fP"
.PP
.SS "bool \fBfullScreen\fP = false"
.PP
.SS "std::string \fBgAppName\fP = 'Antargis'"
.PP
.SS "int \fBlastDepth\fP = 0"
.PP
.SS "bool \fBlastGL\fP = false"
.PP
.SS "int \fBlastHeight\fP = 0"
.PP
.SS "int \fBlastVHeight\fP = 0"
.PP
.SS "int \fBlastVWidth\fP = 0"
.PP
.SS "int \fBlastWidth\fP = 0"
.PP
.SS "\fBAGMain\fP* \fBmAGMain\fP = 0"
.PP
.SS "std::map<std::string,Mix_Chunk*> \fBmSounds\fP"
.PP
.SS "bool \fBquited\fP = false"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
