.TH "gui/src/ag_mixer.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_mixer.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_mixer.h'\fP
.br
\fC#include 'ag_kill.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_mutex.h'\fP
.br
\fC#include 'ag_fs.h'\fP
.br
\fC#include 'ag_config.h'\fP
.br
\fC#include <SDL_mixer.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include <set>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUSE_RWOPS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmusicFinished\fP ()"
.br
.ti -1c
.RI "void \fBchannelDone\fP (int channel)"
.br
.ti -1c
.RI "int \fBgetFreeChannel\fP ()"
.br
.ti -1c
.RI "void \fBinitSoundEngine\fP ()"
.br
.ti -1c
.RI "void \fBcloseSoundEngine\fP ()"
.br
.ti -1c
.RI "\fBAGSound\fP * \fBgetSoundManager\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Mix_Music * \fBmMusic\fP = 0"
.br
.ti -1c
.RI "bool \fBmMusicFinished\fP = false"
.br
.ti -1c
.RI "bool \fBmMusicInited\fP = false"
.br
.ti -1c
.RI "bool \fBmNoSound\fP = false"
.br
.ti -1c
.RI "const int \fBcSoundChannels\fP = 16"
.br
.ti -1c
.RI "std::map< std::string, Mix_Chunk * > \fBmSounds\fP"
.br
.ti -1c
.RI "std::set< int > \fBmFreeChannels\fP"
.br
.ti -1c
.RI "\fBAGMutex\fP * \fBmSoundMutex\fP"
.br
.ti -1c
.RI "\fBAGSound\fP * \fBmSoundManager\fP = 0"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define USE_RWOPS"
.PP
.SH "Function Documentation"
.PP 
.SS "void channelDone (int channel)"
.PP
.SS "void closeSoundEngine ()"
.PP
.SS "int getFreeChannel ()"
.PP
.SS "\fBAGSound\fP* getSoundManager ()"
.PP
.SS "void initSoundEngine ()"
.PP
.SS "void musicFinished ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "const int \fBcSoundChannels\fP = 16"
.PP
.SS "std::set<int> \fBmFreeChannels\fP"
.PP
.SS "Mix_Music* \fBmMusic\fP = 0"
.PP
.SS "bool \fBmMusicFinished\fP = false"
.PP
.SS "bool \fBmMusicInited\fP = false"
.PP
.SS "bool \fBmNoSound\fP = false"
.PP
.SS "\fBAGSound\fP* \fBmSoundManager\fP = 0"
.PP
.SS "\fBAGMutex\fP* \fBmSoundMutex\fP"
.PP
.SS "std::map<std::string,Mix_Chunk*> \fBmSounds\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
