.TH "gui/src/ag_main.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_main.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'ag_rubyobj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGMain\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGMain\fP * \fBgetMain\fP ()"
.br
.ti -1c
.RI "bool \fBhasQuit\fP ()"
.br
.ti -1c
.RI "bool \fBglMode\fP ()"
.br
.ti -1c
.RI "void \fBsetAppName\fP (const std::string &pName)"
.br
.ti -1c
.RI "std::string \fBgetAppName\fP ()"
.br
.ti -1c
.RI "bool \fBvideoInited\fP ()"
.br
.ti -1c
.RI "std::string AGEXPORT \fBmyHash\fP (const std::string &p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string getAppName ()"
.PP
.SS "\fBAGMain\fP* getMain ()"
.PP
.SS "bool glMode ()"
.PP
.SS "bool hasQuit ()"
.PP
.SS "std::string AGEXPORT myHash (const std::string & p)"
.PP
.SS "void setAppName (const std::string & pName)"
.PP
.SS "bool videoInited ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
