.TH "gui/src/ag_png.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_png.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <png.h>\fP
.br
\fC#include <SDL.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <assert.h>\fP
.br
\fC#include <SDL_image.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBpng_write_data\fP (png_structp ctx, png_bytep area, png_size_t size)"
.br
.ti -1c
.RI "static void \fBpng_io_flush\fP (png_structp ctx)"
.br
.ti -1c
.RI "static int \fBpng_colortype_from_surface\fP (SDL_Surface *surface)"
.br
.ti -1c
.RI "static void \fBpng_user_warn\fP (png_structp ctx, png_const_charp str)"
.br
.ti -1c
.RI "static void \fBpng_user_error\fP (png_structp ctx, png_const_charp str)"
.br
.ti -1c
.RI "int \fBIMG_SavePNG_RW\fP (SDL_Surface *surface, SDL_RWops *src)"
.br
.ti -1c
.RI "std::string \fBtoPNG\fP (const SDL_Surface *s)"
.br
.ti -1c
.RI "SDL_Surface * \fBfromPNG\fP (std::string s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SDL_Surface* fromPNG (std::string s)"
.PP
.SS "int IMG_SavePNG_RW (SDL_Surface * surface, SDL_RWops * src)"
.PP
.SS "static int png_colortype_from_surface (SDL_Surface * surface)\fC [static]\fP"
.PP
.SS "static void png_io_flush (png_structp ctx)\fC [static]\fP"
.PP
.SS "static void png_user_error (png_structp ctx, png_const_charp str)\fC [static]\fP"
.PP
.SS "static void png_user_warn (png_structp ctx, png_const_charp str)\fC [static]\fP"
.PP
.SS "static void png_write_data (png_structp ctx, png_bytep area, png_size_t size)\fC [static]\fP"
.PP
.SS "std::string toPNG (const SDL_Surface * s)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
