.TH "gui/src/ag_png.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_png.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <SDL.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBtoPNG\fP (const SDL_Surface *s)"
.br
.ti -1c
.RI "SDL_Surface * \fBfromPNG\fP (std::string s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SDL_Surface* fromPNG (std::string s)"
.PP
.SS "std::string toPNG (const SDL_Surface * s)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
