.TH "gui/src/ag_rendercontext.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_rendercontext.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_rendercontext.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_texture.h'\fP
.br
\fC#include 'ag_surfacemanager.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSLOWCONTEXT\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAGRenderContext\fP \fBgCurrentContext\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define SLOWCONTEXT"
.PP
.SH "Variable Documentation"
.PP 
.SS "\fBAGRenderContext\fP \fBgCurrentContext\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
