.TH "gui/src/ag_serial.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_serial.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_fs.h>\fP
.br
\fC#include <SDL.h>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <ag_geometry.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSerialException\fP"
.br
.ti -1c
.RI "class \fBBinaryIn\fP"
.br
.ti -1c
.RI "class \fBBinaryOut\fP"
.br
.ti -1c
.RI "class \fBBinaryFileIn\fP"
.br
.ti -1c
.RI "class \fBBinaryFileOut\fP"
.br
.ti -1c
.RI "class \fBBinaryStringIn\fP"
.br
.ti -1c
.RI "class \fBBinaryStringOut\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBbinaryToHex\fP (const std::string &s)"
.br
.ti -1c
.RI "std::string \fBhexToBinary\fP (const std::string &s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string binaryToHex (const std::string & s)"
.PP
.SS "std::string hexToBinary (const std::string & s)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
