.TH "gui/src/ag_surface.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_surface.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_texture.h'\fP
.br
\fC#include 'ag_color.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_draw.h'\fP
.br
\fC#include 'privates.h'\fP
.br
\fC#include 'ag_sgeexport.h'\fP
.br
\fC#include 'ag_kill.h'\fP
.br
\fC#include 'ag_png.h'\fP
.br
\fC#include 'ag_glsurface.h'\fP
.br
\fC#include 'ag_surfacemanager.h'\fP
.br
\fC#include 'SDL_image.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <ag_fs.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbeginRender\fP ()"
.br
.ti -1c
.RI "void \fBendRender\fP ()"
.br
.ti -1c
.RI "bool \fBisRendering\fP ()"
.br
.ti -1c
.RI "void \fBAGFreeSurface\fP (SDL_Surface *s)"
.br
.ti -1c
.RI "\fBAGInternalSurface\fP * \fBAGCreate32BitSurface\fP (size_t width, size_t height)"
.br
.ti -1c
.RI "\fBAGDecryptor\fP * \fBtoDecryptor\fP (\fBAGPlugin\fP *p)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBgDRM\fP = false"
.br
.ti -1c
.RI "bool \fBgRendering\fP = false"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGInternalSurface\fP* AGCreate32BitSurface (size_t width, size_t height)"
.PP
.SS "void AGFreeSurface (SDL_Surface * s)"
.PP
.SS "void beginRender ()"
.PP
.SS "void endRender ()"
.PP
.SS "bool isRendering ()"
.PP
.SS "\fBAGDecryptor\fP* toDecryptor (\fBAGPlugin\fP * p)"
.PP
.SH "Variable Documentation"
.PP 
.SS "bool \fBgDRM\fP = false"
.PP
.SS "bool \fBgRendering\fP = false"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
