.TH "gui/src/ag_screenwidget.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_screenwidget.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_screen.h'\fP
.br
\fC#include 'ag_screenwidget.h'\fP
.br
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_theme.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
