.TH "gui/src/ag_texturecache.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_texturecache.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_texture.h'\fP
.br
\fC#include 'ag_texturecache.h'\fP
.br
\fC#include 'ag_png.h'\fP
.br
\fC#include 'ag_kill.h'\fP
.br
\fC#include 'ag_geometry.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGTextureCache\fP * \fBgetTextureCache\fP ()"
.br
.ti -1c
.RI "\fBAGSurface\fP \fBskipHalfTexture\fP (const \fBAGSurface\fP &s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAGTextureCache\fP * \fBmTextureCache\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGTextureCache\fP* getTextureCache ()"
.PP
.SS "\fBAGSurface\fP skipHalfTexture (const \fBAGSurface\fP & s)"
.PP
.SH "Variable Documentation"
.PP 
.SS "\fBAGTextureCache\fP* \fBmTextureCache\fP = 0"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
