.TH "gui/src/ag_texturecache.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_texturecache.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_surface.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include <ag_fs.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGTextureCache\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGTextureCache\fP * \fBgetTextureCache\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGTextureCache\fP* getTextureCache ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
