.TH "gui/src/ag_tools.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_tools.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_tools.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtoInt\fP (const std::string &s)"
.br
.ti -1c
.RI "long \fBtoLong\fP (const std::string &s)"
.br
.ti -1c
.RI "float \fBtoFloat\fP (const std::string &s)"
.br
.ti -1c
.RI "int \fBfromHex\fP (const std::string &s)"
.br
.ti -1c
.RI "std::string \fBtoHex\fP (int i)"
.br
.ti -1c
.RI "std::vector< std::string > \fBsplit\fP (const std::string &needle, const std::string &haystack)"
.br
.ti -1c
.RI "std::string \fBreplace\fP (const std::string &s, const std::string &a, const std::string &b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int fromHex (const std::string & s)"
.PP
.SS "std::string replace (const std::string & s, const std::string & a, const std::string & b)"
.PP
.SS "std::vector<std::string> split (const std::string & needle, const std::string & haystack)"
.PP
.SS "float toFloat (const std::string & s)"
.PP
.SS "std::string toHex (int i)"
.PP
.SS "int toInt (const std::string & s)"
.PP
.SS "long toLong (const std::string & s)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
