.TH "gui/src/ag_widget.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_widget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_geometry.h'\fP
.br
\fC#include 'ag_messageobject.h'\fP
.br
\fC#include <list>\fP
.br
\fC#include 'ag_painter.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGWidget\fP"
.br
.RI "\fIbase class for all widgets \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAGWidget\fP * \fBtoAGWidget\fP (\fBAGMessageObject\fP *o)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAGWidget\fP * \fBagNoParent\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAGWidget\fP* toAGWidget (\fBAGMessageObject\fP * o)"
.PP
.SH "Variable Documentation"
.PP 
.SS "\fBAGWidget\fP* \fBagNoParent\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
