.TH "gui/src/ag_xml.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/ag_xml.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_tools.h>\fP
.br
\fC#include <ag_utf8.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <ag_stringstream.h>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'ag_debug.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNode\fP"
.br
.ti -1c
.RI "class \fBDocument\fP"
.br
.ti -1c
.RI "class \fBParser\fP"
.br
.ti -1c
.RI "class \fBDomParser\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
