.TH "AGCaption" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGCaption \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_caption.h>\fP
.PP
Inherits \fBAGText\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGCaption\fP (\fBAGWidget\fP *pParent, const \fBAGRect2\fP &pRect, const \fBAGStringUtf8\fP &pText, const \fBAGFont\fP &pFont, const \fBAGBackground\fP &pBG)"
.br
.ti -1c
.RI "void \fBdraw\fP (\fBAGPainter\fP &p)"
.br
.ti -1c
.RI "void \fBsetBackground\fP (\fBAGBackground\fP pBG)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGCaption::AGCaption (\fBAGWidget\fP * pParent, const \fBAGRect2\fP & pRect, const \fBAGStringUtf8\fP & pText, const \fBAGFont\fP & pFont, const \fBAGBackground\fP & pBG)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGCaption::draw (\fBAGPainter\fP & p)\fC [virtual]\fP"
.PP
Reimplemented from \fBAGText\fP.
.SS "void AGCaption::setBackground (\fBAGBackground\fP pBG)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
