.TH "AGCharUtf8" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGCharUtf8 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_string_utf8.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGCharUtf8\fP (const char p)"
.br
.ti -1c
.RI "\fBAGCharUtf8\fP (const std::string &p)"
.br
.ti -1c
.RI "\fBAGCharUtf8\fP (const \fBAGCharUtf8\fP &p)"
.br
.ti -1c
.RI "\fBAGCharUtf8\fP (\fBAGStringUtf8\fP *ps, size_t ppos)"
.br
.ti -1c
.RI "\fBAGCharUtf8\fP & \fBoperator=\fP (const \fBAGCharUtf8\fP &c)"
.br
.ti -1c
.RI "\fBAGCharUtf8\fP & \fBoperator=\fP (const \fBAGStringUtf8\fP &c)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAGCharUtf8\fP &c) const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const char pChar) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBAGCharUtf8\fP &c) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const char pChar) const "
.br
.ti -1c
.RI "std::string \fBgetString\fP () const "
.br
.ti -1c
.RI "size_t \fBmemory\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGCharUtf8::AGCharUtf8 (const char p)\fC [explicit]\fP"
.PP
.SS "AGCharUtf8::AGCharUtf8 (const std::string & p)\fC [explicit]\fP"
.PP
.SS "AGCharUtf8::AGCharUtf8 (const \fBAGCharUtf8\fP & p)"
.PP
.SS "AGCharUtf8::AGCharUtf8 (\fBAGStringUtf8\fP * ps, size_t ppos)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "std::string AGCharUtf8::getString () const"
.PP
.SS "size_t AGCharUtf8::memory () const"
.PP
.SS "bool AGCharUtf8::operator!= (const char pChar) const"
.PP
.SS "bool AGCharUtf8::operator!= (const \fBAGCharUtf8\fP & c) const"
.PP
.SS "\fBAGCharUtf8\fP & AGCharUtf8::operator= (const \fBAGStringUtf8\fP & c)"
.PP
.SS "\fBAGCharUtf8\fP & AGCharUtf8::operator= (const \fBAGCharUtf8\fP & c)"
.PP
.SS "bool AGCharUtf8::operator== (const char pChar) const"
.PP
.SS "bool AGCharUtf8::operator== (const \fBAGCharUtf8\fP & c) const"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
