.TH "AGColor" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGColor \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_color.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGColor\fP (int pr, int pg, int pb, int pa=255)"
.br
.ti -1c
.RI "\fBAGColor\fP (const \fBAGColor\fP &c)"
.br
.ti -1c
.RI "\fBAGColor\fP (const \fBAGVector4\fP &v)"
.br
.ti -1c
.RI "\fBAGColor\fP (Uint32 c, const \fBAGSurface\fP &pSurface)"
.br
.ti -1c
.RI "\fBAGColor\fP (const \fBAGString\fP &s)"
.br
.ti -1c
.RI "\fBAGColor\fP ()"
.br
.ti -1c
.RI "\fBAGColor\fP & \fBoperator=\fP (const \fBAGColor\fP &c)"
.br
.ti -1c
.RI "\fBAGColor\fP & \fBoperator *=\fP (float f)"
.br
.ti -1c
.RI "\fBAGColor\fP \fBoperator *\fP (float f) const "
.br
.ti -1c
.RI "\fBAGColor\fP \fBoperator+\fP (const \fBAGColor\fP &c) const "
.br
.ti -1c
.RI "Uint32 \fBmapRGB\fP (SDL_PixelFormat *f) const "
.br
.ti -1c
.RI "\fBAGString\fP \fBtoString\fP () const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBtoVec\fP () const "
.br
.ti -1c
.RI "\fBAGColor\fP \fBgrey\fP () const "
.br
.ti -1c
.RI "Uint8 \fBbrightness\fP () const "
.br
.ti -1c
.RI "void \fBlight\fP (Uint8 l)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint8 \fBa\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGColor::AGColor (int pr, int pg, int pb, int pa = \fC255\fP)"
.PP
.SS "AGColor::AGColor (const \fBAGColor\fP & c)"
.PP
.SS "AGColor::AGColor (const \fBAGVector4\fP & v)"
.PP
.SS "AGColor::AGColor (Uint32 c, const \fBAGSurface\fP & pSurface)"
.PP
.SS "AGColor::AGColor (const \fBAGString\fP & s)"
.PP
.SS "AGColor::AGColor ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "Uint8 AGColor::brightness () const"
.PP
.SS "\fBAGColor\fP AGColor::grey () const"
.PP
.SS "void AGColor::light (Uint8 l)"
.PP
.SS "Uint32 AGColor::mapRGB (SDL_PixelFormat * f) const"
.PP
.SS "\fBAGColor\fP AGColor::operator * (float f) const"
.PP
.SS "\fBAGColor\fP & AGColor::operator *= (float f)"
.PP
.SS "\fBAGColor\fP AGColor::operator+ (const \fBAGColor\fP & c) const"
.PP
.SS "\fBAGColor\fP & AGColor::operator= (const \fBAGColor\fP & c)"
.PP
.SS "\fBAGString\fP AGColor::toString () const"
.PP
.SS "\fBAGVector4\fP AGColor::toVec () const"
.PP
.SH "Member Data Documentation"
.PP 
.SS "Uint8 \fBAGColor::a\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
