.TH "AGDecryptor" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGDecryptor \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_surface.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AGDecryptor\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBdecrypt\fP (const std::string &s, const std::string &n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAGDecryptor\fP provides functionaliy for DRM-plugged images and music-files. You have to derive from this class and give an instance when loading a surface. When you have done so saving is disabled afterwards. 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual AGDecryptor::~AGDecryptor ()\fC [inline, virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string AGDecryptor::decrypt (const std::string & s, const std::string & n)\fC [inline, virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
