.TH "AGDestructionSender" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGDestructionSender \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_destructor.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGDestructionSender\fP (\fBAGDestructionHandler\fP *pHandler, const std::string &pName='')"
.br
.ti -1c
.RI "virtual \fB~AGDestructionSender\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAGDestructionHandler\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGDestructionSender::AGDestructionSender (\fBAGDestructionHandler\fP * pHandler, const std::string & pName = \fC''\fP)"
.PP
.SS "AGDestructionSender::~AGDestructionSender ()\fC [virtual]\fP"
.PP
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBAGDestructionHandler\fP\fC [friend]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
