.TH "AGEditElement" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGEditElement \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_editcontent.h>\fP
.PP
Inherited by \fBAGEditNewLine\fP, \fBAGEditString\fP, \fBAGEditSurface\fP, and \fBAGEditWhiteSpace\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AGEditElement\fP ()"
.br
.ti -1c
.RI "virtual size_t \fBsize\fP ()"
.br
.ti -1c
.RI "virtual int \fBwidth\fP ()"
.br
.ti -1c
.RI "virtual int \fBheight\fP ()"
.br
.ti -1c
.RI "virtual void \fBrender\fP (\fBAGPainter\fP &p, int x, int y)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual AGEditElement::~AGEditElement ()\fC [inline, virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual int AGEditElement::height ()\fC [inline, virtual]\fP"
.PP
Reimplemented in \fBAGEditString\fP, \fBAGEditWhiteSpace\fP, and \fBAGEditSurface\fP.
.SS "virtual void AGEditElement::render (\fBAGPainter\fP & p, int x, int y)\fC [inline, virtual]\fP"
.PP
Reimplemented in \fBAGEditString\fP, and \fBAGEditSurface\fP.
.SS "virtual size_t AGEditElement::size ()\fC [inline, virtual]\fP"
.PP
Reimplemented in \fBAGEditString\fP, \fBAGEditWhiteSpace\fP, \fBAGEditNewLine\fP, and \fBAGEditSurface\fP.
.SS "virtual int AGEditElement::width ()\fC [inline, virtual]\fP"
.PP
Reimplemented in \fBAGEditString\fP, \fBAGEditWhiteSpace\fP, and \fBAGEditSurface\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
