.TH "AGEvent" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGEvent \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_messageobject.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGEvent\fP (\fBAGListener\fP *pCaller, const \fBAGString\fP &pName, const SDL_Event *pEvent=0)"
.br
.ti -1c
.RI "virtual \fB~AGEvent\fP ()"
.br
.ti -1c
.RI "\fBAGListener\fP * \fBgetCaller\fP () const "
.br
.RI "\fIreturns the caller of this event \fP"
.ti -1c
.RI "void \fBsetCaller\fP (\fBAGListener\fP *pCaller)"
.br
.RI "\fIsets the caller of this event - shouldn't be used outside of \fBAGWidget\fP \fP"
.ti -1c
.RI "\fBAGString\fP \fBgetName\fP () const "
.br
.RI "\fIreturn the name of the event \fP"
.ti -1c
.RI "\fBAGVector2\fP \fBgetMousePosition\fP () const "
.br
.ti -1c
.RI "SDLKey \fBgetKey\fP () const "
.br
.ti -1c
.RI "SDLMod \fBgetMod\fP () const "
.br
.ti -1c
.RI "Uint16 \fBgetUnicode\fP () const "
.br
.ti -1c
.RI "int \fBgetButton\fP () const "
.br
.ti -1c
.RI "const SDL_Event * \fBget\fP () const "
.br
.ti -1c
.RI "bool \fBisSDLEvent\fP () const "
.br
.ti -1c
.RI "void \fBsetName\fP (const \fBAGString\fP &n)"
.br
.ti -1c
.RI "void \fBsetVector\fP (const \fBAGVector2\fP &v)"
.br
.ti -1c
.RI "\fBAGVector2\fP \fBgetVector\fP () const "
.br
.RI "\fIreturns the drag-vector in case of a drag-event \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBAGEvent\fP is the typical event which is passed when the user does anything. You can however derive from it and pass it through a signal. But you shouldn't delete it for yourself. 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGEvent::AGEvent (\fBAGListener\fP * pCaller, const \fBAGString\fP & pName, const SDL_Event * pEvent = \fC0\fP)"
.PP
.SS "AGEvent::~AGEvent ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "const SDL_Event * AGEvent::get () const"
.PP
.SS "int AGEvent::getButton () const"
.PP
.SS "\fBAGListener\fP * AGEvent::getCaller () const"
.PP
returns the caller of this event 
.PP
.SS "SDLKey AGEvent::getKey () const"
.PP
.SS "SDLMod AGEvent::getMod () const"
.PP
.SS "\fBAGVector2\fP AGEvent::getMousePosition () const"
.PP
.SS "\fBAGString\fP AGEvent::getName () const"
.PP
return the name of the event 
.PP
.SS "Uint16 AGEvent::getUnicode () const"
.PP
.SS "\fBAGVector2\fP AGEvent::getVector () const"
.PP
returns the drag-vector in case of a drag-event 
.PP
.SS "bool AGEvent::isSDLEvent () const"
.PP
.SS "void AGEvent::setCaller (\fBAGListener\fP * pCaller)"
.PP
sets the caller of this event - shouldn't be used outside of \fBAGWidget\fP 
.PP
.SS "void AGEvent::setName (const \fBAGString\fP & n)"
.PP
.SS "void AGEvent::setVector (const \fBAGVector2\fP & v)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
