.TH "AGFBO" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGFBO \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_fbo.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGFBO\fP (\fBAGGLTexture\fP *pTexture, bool withDepth=false)"
.br
.ti -1c
.RI "\fBAGFBO\fP (GLuint pTexture, size_t pW, size_t pH)"
.br
.ti -1c
.RI "\fB~AGFBO\fP ()"
.br
.ti -1c
.RI "void \fBbeginDraw\fP ()"
.br
.ti -1c
.RI "void \fBendDraw\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGFBO::AGFBO (\fBAGGLTexture\fP * pTexture, bool withDepth = \fCfalse\fP)"
.PP
.SS "AGFBO::AGFBO (GLuint pTexture, size_t pW, size_t pH)"
.PP
.SS "AGFBO::~AGFBO ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGFBO::beginDraw ()"
.PP
.SS "void AGFBO::endDraw ()"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
