.TH "AGFontEngine" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGFontEngine \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_fontengine.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGFontEngine\fP ()"
.br
.ti -1c
.RI "\fB~AGFontEngine\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAGTexture\fP * \fBrenderText\fP (int BaseLineX, int BaseLineY, const \fBAGStringUtf8\fP &pText, const \fBAGFont\fP &ParamIn)"
.br
.ti -1c
.RI "static int \fBgetWidth\fP (const \fBAGFont\fP &pFont, const \fBAGStringUtf8\fP &pText)"
.br
.ti -1c
.RI "static int \fBgetHeight\fP (const \fBAGFont\fP &pFont, const \fBAGStringUtf8\fP &pText)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGFontEngine::AGFontEngine ()"
.PP
.SS "AGFontEngine::~AGFontEngine ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "int AGFontEngine::getHeight (const \fBAGFont\fP & pFont, const \fBAGStringUtf8\fP & pText)\fC [static]\fP"
.PP
.SS "int AGFontEngine::getWidth (const \fBAGFont\fP & pFont, const \fBAGStringUtf8\fP & pText)\fC [static]\fP"
.PP
.SS "\fBAGTexture\fP * AGFontEngine::renderText (int BaseLineX, int BaseLineY, const \fBAGStringUtf8\fP & pText, const \fBAGFont\fP & ParamIn)\fC [static]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
