.TH "AGInstanceKiller" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGInstanceKiller \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_kill.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGInstanceKiller\fP ()"
.br
.ti -1c
.RI "\fB~AGInstanceKiller\fP ()"
.br
.ti -1c
.RI "void \fBreg\fP (\fBAGInstanceBase\fP *b)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGInstanceKiller::AGInstanceKiller ()"
.PP
.SS "AGInstanceKiller::~AGInstanceKiller ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGInstanceKiller::reg (\fBAGInstanceBase\fP * b)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
