.TH "AGListBoxItem" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGListBoxItem \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_listbox.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGListBoxItem\fP (\fBAGString\fP pID, \fBAGStringUtf8\fP pValue)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGString\fP \fBid\fP"
.br
.ti -1c
.RI "\fBAGStringUtf8\fP \fBvalue\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGListBoxItem::AGListBoxItem (\fBAGString\fP pID, \fBAGStringUtf8\fP pValue)"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBAGString\fP \fBAGListBoxItem::id\fP"
.PP
.SS "\fBAGStringUtf8\fP \fBAGListBoxItem::value\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
