.TH "AGListener" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGListener \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_messageobject.h>\fP
.PP
Inherits \fBAGRubyObject\fP.
.PP
Inherited by \fBAGMessageObject\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGListener\fP ()"
.br
.ti -1c
.RI "virtual \fB~AGListener\fP ()"
.br
.ti -1c
.RI "virtual bool \fBsignal\fP (\fBAGEvent\fP *m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAGListener\fP is the base for receiving an event. Any object which is derived from \fBAGListener\fP can receive an event. But you should use \fBAGMessageObject\fP for this, as it holds basic 'listening' facilities. 
.PP
\fBSee also:\fP
.RS 4
\fBAGEvent\fP 
.RE
.PP

.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGListener::AGListener ()"
.PP
.SS "AGListener::~AGListener ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool AGListener::signal (\fBAGEvent\fP * m)\fC [virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
