.TH "AGListBoxLayoutCreator" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGListBoxLayoutCreator \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBAGLayoutCreator\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBAGWidget\fP * \fBcreate\fP (\fBAGWidget\fP *pParent, const \fBAGRect2\fP &pRect, const \fBNode\fP &pNode)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBAGWidget\fP* AGListBoxLayoutCreator::create (\fBAGWidget\fP * pParent, const \fBAGRect2\fP & pRect, const \fBNode\fP & pNode)\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBAGLayoutCreator\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
