.TH "AGLocalizer" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGLocalizer \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_local.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AGLocalizer\fP ()"
.br
.ti -1c
.RI "virtual \fBAGStringUtf8\fP \fBfind\fP (const \fBAGString\fP &p)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGLocalizer::~AGLocalizer ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGStringUtf8\fP AGLocalizer::find (const \fBAGString\fP & p)\fC [virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
