.TH "AGMenu" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGMenu \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_menu.h>\fP
.PP
Inherits \fBAGTable\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGMenu\fP (\fBAGWidget\fP *pParent, \fBAGVector2\fP pWishPos, const \fBAGStringUtf8\fP &pName)"
.br
.ti -1c
.RI "void \fBshow\fP (\fBAGVector2\fP pWishPos)"
.br
.ti -1c
.RI "void \fBaddItem\fP (const \fBAGStringUtf8\fP &pString)"
.br
.ti -1c
.RI "\fBAGMenu\fP & \fBaddMenu\fP (const \fBAGStringUtf8\fP &pString)"
.br
.ti -1c
.RI "void \fBdraw\fP (\fBAGPainter\fP &p)"
.br
.ti -1c
.RI "void \fBeventItemSelected\fP (const \fBAGString\fP &pString)"
.br
.ti -1c
.RI "void \fBeventItemClicked\fP (const \fBAGString\fP &pString)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGSignal\fP \fBsigSelected\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGMenu::AGMenu (\fBAGWidget\fP * pParent, \fBAGVector2\fP pWishPos, const \fBAGStringUtf8\fP & pName)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGMenu::addItem (const \fBAGStringUtf8\fP & pString)"
.PP
.SS "\fBAGMenu\fP & AGMenu::addMenu (const \fBAGStringUtf8\fP & pString)"
.PP
.SS "void AGMenu::draw (\fBAGPainter\fP & p)\fC [virtual]\fP"
.PP
Reimplemented from \fBAGWidget\fP.
.SS "void AGMenu::eventItemClicked (const \fBAGString\fP & pString)"
.PP
.SS "void AGMenu::eventItemSelected (const \fBAGString\fP & pString)"
.PP
.SS "void AGMenu::show (\fBAGVector2\fP pWishPos)"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBAGSignal\fP \fBAGMenu::sigSelected\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
