.TH "AGRect3" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGRect3 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGRect3\fP (const \fBAGVector3\fP &pBase, const \fBAGVector3\fP &pDir)"
.br
.ti -1c
.RI "bool \fBcollides\fP (const \fBAGLine3\fP &pLine) const "
.br
.ti -1c
.RI "\fBAGString\fP \fBtoString\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGRect3::AGRect3 (const \fBAGVector3\fP & pBase, const \fBAGVector3\fP & pDir)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool AGRect3::collides (const \fBAGLine3\fP & pLine) const"
.PP
.SS "\fBAGString\fP AGRect3::toString () const"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
