.TH "AGSDLScreen" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGSDLScreen \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_sdlsurface.h>\fP
.PP
Inherits \fBAGScreen\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGSDLScreen\fP (SDL_Surface *s)"
.br
.ti -1c
.RI "virtual void \fBblit\fP (const \fBAGTexture\fP &pSource, const \fBAGRect2\fP &\fBpDest\fP, const \fBAGRect2\fP &\fBpSrc\fP)"
.br
.ti -1c
.RI "virtual void \fBflip\fP ()"
.br
.ti -1c
.RI "virtual \fBAGRect2\fP \fBgetRect\fP () const "
.br
.ti -1c
.RI "virtual void \fBfillRect\fP (const \fBAGRect2\fP &pRect, const \fBAGColor\fP &c)"
.br
.ti -1c
.RI "virtual void \fBdrawLine\fP (const \fBAGVector2\fP &p0, const \fBAGVector2\fP &p1, const \fBAGColor\fP &c)"
.br
.ti -1c
.RI "virtual void \fBdrawGradientAlpha\fP (const \fBAGRect2\fP &rect, const \fBAGColor\fP &ul, const \fBAGColor\fP &ur, const \fBAGColor\fP &dl, const \fBAGColor\fP &dr)"
.br
.ti -1c
.RI "virtual void \fBdrawGradient\fP (const \fBAGRect2\fP &rect, const \fBAGColor\fP &ul, const \fBAGColor\fP &ur, const \fBAGColor\fP &dl, const \fBAGColor\fP &dr)"
.br
.ti -1c
.RI "virtual void \fBdrawBorder\fP (const \fBAGRect2\fP &rect, int W, const \fBAGColor\fP &c1, const \fBAGColor\fP &c2)"
.br
.ti -1c
.RI "virtual void \fBputPixel\fP (int x, int y, const \fBAGColor\fP &c)"
.br
.ti -1c
.RI "virtual size_t \fBgetWidth\fP () const "
.br
.ti -1c
.RI "virtual size_t \fBgetHeight\fP () const "
.br
.ti -1c
.RI "virtual void \fBclip\fP (const \fBAGRect2\fP &r)"
.br
.ti -1c
.RI "virtual void \fBunclip\fP ()"
.br
.ti -1c
.RI "\fBAGSurface\fP \fBscreenshot\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGSDLScreen::AGSDLScreen (SDL_Surface * s)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGSDLScreen::blit (const \fBAGTexture\fP & pSource, const \fBAGRect2\fP & pDest, const \fBAGRect2\fP & pSrc)\fC [virtual]\fP"
.PP
.SS "void AGSDLScreen::clip (const \fBAGRect2\fP & r)\fC [virtual]\fP"
.PP
Reimplemented from \fBAGPaintTarget\fP.
.SS "void AGSDLScreen::drawBorder (const \fBAGRect2\fP & rect, int W, const \fBAGColor\fP & c1, const \fBAGColor\fP & c2)\fC [virtual]\fP"
.PP
.SS "void AGSDLScreen::drawGradient (const \fBAGRect2\fP & rect, const \fBAGColor\fP & ul, const \fBAGColor\fP & ur, const \fBAGColor\fP & dl, const \fBAGColor\fP & dr)\fC [virtual]\fP"
.PP
.SS "void AGSDLScreen::drawGradientAlpha (const \fBAGRect2\fP & rect, const \fBAGColor\fP & ul, const \fBAGColor\fP & ur, const \fBAGColor\fP & dl, const \fBAGColor\fP & dr)\fC [virtual]\fP"
.PP
.SS "void AGSDLScreen::drawLine (const \fBAGVector2\fP & p0, const \fBAGVector2\fP & p1, const \fBAGColor\fP & c)\fC [virtual]\fP"
.PP
.SS "void AGSDLScreen::fillRect (const \fBAGRect2\fP & pRect, const \fBAGColor\fP & c)\fC [virtual]\fP"
.PP
.SS "void AGSDLScreen::flip ()\fC [virtual]\fP"
.PP
Reimplemented from \fBAGScreen\fP.
.SS "size_t AGSDLScreen::getHeight () const\fC [virtual]\fP"
.PP
Reimplemented from \fBAGScreen\fP.
.SS "\fBAGRect2\fP AGSDLScreen::getRect () const\fC [virtual]\fP"
.PP
.SS "size_t AGSDLScreen::getWidth () const\fC [virtual]\fP"
.PP
Reimplemented from \fBAGScreen\fP.
.SS "void AGSDLScreen::putPixel (int x, int y, const \fBAGColor\fP & c)\fC [virtual]\fP"
.PP
Reimplemented from \fBAGPaintTarget\fP.
.SS "\fBAGSurface\fP AGSDLScreen::screenshot ()\fC [virtual]\fP"
.PP
Reimplemented from \fBAGScreen\fP.
.SS "void AGSDLScreen::unclip ()\fC [virtual]\fP"
.PP
Reimplemented from \fBAGPaintTarget\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
