.TH "AGSlot0" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGSlot0 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_messageobject.h>\fP
.PP
Inherits \fBAGCPPListener\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef bool(T::* \fBFKT\fP )(\fBAGEvent\fP *m)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGSlot0\fP (T *pBase, \fBFKT\fP pF)"
.br
.ti -1c
.RI "virtual \fB~AGSlot0\fP ()"
.br
.ti -1c
.RI "virtual bool \fBsignal\fP (\fBAGEvent\fP *m) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T * \fBbase\fP"
.br
.ti -1c
.RI "\fBFKT\fP \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T> class AGSlot0< T >"
some syntactic sugar for simple connecting of slots and signals. 
.PP
\fBSee also:\fP
.RS 4
\fBAGSignal\fP 
.PP
\fBAGMessageObject\fP 
.RE
.PP

.PP
.SH "Member Typedef Documentation"
.PP 
.SS "template<class T> typedef bool(T::* \fBAGSlot0\fP< T >::\fBFKT\fP)(\fBAGEvent\fP *m)"
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBAGSlot0\fP< T >::\fBAGSlot0\fP (T * pBase, \fBFKT\fP pF)\fC [inline]\fP"
.PP
.SS "template<class T> virtual \fBAGSlot0\fP< T >::~\fBAGSlot0\fP ()\fC [inline, virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "template<class T> virtual bool \fBAGSlot0\fP< T >::signal (\fBAGEvent\fP * m) const\fC [inline, virtual]\fP"
.PP
Implements \fBAGCPPListener\fP.
.SH "Member Data Documentation"
.PP 
.SS "template<class T> T* \fBAGSlot0\fP< T >::\fBbase\fP"
.PP
.SS "template<class T> \fBFKT\fP \fBAGSlot0\fP< T >::\fBf\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
