.TH "AGSound" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGSound \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_mixer.h>\fP
.PP
Inherits \fBAGWidget\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGSound\fP ()"
.br
.ti -1c
.RI "\fB~AGSound\fP ()"
.br
.ti -1c
.RI "bool \fBplayMp3\fP (const std::string &pFilename)"
.br
.ti -1c
.RI "bool \fBplayMp3DRM\fP (const std::string &pFilename, \fBAGDecryptor\fP &pDec)"
.br
.ti -1c
.RI "bool \fBisMusicPlaying\fP () const "
.br
.ti -1c
.RI "void \fBstopMp3\fP ()"
.br
.ti -1c
.RI "void \fBcheckFinished\fP ()"
.br
.ti -1c
.RI "void \fBfadeOutMusic\fP (int ms)"
.br
.ti -1c
.RI "void \fBplayWave\fP (const std::string &pFilename, float v=-1.0)"
.br
.ti -1c
.RI "int \fBloopPlay\fP (const std::string &pFilename, float v=-1.0)"
.br
.ti -1c
.RI "void \fBstopChannel\fP (int i, int ms=200)"
.br
.ti -1c
.RI "void \fBstopAllChannels\fP (int ms=200)"
.br
.ti -1c
.RI "void \fBvolumeSound\fP (int i, float v)"
.br
.ti -1c
.RI "void \fBvolumeSound\fP (float v)"
.br
.ti -1c
.RI "void \fBvolumeMusic\fP (float v)"
.br
.ti -1c
.RI "void \fBloadWave\fP (const std::string &pFilename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGSignal\fP \fBsigMp3Finished\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBAGSound\fP * \fBgetSoundManager\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGSound::AGSound ()"
.PP
.SS "AGSound::~AGSound ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGSound::checkFinished ()"
.PP
.SS "void AGSound::fadeOutMusic (int ms)"
.PP
.SS "bool AGSound::isMusicPlaying () const"
.PP
.SS "void AGSound::loadWave (const std::string & pFilename)"
.PP
.SS "int AGSound::loopPlay (const std::string & pFilename, float v = \fC-1.0\fP)"
.PP
.SS "bool AGSound::playMp3 (const std::string & pFilename)"
.PP
.SS "bool AGSound::playMp3DRM (const std::string & pFilename, \fBAGDecryptor\fP & pDec)"
.PP
.SS "void AGSound::playWave (const std::string & pFilename, float v = \fC-1.0\fP)"
.PP
.SS "void AGSound::stopAllChannels (int ms = \fC200\fP)"
.PP
.SS "void AGSound::stopChannel (int i, int ms = \fC200\fP)"
.PP
.SS "void AGSound::stopMp3 ()"
.PP
.SS "void AGSound::volumeMusic (float v)"
.PP
.SS "void AGSound::volumeSound (float v)"
.PP
.SS "void AGSound::volumeSound (int i, float v)"
.PP
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBAGSound\fP* getSoundManager ()\fC [friend]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBAGSignal\fP \fBAGSound::sigMp3Finished\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
