.TH "AGSubMenu" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGSubMenu \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_menuitem.h>\fP
.PP
Inherits \fBAGMenuItem\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGSubMenu\fP (\fBAGWidget\fP *pParent, const \fBAGStringUtf8\fP &ptext)"
.br
.ti -1c
.RI "virtual \fB~AGSubMenu\fP ()"
.br
.ti -1c
.RI "\fBAGMenu\fP * \fBgetMenu\fP ()"
.br
.ti -1c
.RI "virtual void \fBeventSelect\fP ()"
.br
.ti -1c
.RI "virtual void \fBeventUnselect\fP ()"
.br
.ti -1c
.RI "virtual bool \fBeventMouseClick\fP (\fBAGEvent\fP *m)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGSubMenu::AGSubMenu (\fBAGWidget\fP * pParent, const \fBAGStringUtf8\fP & ptext)"
.PP
.SS "AGSubMenu::~AGSubMenu ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool AGSubMenu::eventMouseClick (\fBAGEvent\fP * m)\fC [virtual]\fP"
.PP
Reimplemented from \fBAGMenuItem\fP.
.SS "void AGSubMenu::eventSelect ()\fC [virtual]\fP"
.PP
Reimplemented from \fBAGMenuItem\fP.
.SS "void AGSubMenu::eventUnselect ()\fC [virtual]\fP"
.PP
Reimplemented from \fBAGMenuItem\fP.
.SS "\fBAGMenu\fP * AGSubMenu::getMenu ()"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
