.TH "AGTableLayoutCreator" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGTableLayoutCreator \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBAGLayoutCreator\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBAGWidget\fP * \fBcreate\fP (\fBAGWidget\fP *pParent, const \fBAGRect2\fP &pRect, const \fBNode\fP &pNode)"
.br
.ti -1c
.RI "\fBAGTable\fP * \fBparseTable\fP (\fBAGWidget\fP *pParent, const \fBNode\fP &pNode, const \fBAGRect2\fP &geom)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBAGWidget\fP* AGTableLayoutCreator::create (\fBAGWidget\fP * pParent, const \fBAGRect2\fP & pRect, const \fBNode\fP & pNode)\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBAGLayoutCreator\fP.
.SS "\fBAGTable\fP* AGTableLayoutCreator::parseTable (\fBAGWidget\fP * pParent, const \fBNode\fP & pNode, const \fBAGRect2\fP & geom)\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
