.TH "AGText" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGText \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_text.h>\fP
.PP
Inherits \fBAGWidget\fP.
.PP
Inherited by \fBAGCaption\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGText\fP (\fBAGWidget\fP *pParent, const \fBAGRect2\fP &pRect, const \fBAGStringUtf8\fP &pText, const \fBAGFont\fP &pFont)"
.br
.ti -1c
.RI "\fBAGText\fP (\fBAGWidget\fP *pParent, const \fBAGVector2\fP &pPoint, const \fBAGStringUtf8\fP &pText, const \fBAGFont\fP &pFont)"
.br
.ti -1c
.RI "void \fBsetDeriveRect\fP ()"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (\fBAGPainter\fP &p)"
.br
.ti -1c
.RI "void \fBsetText\fP (const \fBAGStringUtf8\fP &pText)"
.br
.ti -1c
.RI "\fBAGStringUtf8\fP \fBgetText\fP () const "
.br
.ti -1c
.RI "void \fBsetFont\fP (const \fBAGFont\fP &f)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGText::AGText (\fBAGWidget\fP * pParent, const \fBAGRect2\fP & pRect, const \fBAGStringUtf8\fP & pText, const \fBAGFont\fP & pFont)"
.PP
.SS "AGText::AGText (\fBAGWidget\fP * pParent, const \fBAGVector2\fP & pPoint, const \fBAGStringUtf8\fP & pText, const \fBAGFont\fP & pFont)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AGText::draw (\fBAGPainter\fP & p)\fC [virtual]\fP"
.PP
Reimplemented from \fBAGWidget\fP.
.PP
Reimplemented in \fBAGCaption\fP.
.SS "\fBAGStringUtf8\fP AGText::getText () const"
.PP
.SS "void AGText::setDeriveRect ()"
.PP
.SS "void AGText::setFont (const \fBAGFont\fP & f)"
.PP
.SS "void AGText::setText (const \fBAGStringUtf8\fP & pText)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
