.TH "AGTheme" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGTheme \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_theme.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGTheme\fP ()"
.br
.ti -1c
.RI "virtual \fB~AGTheme\fP ()"
.br
.ti -1c
.RI "\fBAGFont\fP \fBgetFont\fP (const \fBAGString\fP &pName)"
.br
.ti -1c
.RI "\fBAGColor\fP \fBgetColor\fP (const \fBAGString\fP &pName)"
.br
.ti -1c
.RI "void \fBsetFont\fP (const \fBAGString\fP &pName, \fBAGFont\fP pFont)"
.br
.ti -1c
.RI "void \fBsetColor\fP (const \fBAGString\fP &pName, \fBAGColor\fP pColor)"
.br
.ti -1c
.RI "int \fBgetInt\fP (const \fBAGString\fP &pName)"
.br
.ti -1c
.RI "void \fBsetInt\fP (const \fBAGString\fP &pName, int i)"
.br
.ti -1c
.RI "\fBAGSurface\fP \fBgetSurface\fP (const \fBAGString\fP &pName)"
.br
.ti -1c
.RI "void \fBsetSurface\fP (const \fBAGString\fP &pName, const \fBAGSurface\fP &pSurface)"
.br
.ti -1c
.RI "std::string \fBgetSurfaceName\fP (const \fBAGString\fP &pName)"
.br
.ti -1c
.RI "void \fBsetSurfaceName\fP (const \fBAGString\fP &pName, const std::string &pSurface)"
.br
.ti -1c
.RI "bool \fBhasSurface\fP (const \fBAGString\fP &pName) const "
.br
.ti -1c
.RI "bool \fBhasColor\fP (const \fBAGString\fP &pName) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGTheme::AGTheme ()"
.PP
.SS "AGTheme::~AGTheme ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGColor\fP AGTheme::getColor (const \fBAGString\fP & pName)"
.PP
.SS "\fBAGFont\fP AGTheme::getFont (const \fBAGString\fP & pName)"
.PP
.SS "int AGTheme::getInt (const \fBAGString\fP & pName)"
.PP
.SS "\fBAGSurface\fP AGTheme::getSurface (const \fBAGString\fP & pName)"
.PP
.SS "std::string AGTheme::getSurfaceName (const \fBAGString\fP & pName)"
.PP
.SS "bool AGTheme::hasColor (const \fBAGString\fP & pName) const"
.PP
.SS "bool AGTheme::hasSurface (const \fBAGString\fP & pName) const"
.PP
.SS "void AGTheme::setColor (const \fBAGString\fP & pName, \fBAGColor\fP pColor)"
.PP
.SS "void AGTheme::setFont (const \fBAGString\fP & pName, \fBAGFont\fP pFont)"
.PP
.SS "void AGTheme::setInt (const \fBAGString\fP & pName, int i)"
.PP
.SS "void AGTheme::setSurface (const \fBAGString\fP & pName, const \fBAGSurface\fP & pSurface)"
.PP
.SS "void AGTheme::setSurfaceName (const \fBAGString\fP & pName, const std::string & pSurface)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
