.TH "AGTriangle2" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGTriangle2 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGTriangle2\fP (const \fBAGVector2\fP &v0, const \fBAGVector2\fP &v1, const \fBAGVector2\fP &v2)"
.br
.ti -1c
.RI "\fBAGVector2\fP \fBoperator[]\fP (int index) const "
.br
.ti -1c
.RI "\fBAGVector2\fP \fBget\fP (int index) const "
.br
.ti -1c
.RI "bool \fBcollide\fP (const \fBAGTriangle2\fP &t) const "
.br
.ti -1c
.RI "std::vector< \fBAGVector2\fP > \fBgetNormals\fP () const "
.br
.ti -1c
.RI "void \fBapply\fP (const \fBAGMatrix3\fP &m)"
.br
.ti -1c
.RI "\fBAGTriangle2\fP \fBapplied\fP (const \fBAGMatrix3\fP &m) const "
.br
.ti -1c
.RI "\fBAGVector2\fP \fBtouchPoint\fP (const \fBAGTriangle2\fP &t) const "
.br
.ti -1c
.RI "\fBAGVector2\fP \fBtouchVector\fP (const \fBAGTriangle2\fP &t) const "
.br
.ti -1c
.RI "std::vector< \fBAGVector2\fP > \fBcollisionPoints\fP (const \fBAGLine2\fP &l) const "
.br
.ti -1c
.RI "bool \fBcontains\fP (const \fBAGVector2\fP &p) const "
.br
.ti -1c
.RI "\fBAGRect2\fP \fBgetBBox\fP () const "
.br
.ti -1c
.RI "\fBAGLine2\fP \fBnearestLine\fP (const \fBAGVector2\fP &v) const "
.br
.ti -1c
.RI "std::vector< \fBAGLine2\fP > \fBgetLines\fP () const "
.br
.ti -1c
.RI "\fBAGString\fP \fBtoString\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGTriangle2::AGTriangle2 (const \fBAGVector2\fP & v0, const \fBAGVector2\fP & v1, const \fBAGVector2\fP & v2)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGTriangle2\fP AGTriangle2::applied (const \fBAGMatrix3\fP & m) const"
.PP
.SS "void AGTriangle2::apply (const \fBAGMatrix3\fP & m)"
.PP
.SS "bool AGTriangle2::collide (const \fBAGTriangle2\fP & t) const"
.PP
.SS "std::vector< \fBAGVector2\fP > AGTriangle2::collisionPoints (const \fBAGLine2\fP & l) const"
.PP
.SS "bool AGTriangle2::contains (const \fBAGVector2\fP & p) const"
.PP
.SS "\fBAGVector2\fP AGTriangle2::get (int index) const"
.PP
.SS "\fBAGRect2\fP AGTriangle2::getBBox () const"
.PP
.SS "std::vector< \fBAGLine2\fP > AGTriangle2::getLines () const"
.PP
.SS "std::vector< \fBAGVector2\fP > AGTriangle2::getNormals () const"
.PP
.SS "\fBAGLine2\fP AGTriangle2::nearestLine (const \fBAGVector2\fP & v) const"
.PP
.SS "\fBAGVector2\fP AGTriangle2::operator[] (int index) const"
.PP
.SS "\fBAGString\fP AGTriangle2::toString () const"
.PP
.SS "\fBAGVector2\fP AGTriangle2::touchPoint (const \fBAGTriangle2\fP & t) const"
.PP
.SS "\fBAGVector2\fP AGTriangle2::touchVector (const \fBAGTriangle2\fP & t) const"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
