.TH "AGVertexProgram" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGVertexProgram \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_glsl.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGVertexProgram\fP (const std::string &pFile)"
.br
.ti -1c
.RI "\fB~AGVertexProgram\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAGShaderProgram\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGVertexProgram::AGVertexProgram (const std::string & pFile)"
.PP
.SS "AGVertexProgram::~AGVertexProgram ()"
.PP
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBAGShaderProgram\fP\fC [friend]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
