.TH "AGVector4" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AGVector4 \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_geometry.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGVector4\fP (float pX, float pY, float pZ, float pW=1.0f)"
.br
.ti -1c
.RI "\fBAGVector4\fP (const \fBAGVector4\fP &a)"
.br
.ti -1c
.RI "\fBAGVector4\fP (const \fBAGVector3\fP &a, float h)"
.br
.ti -1c
.RI "\fBAGVector4\fP ()"
.br
.ti -1c
.RI "void \fBsetX\fP (float pX)"
.br
.ti -1c
.RI "void \fBsetY\fP (float pY)"
.br
.ti -1c
.RI "void \fBsetZ\fP (float pZ)"
.br
.ti -1c
.RI "void \fBsetW\fP (float pW)"
.br
.ti -1c
.RI "float \fBgetX\fP () const "
.br
.ti -1c
.RI "float \fBgetY\fP () const "
.br
.ti -1c
.RI "float \fBgetZ\fP () const "
.br
.ti -1c
.RI "float \fBgetW\fP () const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBoperator-\fP (const \fBAGVector4\fP &p) const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBoperator+\fP (const \fBAGVector4\fP &p) const "
.br
.ti -1c
.RI "\fBAGVector4\fP & \fBoperator+=\fP (const \fBAGVector4\fP &p)"
.br
.ti -1c
.RI "\fBAGVector4\fP & \fBoperator-=\fP (const \fBAGVector4\fP &p)"
.br
.ti -1c
.RI "float \fBoperator *\fP (const \fBAGVector4\fP &p) const "
.br
.ti -1c
.RI "\fBAGVector4\fP & \fBoperator *=\fP (float f)"
.br
.ti -1c
.RI "\fBAGVector4\fP & \fBoperator/=\fP (float f)"
.br
.ti -1c
.RI "\fBAGVector4\fP \fBoperator *\fP (float f) const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBoperator/\fP (float f) const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBoperator-\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAGVector4\fP &a) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBAGVector4\fP &a) const "
.br
.ti -1c
.RI "float \fBlength\fP () const "
.br
.ti -1c
.RI "float \fBlength2\fP () const "
.br
.ti -1c
.RI "float \fBlength3\fP () const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBnormalized\fP () const "
.br
.ti -1c
.RI "void \fBnormalize\fP ()"
.br
.ti -1c
.RI "\fBAGVector4\fP \fBnormalized3\fP () const "
.br
.ti -1c
.RI "void \fBnormalize3\fP ()"
.br
.ti -1c
.RI "float \fBoperator[]\fP (int index) const "
.br
.ti -1c
.RI "float & \fBoperator[]\fP (int index)"
.br
.ti -1c
.RI "bool \fBnonZero\fP () const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBoperator%\fP (const \fBAGVector4\fP &a) const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBcross\fP (const \fBAGVector4\fP &a) const "
.br
.ti -1c
.RI "\fBAGVector3\fP \fBdim3\fP () const "
.br
.ti -1c
.RI "\fBAGVector2\fP \fBdim2\fP () const "
.br
.ti -1c
.RI "\fBAGString\fP \fBtoString\fP () const "
.br
.ti -1c
.RI "\fBoperator float *)\fP ()"
.br
.ti -1c
.RI "\fBoperator const float *)\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBv\fP [4]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AGVector4::AGVector4 (float pX, float pY, float pZ, float pW = \fC1.0f\fP)"
.PP
.SS "AGVector4::AGVector4 (const \fBAGVector4\fP & a)"
.PP
.SS "AGVector4::AGVector4 (const \fBAGVector3\fP & a, float h)"
.PP
.SS "AGVector4::AGVector4 ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGVector4\fP AGVector4::cross (const \fBAGVector4\fP & a) const\fC [inline]\fP"
.PP
.SS "\fBAGVector2\fP AGVector4::dim2 () const"
.PP
.SS "\fBAGVector3\fP AGVector4::dim3 () const"
.PP
.SS "float AGVector4::getW () const"
.PP
.SS "float AGVector4::getX () const"
.PP
.SS "float AGVector4::getY () const"
.PP
.SS "float AGVector4::getZ () const"
.PP
.SS "float AGVector4::length () const"
.PP
.SS "float AGVector4::length2 () const"
.PP
.SS "float AGVector4::length3 () const"
.PP
.SS "bool AGVector4::nonZero () const"
.PP
.SS "void AGVector4::normalize ()"
.PP
.SS "void AGVector4::normalize3 ()"
.PP
.SS "\fBAGVector4\fP AGVector4::normalized () const"
.PP
.SS "\fBAGVector4\fP AGVector4::normalized3 () const"
.PP
.SS "\fBAGVector4\fP AGVector4::operator * (float f) const"
.PP
.SS "float AGVector4::operator * (const \fBAGVector4\fP & p) const"
.PP
.SS "\fBAGVector4\fP & AGVector4::operator *= (float f)"
.PP
.SS "AGVector4::operator const float *) () const"
.PP
.SS "AGVector4::operator float *) ()"
.PP
.SS "bool AGVector4::operator!= (const \fBAGVector4\fP & a) const"
.PP
.SS "\fBAGVector4\fP AGVector4::operator% (const \fBAGVector4\fP & a) const"
.PP
.SS "\fBAGVector4\fP AGVector4::operator+ (const \fBAGVector4\fP & p) const"
.PP
.SS "\fBAGVector4\fP & AGVector4::operator+= (const \fBAGVector4\fP & p)"
.PP
.SS "\fBAGVector4\fP AGVector4::operator- () const"
.PP
.SS "\fBAGVector4\fP AGVector4::operator- (const \fBAGVector4\fP & p) const"
.PP
.SS "\fBAGVector4\fP & AGVector4::operator-= (const \fBAGVector4\fP & p)"
.PP
.SS "\fBAGVector4\fP AGVector4::operator/ (float f) const"
.PP
.SS "\fBAGVector4\fP & AGVector4::operator/= (float f)"
.PP
.SS "bool AGVector4::operator== (const \fBAGVector4\fP & a) const"
.PP
.SS "float & AGVector4::operator[] (int index)"
.PP
.SS "float AGVector4::operator[] (int index) const"
.PP
.SS "void AGVector4::setW (float pW)"
.PP
.SS "void AGVector4::setX (float pX)"
.PP
.SS "void AGVector4::setY (float pY)"
.PP
.SS "void AGVector4::setZ (float pZ)"
.PP
.SS "\fBAGString\fP AGVector4::toString () const"
.PP
.SH "Member Data Documentation"
.PP 
.SS "float \fBAGVector4::v\fP[4]"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
