.TH "src/anim_mesh.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/anim_mesh.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'anim_mesh.h'\fP
.br
\fC#include 'scene.h'\fP
.br
\fC#include 'ag_texturecache.h'\fP
.br
\fC#include 'ag_rendercontext.h'\fP
.br
\fC#include 'ag_debug.h'\fP
.br
\fC#include 'ag_xml.h'\fP
.br
\fC#include 'ag_fs.h'\fP
.br
\fC#include 'ag_config.h'\fP
.br
\fC#include 'ag_profiler.h'\fP
.br
\fC#include 'entity.h'\fP
.br
\fC#include <math.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBuseShaderAnimation\fP ()"
.br
.ti -1c
.RI "void \fBsetRotation\fP (\fBAGMatrix4\fP &m, const \fBAGVector3\fP &angles)"
.br
.ti -1c
.RI "void \fBsetTranslation\fP (\fBAGMatrix4\fP &m, const \fBAGVector3\fP &t)"
.br
.ti -1c
.RI "void \fBinverseRotate\fP (\fBAGVector3\fP &v, const \fBAGMatrix4\fP &m)"
.br
.ti -1c
.RI "void \fBinverseTranslate\fP (\fBAGVector3\fP &v, const \fBAGMatrix4\fP &m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void inverseRotate (\fBAGVector3\fP & v, const \fBAGMatrix4\fP & m)"
.PP
.SS "void inverseTranslate (\fBAGVector3\fP & v, const \fBAGMatrix4\fP & m)"
.PP
.SS "void setRotation (\fBAGMatrix4\fP & m, const \fBAGVector3\fP & angles)"
.PP
.SS "void setTranslation (\fBAGMatrix4\fP & m, const \fBAGVector3\fP & t)"
.PP
.SS "bool useShaderAnimation ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
