.TH "src/ant_app.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ant_app.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'scene.h'\fP
.br
\fC#include 'ant_renderer.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <ag_application.h>\fP
.br
\fC#include <ag_debug.h>\fP
.br
\fC#include <ag_main.h>\fP
.br
\fC#include <ag_geometry.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGLApp\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::ofstream \fBout\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::ofstream \fBout\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
