.TH "src/ant_camera.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ant_camera.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GLee.h>\fP
.br
\fC#include <ant_frustum.h>\fP
.br
\fC#include <ant_projection.h>\fP
.br
\fC#include <ag_rubyobj.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAntCamera\fP"
.br
.RI "\fIa camera object for moving over a height map
.PP
This function provides functions for moving a camera about and computation of the used 4x4-matrixes for camera-view and lighting (mainly used for shadows) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
