.TH "src/ant_frustum.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ant_frustum.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ag_geometry.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAntPlane\fP"
.br
.ti -1c
.RI "class \fBAntFrustum\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAntPlane\fP \fBmakePlane\fP (const \fBAGVector3\fP &p0, const \fBAGVector3\fP &p1, const \fBAGVector3\fP &p2)"
.br
.RI "\fIp0 is center - p1 is above and p2 at the right, then positive normal points into screen \fP"
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAntPlane\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBAntFrustum\fP &p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAntPlane\fP makePlane (const \fBAGVector3\fP & p0, const \fBAGVector3\fP & p1, const \fBAGVector3\fP & p2)"
.PP
p0 is center - p1 is above and p2 at the right, then positive normal points into screen 
.PP
.SS "std::ostream& operator<< (std::ostream & o, const \fBAntFrustum\fP & p)"
.PP
.SS "std::ostream& operator<< (std::ostream & o, const \fBAntPlane\fP & p)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
