.TH "src/ant_renderer.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ant_renderer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GLee.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRenderer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRenderer\fP * \fBgetRenderer\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBRenderer\fP* getRenderer ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
