.TH "AntEntityPtr" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AntEntityPtr \- 
.SH SYNOPSIS
.br
.PP
\fC#include <entptr.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAntEntityPtr\fP (const \fBAntEntityPtr\fP &p)"
.br
.ti -1c
.RI "\fBAntEntityPtr\fP (\fBAntEntity\fP *p)"
.br
.ti -1c
.RI "\fBAntEntityPtr\fP ()"
.br
.ti -1c
.RI "\fBAntEntity\fP * \fBget\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AntEntityPtr::AntEntityPtr (const \fBAntEntityPtr\fP & p)"
.PP
.SS "AntEntityPtr::AntEntityPtr (\fBAntEntity\fP * p)"
.PP
.SS "AntEntityPtr::AntEntityPtr ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAntEntity\fP * AntEntityPtr::get ()"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
