.TH "AntWaterShader" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AntWaterShader \- 
.SH SYNOPSIS
.br
.PP
\fC#include <glsl.h>\fP
.PP
Inherits \fBAntShaderProgram\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAntWaterShader\fP ()"
.br
.ti -1c
.RI "void \fBdoUpdate\fP (float time)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AntWaterShader::AntWaterShader ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void AntWaterShader::doUpdate (float time)\fC [virtual]\fP"
.PP
Reimplemented from \fBAntShaderProgram\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
