.TH "BinaryIn" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryIn \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_serial.h>\fP
.PP
Inherited by \fBBinaryFileIn\fP, and \fBBinaryStringIn\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryIn\fP ()"
.br
.ti -1c
.RI "virtual \fB~BinaryIn\fP ()"
.br
.ti -1c
.RI "virtual bool \fBeof\fP ()"
.br
.ti -1c
.RI "virtual char \fBread\fP ()"
.br
.ti -1c
.RI "\fBBinaryIn\fP & \fBoperator>>\fP (Sint32 &i)"
.br
.ti -1c
.RI "\fBBinaryIn\fP & \fBoperator>>\fP (Uint32 &i)"
.br
.ti -1c
.RI "\fBBinaryIn\fP & \fBoperator>>\fP (Uint16 &i)"
.br
.ti -1c
.RI "\fBBinaryIn\fP & \fBoperator>>\fP (float &f)"
.br
.ti -1c
.RI "\fBBinaryIn\fP & \fBoperator>>\fP (\fBAGVector2\fP &v)"
.br
.ti -1c
.RI "\fBBinaryIn\fP & \fBoperator>>\fP (\fBAGVector3\fP &v)"
.br
.ti -1c
.RI "\fBBinaryIn\fP & \fBoperator>>\fP (\fBAGVector4\fP &v)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BinaryIn::BinaryIn ()"
.PP
.SS "BinaryIn::~BinaryIn ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool BinaryIn::eof ()\fC [virtual]\fP"
.PP
Reimplemented in \fBBinaryFileIn\fP, and \fBBinaryStringIn\fP.
.SS "\fBBinaryIn\fP & BinaryIn::operator>> (\fBAGVector4\fP & v)"
.PP
.SS "\fBBinaryIn\fP & BinaryIn::operator>> (\fBAGVector3\fP & v)"
.PP
.SS "\fBBinaryIn\fP & BinaryIn::operator>> (\fBAGVector2\fP & v)"
.PP
.SS "\fBBinaryIn\fP & BinaryIn::operator>> (float & f)"
.PP
.SS "\fBBinaryIn\fP & BinaryIn::operator>> (Uint16 & i)"
.PP
.SS "\fBBinaryIn\fP & BinaryIn::operator>> (Uint32 & i)"
.PP
.SS "\fBBinaryIn\fP & BinaryIn::operator>> (Sint32 & i)"
.PP
.SS "char BinaryIn::read ()\fC [virtual]\fP"
.PP
Reimplemented in \fBBinaryFileIn\fP, and \fBBinaryStringIn\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
