.TH "Bone" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bone \- 
.SH SYNOPSIS
.br
.PP
\fC#include <anim_mesh_data.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAGVector3\fP \fBinterpolateRot\fP (float t)"
.br
.ti -1c
.RI "\fBAGVector3\fP \fBinterpolateTrans\fP (float t)"
.br
.ti -1c
.RI "\fBAGVector3\fP \fBinterpolate\fP (const std::vector< \fBKeyFrame\fP > &frames, float t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBid\fP"
.br
.ti -1c
.RI "\fBAGVector3\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBAGVector3\fP \fBrot\fP"
.br
.ti -1c
.RI "\fBAGMatrix4\fP \fBmRelative\fP"
.br
.ti -1c
.RI "\fBAGMatrix4\fP \fBmAbsolute\fP"
.br
.ti -1c
.RI "\fBAGMatrix4\fP \fBmFinal\fP"
.br
.ti -1c
.RI "\fBBone\fP * \fBparent\fP"
.br
.ti -1c
.RI "std::vector< \fBKeyFrame\fP > \fBrFrames\fP"
.br
.ti -1c
.RI "std::vector< \fBKeyFrame\fP > \fBtFrames\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBAGVector3\fP Bone::interpolate (const std::vector< \fBKeyFrame\fP > & frames, float t)"
.PP
.SS "\fBAGVector3\fP Bone::interpolateRot (float t)"
.PP
.SS "\fBAGVector3\fP Bone::interpolateTrans (float t)"
.PP
.SH "Member Data Documentation"
.PP 
.SS "size_t \fBBone::id\fP"
.PP
.SS "\fBAGMatrix4\fP \fBBone::mAbsolute\fP"
.PP
.SS "\fBAGMatrix4\fP \fBBone::mFinal\fP"
.PP
.SS "\fBAGMatrix4\fP \fBBone::mRelative\fP"
.PP
.SS "\fBBone\fP* \fBBone::parent\fP"
.PP
.SS "\fBAGVector3\fP \fBBone::pos\fP"
.PP
.SS "std::vector<\fBKeyFrame\fP> \fBBone::rFrames\fP"
.PP
.SS "\fBAGVector3\fP \fBBone::rot\fP"
.PP
.SS "std::vector<\fBKeyFrame\fP> \fBBone::tFrames\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
