.TH "DecimatedGraph" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DecimatedGraph \- 
.SH SYNOPSIS
.br
.PP
\fC#include <path.h>\fP
.PP
Inherits \fBSimpleGraph\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecimatedGraph\fP ()"
.br
.ti -1c
.RI "\fBDecimatedGraph\fP (const \fBSimpleGraph\fP &g)"
.br
.ti -1c
.RI "void \fBdecimate\fP (float amount, \fBMapPathWeighter\fP *pWeighter)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DecimatedGraph::DecimatedGraph ()\fC [inline]\fP"
.PP
.SS "DecimatedGraph::DecimatedGraph (const \fBSimpleGraph\fP & g)\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void DecimatedGraph::decimate (float amount, \fBMapPathWeighter\fP * pWeighter)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
