.TH "Document" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Document \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_xml.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDocument\fP ()"
.br
.ti -1c
.RI "\fBDocument\fP (\fBAGFilename\fP pFile)"
.br
.ti -1c
.RI "\fB~Document\fP ()"
.br
.ti -1c
.RI "bool \fBparseFile\fP (\fBAGFilename\fP file)"
.br
.ti -1c
.RI "\fBNode\fP & \fBroot\fP ()"
.br
.ti -1c
.RI "std::string \fBtoString\fP (bool forceIndent=false) const "
.br
.ti -1c
.RI "void \fBparseMemory\fP (const \fBAGData\fP &s)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Document::Document ()"
.PP
.SS "Document::Document (\fBAGFilename\fP pFile)"
.PP
.SS "Document::~Document ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool Document::parseFile (\fBAGFilename\fP file)"
.PP
.SS "void Document::parseMemory (const \fBAGData\fP & s)"
.PP
.SS "\fBNode\fP & Document::root ()"
.PP
.SS "\fBAGData\fP Document::toString (bool forceIndent = \fCfalse\fP) const"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
