.TH "DomParser" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DomParser \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_xml.h>\fP
.PP
Inherits \fBParser\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsimpleTag\fP (const \fBAGString\fP &pName, const \fBNode::Attributes\fP &pAttributes)"
.br
.ti -1c
.RI "virtual void \fBstartTag\fP (const \fBAGString\fP &pName, const \fBNode::Attributes\fP &pAttributes)"
.br
.ti -1c
.RI "virtual void \fBendTag\fP (const \fBAGString\fP &pName)"
.br
.ti -1c
.RI "virtual void \fBtext\fP (const \fBAGString\fP &pText)"
.br
.ti -1c
.RI "virtual void \fBcomment\fP (const \fBAGString\fP &pText)"
.br
.ti -1c
.RI "virtual void \fBheader\fP (const \fBAGString\fP &pText)"
.br
.ti -1c
.RI "\fBDocument\fP * \fBparse\fP (const std::string &pData)"
.br
.ti -1c
.RI "\fBDocument\fP * \fBparse\fP (const std::string &pData, \fBDocument\fP *d)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void DomParser::comment (const \fBAGString\fP & pText)\fC [virtual]\fP"
.PP
Reimplemented from \fBParser\fP.
.SS "void DomParser::endTag (const \fBAGString\fP & pName)\fC [virtual]\fP"
.PP
Reimplemented from \fBParser\fP.
.SS "void DomParser::header (const \fBAGString\fP & pText)\fC [virtual]\fP"
.PP
Reimplemented from \fBParser\fP.
.SS "\fBDocument\fP * DomParser::parse (const std::string & pData, \fBDocument\fP * d)"
.PP
.SS "\fBDocument\fP * DomParser::parse (const std::string & pData)"
.PP
Reimplemented from \fBParser\fP.
.SS "void DomParser::simpleTag (const \fBAGString\fP & pName, const \fBNode::Attributes\fP & pAttributes)\fC [virtual]\fP"
.PP
Reimplemented from \fBParser\fP.
.SS "void DomParser::startTag (const \fBAGString\fP & pName, const \fBNode::Attributes\fP & pAttributes)\fC [virtual]\fP"
.PP
Reimplemented from \fBParser\fP.
.SS "void DomParser::text (const \fBAGString\fP & pText)\fC [virtual]\fP"
.PP
Reimplemented from \fBParser\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
