.TH "FontInfo" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FontInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBFontInfo\fP &i) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBpName\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool FontInfo::operator< (const \fBFontInfo\fP & i) const\fC [inline]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "std::string \fBFontInfo::pName\fP"
.PP
.SS "int \fBFontInfo::size\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
