.TH "src/height_map.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/height_map.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'height_map.h'\fP
.br
\fC#include 'terrain.h'\fP
.br
\fC#include <ag_serial.h>\fP
.br
\fC#include <ag_main.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< float > \fBgenSomeHeights\fP (int mW, int mH, float mMaxHeight)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBTerrainNames\fP [][20] = {'water','sand','earth','grass','grass2','forest','rock','rock2'}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::vector< float > genSomeHeights (int mW, int mH, float mMaxHeight)"
.PP
.SH "Variable Documentation"
.PP 
.SS "char \fBTerrainNames\fP[][20] = {'water','sand','earth','grass','grass2','forest','rock','rock2'}"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
