.TH "src/height_map.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/height_map.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'scene.h'\fP
.br
\fC#include <ag_geometry.h>\fP
.br
\fC#include <ag_xml.h>\fP
.br
\fC#include 'entptr.h'\fP
.br
\fC#include <ag_messageobject.h>\fP
.br
\fC#include <ag_serial.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHeightMap\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFIRSTTERRAIN\fP   WATER"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTerrainType\fP { \fBWATER\fP = 0, \fBSAND\fP, \fBEARTH\fP, \fBGRASS\fP, \fBGRASS2\fP, \fBFOREST\fP, \fBROCK\fP, \fBROCK2\fP, \fBLASTTERRAIN\fP }"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define FIRSTTERRAIN   WATER"
.PP
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTerrainType\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIWATER \fP\fP
.TP
\fB\fISAND \fP\fP
.TP
\fB\fIEARTH \fP\fP
.TP
\fB\fIGRASS \fP\fP
.TP
\fB\fIGRASS2 \fP\fP
.TP
\fB\fIFOREST \fP\fP
.TP
\fB\fIROCK \fP\fP
.TP
\fB\fIROCK2 \fP\fP
.TP
\fB\fILASTTERRAIN \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
