.TH "HeightMap" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeightMap \- 
.SH SYNOPSIS
.br
.PP
\fC#include <height_map.h>\fP
.PP
Inherits \fBAGMessageObject\fP.
.PP
Inherited by \fBAntMap\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHeightMap\fP (\fBScene\fP *pScene, int w, int h)"
.br
.ti -1c
.RI "virtual \fB~HeightMap\fP ()"
.br
.ti -1c
.RI "\fBAGVector2\fP \fBgetNextPlaceAbove\fP (const \fBAGVector2\fP &p, float height) const "
.br
.ti -1c
.RI "float \fBgetHeight\fP (float x, float y) const "
.br
.ti -1c
.RI "\fBAGVector3\fP \fBgetNormal\fP (int x, int y) const "
.br
.ti -1c
.RI "\fBAGVector3\fP \fBgetNormalF\fP (float x, float y) const "
.br
.ti -1c
.RI "\fBAGVector4\fP \fBgetVertex\fP (int x, int y)"
.br
.ti -1c
.RI "float \fBget\fP (size_t x, size_t y) const "
.br
.ti -1c
.RI "void \fBsetTerrain\fP (size_t x, size_t y, \fBTerrainType\fP t, float v)"
.br
.ti -1c
.RI "float \fBgetTerrain\fP (size_t x, size_t y, \fBTerrainType\fP t) const "
.br
.ti -1c
.RI "float \fBgetMean\fP (float x, float y)"
.br
.ti -1c
.RI "size_t \fBgetW\fP () const "
.br
.ti -1c
.RI "size_t \fBgetH\fP () const "
.br
.ti -1c
.RI "\fBAGVector2\fP \fBtruncPos\fP (const \fBAGVector2\fP &p) const "
.br
.ti -1c
.RI "\fBAGVector3\fP \fBtruncPos\fP (const \fBAGVector3\fP &p) const "
.br
.ti -1c
.RI "virtual void \fBsaveXML\fP (\fBNode\fP &node) const "
.br
.ti -1c
.RI "virtual void \fBloadXML\fP (const \fBNode\fP &node)"
.br
.ti -1c
.RI "void \fBsetHeight\fP (float height)"
.br
.ti -1c
.RI "void \fBset\fP (size_t x, size_t y, float height)"
.br
.ti -1c
.RI "virtual void \fBmapChanged\fP ()"
.br
.ti -1c
.RI "void \fBsetTerrainScale\fP (\fBTerrainType\fP t, float s)"
.br
.ti -1c
.RI "float \fBgetTerrainValue\fP (float x, float y, \fBTerrainType\fP t)"
.br
.ti -1c
.RI "\fBTerrainType\fP \fBgetTerrain\fP (float x, float y)"
.br
.ti -1c
.RI "float \fBgetTerrainWeight\fP (float x, float y)"
.br
.ti -1c
.RI "float \fBgetTerrainScale\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBaddChange\fP (const \fBAGVector2\fP &v)"
.br
.ti -1c
.RI "\fBAGRect2\fP \fBgetChangeRect\fP () const "
.br
.ti -1c
.RI "virtual void \fBnewMap\fP (int w, int h)"
.br
.ti -1c
.RI "\fBScene\fP * \fBgetScene\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGSignal\fP \fBsigMapChanged\fP"
.br
.ti -1c
.RI "\fBAGSignal\fP \fBsigMapChangedComplete\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTerrain\fP * \fBmTerrain\fP"
.br
.ti -1c
.RI "\fBAGString\fP \fBmName\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HeightMap::HeightMap (\fBScene\fP * pScene, int w, int h)"
.PP
.SS "HeightMap::~HeightMap ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void HeightMap::addChange (const \fBAGVector2\fP & v)"
.PP
.SS "float HeightMap::get (size_t x, size_t y) const"
.PP
.SS "\fBAGRect2\fP HeightMap::getChangeRect () const"
.PP
.SS "size_t HeightMap::getH () const\fC [inline]\fP"
.PP
.SS "float HeightMap::getHeight (float x, float y) const"
.PP
.SS "float HeightMap::getMean (float x, float y)"
.PP
.SS "\fBAGVector2\fP HeightMap::getNextPlaceAbove (const \fBAGVector2\fP & p, float height) const"
.PP
.SS "\fBAGVector3\fP HeightMap::getNormal (int x, int y) const"
.PP
.SS "\fBAGVector3\fP HeightMap::getNormalF (float x, float y) const"
.PP
.SS "\fBScene\fP * HeightMap::getScene ()"
.PP
.SS "\fBTerrainType\fP HeightMap::getTerrain (float x, float y)"
.PP
.SS "float HeightMap::getTerrain (size_t x, size_t y, \fBTerrainType\fP t) const"
.PP
.SS "float HeightMap::getTerrainScale (float x, float y)"
.PP
.SS "float HeightMap::getTerrainValue (float x, float y, \fBTerrainType\fP t)"
.PP
.SS "float HeightMap::getTerrainWeight (float x, float y)"
.PP
.SS "\fBAGVector4\fP HeightMap::getVertex (int x, int y)"
.PP
.SS "size_t HeightMap::getW () const\fC [inline]\fP"
.PP
.SS "void HeightMap::loadXML (const \fBNode\fP & node)\fC [virtual]\fP"
.PP
Reimplemented in \fBAntMap\fP.
.SS "void HeightMap::mapChanged ()\fC [virtual]\fP"
.PP
Reimplemented in \fBAntMap\fP.
.SS "void HeightMap::newMap (int w, int h)\fC [virtual]\fP"
.PP
Reimplemented in \fBAntMap\fP.
.SS "void HeightMap::saveXML (\fBNode\fP & node) const\fC [virtual]\fP"
.PP
Reimplemented in \fBAntMap\fP.
.SS "void HeightMap::set (size_t x, size_t y, float height)"
.PP
.SS "void HeightMap::setHeight (float height)"
.PP
.SS "void HeightMap::setTerrain (size_t x, size_t y, \fBTerrainType\fP t, float v)"
.PP
.SS "void HeightMap::setTerrainScale (\fBTerrainType\fP t, float s)"
.PP
.SS "\fBAGVector3\fP HeightMap::truncPos (const \fBAGVector3\fP & p) const"
.PP
.SS "\fBAGVector2\fP HeightMap::truncPos (const \fBAGVector2\fP & p) const"
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBAGString\fP \fBHeightMap::mName\fP\fC [protected]\fP"
.PP
.SS "\fBTerrain\fP* \fBHeightMap::mTerrain\fP\fC [protected]\fP"
.PP
.SS "\fBAGSignal\fP \fBHeightMap::sigMapChanged\fP"
.PP
.SS "\fBAGSignal\fP \fBHeightMap::sigMapChangedComplete\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
