.TH "HeuristicFunction" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeuristicFunction \- 
.SH SYNOPSIS
.br
.PP
\fC#include <heuristic.h>\fP
.PP
Inherited by \fBStoredHeuristicFunction\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::pair< \fBAGVector2\fP, \fBAGVector2\fP > \fBInput\fP"
.br
.ti -1c
.RI "typedef float \fBOutput\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~HeuristicFunction\fP ()"
.br
.ti -1c
.RI "virtual \fBOutput\fP \fBoperator()\fP (const \fBInput\fP &input)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::pair<\fBAGVector2\fP,\fBAGVector2\fP> \fBHeuristicFunction::Input\fP"
.PP
.SS "typedef float \fBHeuristicFunction::Output\fP"
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual HeuristicFunction::~HeuristicFunction ()\fC [inline, virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBHeuristicFunction::Output\fP HeuristicFunction::operator() (const \fBInput\fP & input)\fC [virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
