.TH "Job" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Job \- 
.SH SYNOPSIS
.br
.PP
\fC#include <jobs.h>\fP
.PP
Inherited by \fBFightJob\fP, \fBMoveJob\fP, and \fBRestJob\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJob\fP ()"
.br
.ti -1c
.RI "\fBJob\fP (int p)"
.br
.ti -1c
.RI "virtual \fB~Job\fP ()"
.br
.ti -1c
.RI "virtual void \fBmove\fP (\fBAntEntity\fP *, float ptime)"
.br
.ti -1c
.RI "virtual void \fBsaveXML\fP (\fBNode\fP &pNode) const "
.br
.ti -1c
.RI "virtual void \fBloadXML\fP (const \fBNode\fP &pNode)"
.br
.ti -1c
.RI "virtual \fBAGString\fP \fBxmlName\fP () const "
.br
.ti -1c
.RI "virtual void \fBjobFinished\fP (\fBAntEntity\fP *e)"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBJob\fP &j) const "
.br
.ti -1c
.RI "virtual bool \fBneedsMorale\fP () const "
.br
.ti -1c
.RI "bool \fBvalid\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBJob\fP class won't be exported to Ruby, because their constant creation and deletion fills up the GC otherwise. 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Job::Job ()"
.PP
.SS "Job::Job (int p)"
.PP
.SS "Job::~Job ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void Job::jobFinished (\fBAntEntity\fP * e)\fC [virtual]\fP"
.PP
Reimplemented in \fBFetchJob\fP.
.SS "void Job::loadXML (const \fBNode\fP & pNode)\fC [virtual]\fP"
.PP
Reimplemented in \fBRestJob\fP, \fBMoveJob\fP, \fBFightJob\fP, and \fBFetchJob\fP.
.SS "void Job::move (\fBAntEntity\fP *, float ptime)\fC [virtual]\fP"
.PP
Reimplemented in \fBRestJob\fP, \fBMoveJob\fP, \fBFightJob\fP, and \fBFetchJob\fP.
.SS "bool Job::needsMorale () const\fC [virtual]\fP"
.PP
Reimplemented in \fBFightJob\fP.
.SS "bool Job::operator<= (const \fBJob\fP & j) const"
.PP
.SS "void Job::saveXML (\fBNode\fP & pNode) const\fC [virtual]\fP"
.PP
Reimplemented in \fBRestJob\fP, \fBMoveJob\fP, \fBFightJob\fP, and \fBFetchJob\fP.
.SS "bool Job::valid () const"
.PP
.SS "\fBAGString\fP Job::xmlName () const\fC [virtual]\fP"
.PP
Reimplemented in \fBRestJob\fP, \fBMoveJob\fP, \fBFightJob\fP, and \fBFetchJob\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
