.TH "KeyFrame" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyFrame \- 
.SH SYNOPSIS
.br
.PP
\fC#include <anim_mesh_data.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBtime\fP"
.br
.ti -1c
.RI "\fBAGVector3\fP \fBv\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float \fBKeyFrame::time\fP"
.PP
.SS "\fBAGVector3\fP \fBKeyFrame::v\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
