.TH "src/map.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/map.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'scene.h'\fP
.br
\fC#include 'map.h'\fP
.br
\fC#include 'entity.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <ag_debug.h>\fP
.br
\fC#include 'mesh.h'\fP
.br
\fC#include 'terrain.h'\fP
.br
\fC#include 'quadtree.h'\fP
.br
\fC#include 'anim_mesh.h'\fP
.br
\fC#include 'ag_profiler.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAntMap\fP * \fBgetMap\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAntMap\fP * \fBmyAntargisMap\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAntMap\fP* getMap ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "\fBAntMap\fP* \fBmyAntargisMap\fP = 0"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
