.TH "MapPathWeighter" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapPathWeighter \- 
.SH SYNOPSIS
.br
.PP
\fC#include <path.h>\fP
.PP
Inherits \fBPathWeighter\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapPathWeighter\fP (\fBHeightMap\fP *pMap)"
.br
.ti -1c
.RI "virtual float \fBweight\fP (const \fBAGVector2\fP &a, const \fBAGVector2\fP &b)"
.br
.ti -1c
.RI "virtual bool \fBaccessible\fP (const \fBAGVector2\fP &a)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MapPathWeighter::MapPathWeighter (\fBHeightMap\fP * pMap)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool MapPathWeighter::accessible (const \fBAGVector2\fP & a)\fC [virtual]\fP"
.PP
.SS "float MapPathWeighter::weight (const \fBAGVector2\fP & a, const \fBAGVector2\fP & b)\fC [virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
