.TH "MeshTriangle" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeshTriangle \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeshTriangle\fP (size_t p0, size_t p1, size_t p2)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBMeshTriangle\fP &t) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBi0\fP"
.br
.ti -1c
.RI "size_t \fBi1\fP"
.br
.ti -1c
.RI "size_t \fBi2\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MeshTriangle::MeshTriangle (size_t p0, size_t p1, size_t p2)\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool MeshTriangle::operator< (const \fBMeshTriangle\fP & t) const"
.PP
.SH "Member Data Documentation"
.PP 
.SS "size_t \fBMeshTriangle::i0\fP"
.PP
.SS "size_t \fBMeshTriangle::i1\fP"
.PP
.SS "size_t \fBMeshTriangle::i2\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
