.TH "MeshData" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeshData \- 
.SH SYNOPSIS
.br
.PP
\fC#include <mesh_data.h>\fP
.PP
Inherits \fBAGRubyObject\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeshData\fP (const std::string &filename, float zoom, const std::string &pTexture='', bool pShadow=true)"
.br
.ti -1c
.RI "\fBMeshData\fP (const \fBVertexArray\fP &va, const std::string &pTexture, bool pShadow=true)"
.br
.ti -1c
.RI "\fB~MeshData\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (const \fBAGVector4\fP &pColor)"
.br
.ti -1c
.RI "void \fBdrawShadow\fP ()"
.br
.ti -1c
.RI "void \fBdrawDepth\fP ()"
.br
.ti -1c
.RI "void \fBdrawPick\fP ()"
.br
.ti -1c
.RI "void \fBmakeInstances\fP (const std::vector< \fBAGMatrix4\fP > &ts)"
.br
.RI "\fItest function 'instancing' \fP"
.ti -1c
.RI "\fBAGBox3\fP \fBbbox\fP () const "
.br
.ti -1c
.RI "void \fBsave\fP (const std::string &pFilename)"
.br
.ti -1c
.RI "virtual size_t \fBgetTriangles\fP () const "
.br
.ti -1c
.RI "virtual \fBAGVector4\fP \fBlineHit\fP (const \fBAGLine3\fP &pLine) const "
.br
.ti -1c
.RI "void \fBtexCoordFromPos\fP (float scale)"
.br
.ti -1c
.RI "void \fBsetPickable\fP (bool p)"
.br
.ti -1c
.RI "void \fBsetTransparent\fP (bool p)"
.br
.ti -1c
.RI "virtual bool \fBtransparent\fP ()"
.br
.ti -1c
.RI "void \fBsetLighting\fP (bool l)"
.br
.ti -1c
.RI "void \fBsetOverdraw\fP (bool o)"
.br
.ti -1c
.RI "void \fBsetCulling\fP (bool c)"
.br
.ti -1c
.RI "void \fBsetColors\fP (bool c)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MeshData::MeshData (const std::string & filename, float zoom, const std::string & pTexture = \fC''\fP, bool pShadow = \fCtrue\fP)"
.PP
.SS "MeshData::MeshData (const \fBVertexArray\fP & va, const std::string & pTexture, bool pShadow = \fCtrue\fP)"
.PP
.SS "MeshData::~MeshData ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "\fBAGBox3\fP MeshData::bbox () const"
.PP
.SS "void MeshData::draw (const \fBAGVector4\fP & pColor)"
.PP
.SS "void MeshData::drawDepth ()"
.PP
.SS "void MeshData::drawPick ()"
.PP
.SS "void MeshData::drawShadow ()"
.PP
.SS "size_t MeshData::getTriangles () const\fC [virtual]\fP"
.PP
.SS "virtual \fBAGVector4\fP MeshData::lineHit (const \fBAGLine3\fP & pLine) const\fC [inline, virtual]\fP"
.PP
.SS "void MeshData::makeInstances (const std::vector< \fBAGMatrix4\fP > & ts)"
.PP
test function 'instancing' 
.PP
.SS "void MeshData::save (const std::string & pFilename)"
.PP
.SS "void MeshData::setColors (bool c)"
.PP
.SS "void MeshData::setCulling (bool c)"
.PP
.SS "void MeshData::setLighting (bool l)"
.PP
.SS "void MeshData::setOverdraw (bool o)"
.PP
.SS "void MeshData::setPickable (bool p)"
.PP
.SS "void MeshData::setTransparent (bool p)"
.PP
.SS "void MeshData::texCoordFromPos (float scale)"
.PP
.SS "bool MeshData::transparent ()\fC [virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
