.TH "RegEx" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegEx \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ag_regex.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegEx\fP (const std::string &s, bool newline=false)"
.br
.ti -1c
.RI "\fB~RegEx\fP ()"
.br
.ti -1c
.RI "void \fBerr\fP (const std::string &s)"
.br
.ti -1c
.RI "bool \fBmatchFirst\fP (const std::string &s)"
.br
.ti -1c
.RI "int \fBfirst\fP (const std::string &s)"
.br
.ti -1c
.RI "std::pair< int, int > \fBfirstMatch\fP (const std::string &s)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RegEx::RegEx (const std::string & s, bool newline = \fCfalse\fP)\fC [inline]\fP"
.PP
.SS "RegEx::~RegEx ()\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void RegEx::err (const std::string & s)\fC [inline]\fP"
.PP
.SS "int RegEx::first (const std::string & s)\fC [inline]\fP"
.PP
.SS "std::pair<int,int> RegEx::firstMatch (const std::string & s)\fC [inline]\fP"
.PP
.SS "bool RegEx::matchFirst (const std::string & s)\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
