.TH "Renderer" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renderer \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ant_renderer.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Renderer\fP ()"
.br
.ti -1c
.RI "bool \fBcanMultitexture\fP ()"
.br
.ti -1c
.RI "bool \fBcanShadow\fP ()"
.br
.ti -1c
.RI "bool \fBcanGLSL\fP ()"
.br
.ti -1c
.RI "GLint \fBgetShadowUnit\fP ()"
.br
.ti -1c
.RI "GLint \fBgetNormalUnit\fP ()"
.br
.ti -1c
.RI "void \fBsetCurrentScene\fP (\fBScene\fP *scene)"
.br
.ti -1c
.RI "\fBScene\fP * \fBgetCurrentScene\fP ()"
.br
.ti -1c
.RI "void \fBinitShadowTexture\fP ()"
.br
.ti -1c
.RI "void \fBbeginShadowComputation\fP ()"
.br
.ti -1c
.RI "void \fBendShadowComputation\fP ()"
.br
.ti -1c
.RI "void \fBbeginShadowDrawing\fP ()"
.br
.ti -1c
.RI "void \fBendShadowDrawing\fP ()"
.br
.ti -1c
.RI "bool \fBbadShadowMap\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBRenderer\fP * \fBgetRenderer\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renderer::~Renderer ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool Renderer::badShadowMap ()"
.PP
.SS "void Renderer::beginShadowComputation ()"
.PP
.SS "void Renderer::beginShadowDrawing ()"
.PP
.SS "bool Renderer::canGLSL ()"
.PP
.SS "bool Renderer::canMultitexture ()"
.PP
.SS "bool Renderer::canShadow ()"
.PP
.SS "void Renderer::endShadowComputation ()"
.PP
\fBTodo\fP
.RS 4
switch to FBOs - this should bring an improvement of 17 to 19 fps 
.RE
.PP

.SS "void Renderer::endShadowDrawing ()"
.PP
.SS "\fBScene\fP * Renderer::getCurrentScene ()"
.PP
.SS "GLint Renderer::getNormalUnit ()"
.PP
.SS "GLint Renderer::getShadowUnit ()"
.PP
.SS "void Renderer::initShadowTexture ()"
.PP
.SS "void Renderer::setCurrentScene (\fBScene\fP * scene)"
.PP
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBRenderer\fP* getRenderer ()\fC [friend]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
