.TH "src/scene.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/scene.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ant_renderer.h'\fP
.br
\fC#include 'scene.h'\fP
.br
\fC#include <GL/gl.h>\fP
.br
\fC#include <GL/glu.h>\fP
.br
\fC#include <ag_debug.h>\fP
.br
\fC#include <ag_rendercontext.h>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include 'quadtree.h'\fP
.br
\fC#include 'ag_profiler.h'\fP
.br
\fC#include 'ag_main.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSortDistance\fP"
.br
.ti -1c
.RI "class \fBSortOrder\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
