.TH "src/scene.h" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/scene.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'GLee.h'\fP
.br
\fC#include 'ag_geometry.h'\fP
.br
\fC#include <SDL_opengl.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <set>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'scenenode.h'\fP
.br
\fC#include 'ant_camera.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPickNode\fP"
.br
.ti -1c
.RI "class \fBScene\fP"
.br
.RI "\fIquad-tree based scene-manager
.PP
\fBScene\fP is scene-manager. it holds all the 3d-objects (meshes and particles). These objects are stored in a \fBQuadTree\fP (could easily be exchanged for an octree, if needed). It takes further for drawing modes like picking, shadow-rendering and depth-drawing (for shadow-depth-computation). It contains a camera-object! So in the current state it's not possible to render the same scene from to places at the same time. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
