.TH "seg" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
seg \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sint16 \fBy\fP"
.br
.ti -1c
.RI "Sint16 \fBxl\fP"
.br
.ti -1c
.RI "Sint16 \fBxr\fP"
.br
.ti -1c
.RI "Sint16 \fBdy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Color filling functions 
.PP
.SH "Member Data Documentation"
.PP 
.SS "Sint16 \fBseg::dy\fP"
.PP
.SS "Sint16 \fBseg::xl\fP"
.PP
.SS "Sint16 \fBseg::xr\fP"
.PP
.SS "Sint16 \fBseg::y\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
