.TH "gui/src/sge_surface.cc" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui/src/sge_surface.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL.h'\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include 'sge_surface.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBseg\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX\fP   1000"
.br
.ti -1c
.RI "#define \fBPUSH\fP(Y, XL, XR, DY)"
.br
.ti -1c
.RI "#define \fBPOP\fP(Y, XL, XR, DY)"
.br
.ti -1c
.RI "#define \fBDO_FILL\fP(UintXX, label)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsge_Update_OFF\fP (void)"
.br
.ti -1c
.RI "void \fBsge_Update_ON\fP (void)"
.br
.ti -1c
.RI "void \fBsge_Lock_OFF\fP (void)"
.br
.ti -1c
.RI "void \fBsge_Lock_ON\fP (void)"
.br
.ti -1c
.RI "Uint8 \fBsge_getUpdate\fP (void)"
.br
.ti -1c
.RI "Uint8 \fBsge_getLock\fP (void)"
.br
.ti -1c
.RI "void \fBsge_UpdateRect\fP (SDL_Surface *screen, Sint16 x, Sint16 y, Uint16 w, Uint16 h)"
.br
.ti -1c
.RI "SDL_Surface * \fBsge_CreateAlphaSurface\fP (Uint32 flags, int width, int height)"
.br
.ti -1c
.RI "Uint32 \fBsge_MapAlpha\fP (Uint8 R, Uint8 G, Uint8 B, Uint8 A)"
.br
.ti -1c
.RI "void \fBsge_SetError\fP (const char *format,...)"
.br
.ti -1c
.RI "void \fB_PutPixel\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint32 color)"
.br
.ti -1c
.RI "void \fB_PutPixel\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B)"
.br
.ti -1c
.RI "void \fB_PutPixel8\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint32 color)"
.br
.ti -1c
.RI "void \fB_PutPixel16\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint32 color)"
.br
.ti -1c
.RI "void \fB_PutPixel24\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint32 color)"
.br
.ti -1c
.RI "void \fB_PutPixel32\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint32 color)"
.br
.ti -1c
.RI "void \fB_PutPixelX\fP (SDL_Surface *dest, Sint16 x, Sint16 y, Uint32 color)"
.br
.ti -1c
.RI "void \fBsge_PutPixel\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint32 color)"
.br
.ti -1c
.RI "void \fBsge_PutPixel\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B)"
.br
.ti -1c
.RI "Sint32 \fBsge_CalcYPitch\fP (SDL_Surface *dest, Sint16 y)"
.br
.ti -1c
.RI "void \fBsge_pPutPixel\fP (SDL_Surface *surface, Sint16 x, Sint32 ypitch, Uint32 color)"
.br
.ti -1c
.RI "Uint32 \fBsge_GetPixel\fP (SDL_Surface *surface, Sint16 x, Sint16 y)"
.br
.ti -1c
.RI "void \fB_PutPixelAlpha\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint32 color, Uint8 alpha)"
.br
.ti -1c
.RI "void \fBsge_PutPixelAlpha\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint32 color, Uint8 alpha)"
.br
.ti -1c
.RI "void \fB_PutPixelAlpha\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B, Uint8 alpha)"
.br
.ti -1c
.RI "void \fBsge_PutPixelAlpha\fP (SDL_Surface *surface, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B, Uint8 alpha)"
.br
.ti -1c
.RI "void \fBsge_write_block8\fP (SDL_Surface *Surface, Uint8 *block, Sint16 y)"
.br
.ti -1c
.RI "void \fBsge_write_block16\fP (SDL_Surface *Surface, Uint16 *block, Sint16 y)"
.br
.ti -1c
.RI "void \fBsge_write_block32\fP (SDL_Surface *Surface, Uint32 *block, Sint16 y)"
.br
.ti -1c
.RI "void \fBsge_read_block8\fP (SDL_Surface *Surface, Uint8 *block, Sint16 y)"
.br
.ti -1c
.RI "void \fBsge_read_block16\fP (SDL_Surface *Surface, Uint16 *block, Sint16 y)"
.br
.ti -1c
.RI "void \fBsge_read_block32\fP (SDL_Surface *Surface, Uint32 *block, Sint16 y)"
.br
.ti -1c
.RI "void \fBsge_ClearSurface\fP (SDL_Surface *Surface, Uint32 color)"
.br
.ti -1c
.RI "void \fBsge_ClearSurface\fP (SDL_Surface *Surface, Uint8 R, Uint8 G, Uint8 B)"
.br
.ti -1c
.RI "int \fBsge_BlitTransparent\fP (SDL_Surface *Src, SDL_Surface *Dest, Sint16 SrcX, Sint16 SrcY, Sint16 DestX, Sint16 DestY, Sint16 W, Sint16 H, Uint32 Clear, Uint8 Alpha)"
.br
.ti -1c
.RI "int \fBsge_Blit\fP (SDL_Surface *Src, SDL_Surface *Dest, Sint16 SrcX, Sint16 SrcY, Sint16 DestX, Sint16 DestY, Sint16 W, Sint16 H)"
.br
.ti -1c
.RI "SDL_Surface * \fBsge_copy_surface\fP (SDL_Surface *src)"
.br
.ti -1c
.RI "SDL_Color \fBsge_FillPaletteEntry\fP (Uint8 R, Uint8 G, Uint8 B)"
.br
.ti -1c
.RI "SDL_Color \fBsge_GetRGB\fP (SDL_Surface *Surface, Uint32 Color)"
.br
.ti -1c
.RI "void \fBsge_Fader\fP (SDL_Surface *Surface, Uint8 sR, Uint8 sG, Uint8 sB, Uint8 dR, Uint8 dG, Uint8 dB, Uint32 *ctab, int start, int stop)"
.br
.ti -1c
.RI "void \fBsge_AlphaFader\fP (Uint8 sR, Uint8 sG, Uint8 sB, Uint8 sA, Uint8 dR, Uint8 dG, Uint8 dB, Uint8 dA, Uint32 *ctab, int start, int stop)"
.br
.ti -1c
.RI "void \fBsge_SetupRainbowPalette\fP (SDL_Surface *Surface, Uint32 *ctab, int intensity, int start, int stop)"
.br
.ti -1c
.RI "void \fBsge_SetupBWPalette\fP (SDL_Surface *Surface, Uint32 *ctab, int start, int stop)"
.br
.ti -1c
.RI "void \fB_FloodFillX\fP (SDL_Surface *dst, Sint16 x, Sint16 y, Uint32 color)"
.br
.ti -1c
.RI "void \fBsge_FloodFill\fP (SDL_Surface *dst, Sint16 x, Sint16 y, Uint32 color)"
.br
.ti -1c
.RI "void \fBsge_FloodFill\fP (SDL_Surface *dst, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Uint8 \fB_sge_update\fP = 1"
.br
.ti -1c
.RI "Uint8 \fB_sge_lock\fP = 1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define DO_FILL(UintXX, label)"
.PP
.SS "#define MAX   1000"
.PP
.SS "#define POP(Y, XL, XR, DY)"
.PP
\fBValue:\fP
.PP
.nf
{\
        sp--;\
        DY = sp->dy;\
        Y = sp->y + sp->dy;\
        XL = sp->xl;\
        XR = sp->xr;\
}
.fi
.SS "#define PUSH(Y, XL, XR, DY)"
.PP
\fBValue:\fP
.PP
.nf
{\
        if (sp<stack+MAX && Y+(DY)>=sge_clip_ymin(dst) && Y+(DY)<=sge_clip_ymax(dst)){\
                sp->y = Y;\
                sp->xl = XL;\
                sp->xr = XR;\
                sp->dy = DY;\
                sp++;\
        }\
}
.fi
.SH "Function Documentation"
.PP 
.SS "void _FloodFillX (SDL_Surface * dst, Sint16 x, Sint16 y, Uint32 color)"
.PP
.SS "void _PutPixel (SDL_Surface * surface, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B)"
.PP
.SS "void _PutPixel (SDL_Surface * surface, Sint16 x, Sint16 y, Uint32 color)"
.PP
Pixel functions 
.SS "void _PutPixel16 (SDL_Surface * surface, Sint16 x, Sint16 y, Uint32 color)"
.PP
.SS "void _PutPixel24 (SDL_Surface * surface, Sint16 x, Sint16 y, Uint32 color)"
.PP
.SS "void _PutPixel32 (SDL_Surface * surface, Sint16 x, Sint16 y, Uint32 color)"
.PP
.SS "void _PutPixel8 (SDL_Surface * surface, Sint16 x, Sint16 y, Uint32 color)"
.PP
.SS "void _PutPixelAlpha (SDL_Surface * surface, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B, Uint8 alpha)"
.PP
.SS "void _PutPixelAlpha (SDL_Surface * surface, Sint16 x, Sint16 y, Uint32 color, Uint8 alpha)"
.PP
.SS "void _PutPixelX (SDL_Surface * dest, Sint16 x, Sint16 y, Uint32 color)"
.PP
.SS "void sge_AlphaFader (Uint8 sR, Uint8 sG, Uint8 sB, Uint8 sA, Uint8 dR, Uint8 dG, Uint8 dB, Uint8 dA, Uint32 * ctab, int start, int stop)"
.PP
.SS "int sge_Blit (SDL_Surface * Src, SDL_Surface * Dest, Sint16 SrcX, Sint16 SrcY, Sint16 DestX, Sint16 DestY, Sint16 W, Sint16 H)"
.PP
.SS "int sge_BlitTransparent (SDL_Surface * Src, SDL_Surface * Dest, Sint16 SrcX, Sint16 SrcY, Sint16 DestX, Sint16 DestY, Sint16 W, Sint16 H, Uint32 Clear, Uint8 Alpha)"
.PP
.SS "Sint32 sge_CalcYPitch (SDL_Surface * dest, Sint16 y)"
.PP
.SS "void sge_ClearSurface (SDL_Surface * Surface, Uint8 R, Uint8 G, Uint8 B)"
.PP
.SS "void sge_ClearSurface (SDL_Surface * Surface, Uint32 color)"
.PP
Blitting/surface functions 
.SS "SDL_Surface* sge_copy_surface (SDL_Surface * src)"
.PP
.SS "SDL_Surface* sge_CreateAlphaSurface (Uint32 flags, int width, int height)"
.PP
.SS "void sge_Fader (SDL_Surface * Surface, Uint8 sR, Uint8 sG, Uint8 sB, Uint8 dR, Uint8 dG, Uint8 dB, Uint32 * ctab, int start, int stop)"
.PP
.SS "SDL_Color sge_FillPaletteEntry (Uint8 R, Uint8 G, Uint8 B)"
.PP
Palette functions 
.SS "void sge_FloodFill (SDL_Surface * dst, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B)"
.PP
.SS "void sge_FloodFill (SDL_Surface * dst, Sint16 x, Sint16 y, Uint32 color)"
.PP
.SS "Uint8 sge_getLock (void)"
.PP
.SS "Uint32 sge_GetPixel (SDL_Surface * surface, Sint16 x, Sint16 y)"
.PP
.SS "SDL_Color sge_GetRGB (SDL_Surface * Surface, Uint32 Color)"
.PP
.SS "Uint8 sge_getUpdate (void)"
.PP
.SS "void sge_Lock_OFF (void)"
.PP
.SS "void sge_Lock_ON (void)"
.PP
.SS "Uint32 sge_MapAlpha (Uint8 R, Uint8 G, Uint8 B, Uint8 A)"
.PP
.SS "void sge_pPutPixel (SDL_Surface * surface, Sint16 x, Sint32 ypitch, Uint32 color)"
.PP
.SS "void sge_PutPixel (SDL_Surface * surface, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B)"
.PP
.SS "void sge_PutPixel (SDL_Surface * surface, Sint16 x, Sint16 y, Uint32 color)"
.PP
.SS "void sge_PutPixelAlpha (SDL_Surface * surface, Sint16 x, Sint16 y, Uint8 R, Uint8 G, Uint8 B, Uint8 alpha)"
.PP
.SS "void sge_PutPixelAlpha (SDL_Surface * surface, Sint16 x, Sint16 y, Uint32 color, Uint8 alpha)"
.PP
.SS "void sge_read_block16 (SDL_Surface * Surface, Uint16 * block, Sint16 y)"
.PP
.SS "void sge_read_block32 (SDL_Surface * Surface, Uint32 * block, Sint16 y)"
.PP
.SS "void sge_read_block8 (SDL_Surface * Surface, Uint8 * block, Sint16 y)"
.PP
.SS "void sge_SetError (const char * format,  ...)"
.PP
.SS "void sge_SetupBWPalette (SDL_Surface * Surface, Uint32 * ctab, int start, int stop)"
.PP
.SS "void sge_SetupRainbowPalette (SDL_Surface * Surface, Uint32 * ctab, int intensity, int start, int stop)"
.PP
.SS "void sge_Update_OFF (void)"
.PP
Misc. functions 
.SS "void sge_Update_ON (void)"
.PP
.SS "void sge_UpdateRect (SDL_Surface * screen, Sint16 x, Sint16 y, Uint16 w, Uint16 h)"
.PP
.SS "void sge_write_block16 (SDL_Surface * Surface, Uint16 * block, Sint16 y)"
.PP
.SS "void sge_write_block32 (SDL_Surface * Surface, Uint32 * block, Sint16 y)"
.PP
.SS "void sge_write_block8 (SDL_Surface * Surface, Uint8 * block, Sint16 y)"
.PP
Block functions 
.SH "Variable Documentation"
.PP 
.SS "Uint8 \fB_sge_lock\fP = 1"
.PP
.SS "Uint8 \fB_sge_update\fP = 1"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
