.TH "SortEdges" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SortEdges \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBSimpleGraph::Edge\fP *e1, const \fBSimpleGraph::Edge\fP *e2)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool SortEdges::operator() (const \fBSimpleGraph::Edge\fP * e1, const \fBSimpleGraph::Edge\fP * e2)\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
