.TH "StoredHeuristicFunction" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StoredHeuristicFunction \- 
.SH SYNOPSIS
.br
.PP
\fC#include <heuristic.h>\fP
.PP
Inherits \fBHeuristicFunction\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStoredHeuristicFunction\fP (size_t res, float width)"
.br
.ti -1c
.RI "void \fBstore\fP (\fBInput\fP in, \fBOutput\fP \fBout\fP)"
.br
.ti -1c
.RI "void \fBdisplay\fP ()"
.br
.ti -1c
.RI "virtual \fBOutput\fP \fBoperator()\fP (const \fBInput\fP &input)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StoredHeuristicFunction::StoredHeuristicFunction (size_t res, float width)"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void StoredHeuristicFunction::display ()"
.PP
.SS "\fBStoredHeuristicFunction::Output\fP StoredHeuristicFunction::operator() (const \fBInput\fP & input)\fC [virtual]\fP"
.PP
.SS "void StoredHeuristicFunction::store (\fBInput\fP in, \fBOutput\fP out)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
