.TH "TerrainPiece" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TerrainPiece \- 
.SH SYNOPSIS
.br
.PP
\fC#include <terrain.h>\fP
.PP
Inherits \fBSceneNode\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerrainPiece\fP (\fBScene\fP *pScene, \fBTerrain\fP *t, \fBHeightMap\fP &map, int x, int y, int w, int h, const \fBAGVector4\fP &pPos, int scale)"
.br
.ti -1c
.RI "virtual \fB~TerrainPiece\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBdrawShadow\fP ()"
.br
.ti -1c
.RI "void \fBdrawDepth\fP ()"
.br
.ti -1c
.RI "void \fBdrawPick\fP ()"
.br
.ti -1c
.RI "\fBAGVector4\fP \fBlineHit\fP (const \fBAGLine3\fP &pLine) const "
.br
.ti -1c
.RI "size_t \fBgetTriangles\fP () const "
.br
.ti -1c
.RI "virtual void \fBmapChanged\fP ()"
.br
.RI "\fIrebuilds the mesh \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBTerrainPiece\fP displays (like \fBWaterPiece\fP) some small patch of terrain. (\fBTerrain\fP and water is tiled for the ease of culling) for more information on drawing-modes and such go to \fBSceneNode\fP. 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TerrainPiece::TerrainPiece (\fBScene\fP * pScene, \fBTerrain\fP * t, \fBHeightMap\fP & map, int x, int y, int w, int h, const \fBAGVector4\fP & pPos, int scale)"
.PP
.SS "TerrainPiece::~TerrainPiece ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void TerrainPiece::draw ()\fC [virtual]\fP"
.PP
Reimplemented from \fBSceneNode\fP.
.SS "void TerrainPiece::drawDepth ()\fC [virtual]\fP"
.PP
This functions is used in the 1st depth-drawing render-pass, so you should not use colors or textures, when not needed 
.PP
Reimplemented from \fBSceneNode\fP.
.SS "void TerrainPiece::drawPick ()\fC [virtual]\fP"
.PP
this function is used for picking objects. Picking is done one CPU, so shader-animated models are out of place here. 
.PP
Reimplemented from \fBSceneNode\fP.
.SS "void TerrainPiece::drawShadow ()\fC [virtual]\fP"
.PP
this function is deprecated. It was once used for drawing shadow in a 3rd render-pass. 
.PP
Reimplemented from \fBSceneNode\fP.
.SS "size_t TerrainPiece::getTriangles () const\fC [virtual]\fP"
.PP
Reimplemented from \fBSceneNode\fP.
.SS "\fBAGVector4\fP TerrainPiece::lineHit (const \fBAGLine3\fP & pLine) const\fC [virtual]\fP"
.PP
Reimplemented from \fBSceneNode\fP.
.SS "void TerrainPiece::mapChanged ()\fC [virtual]\fP"
.PP
rebuilds the mesh 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Antargis from the source code.
