.TH "todo" 3 "27 Oct 2006" "Version 0.1.9" "Antargis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBClass \fBAGTable\fP \fP" 1c
children should be re-arranged whenever \fBAGTable::arrange()\fP is called! 
.PP
.PP
 
.IP "\fBMember \fBNode::Node\fP() \fP" 1c
finish documentation 
.PP
.PP
 
.IP "\fBMember \fBRenderer::endShadowComputation\fP() \fP" 1c
switch to FBOs - this should bring an improvement of 17 to 19 fps 
.PP

