/* config.h. Generated by SConstruct */


#define PACKAGE_BUGREPORT "none"
#define HAVE_STRING_H ""
#define PACKAGE_NAME "LincityNG"
#define PACKAGE "lincityng"
#define HAVE_UNISTD_H ""
#define PACKAGE_VERSION "0.1-svn"
#define SIZEOF_LONG 4
#define HAVE_GZIP ""
#define HAVE_SYS_TIME_H ""
#define SIZEOF_CHAR 1
#define HAVE_POPEN ""
#define SIZEOF_INT 4
#define HAVE_DIRENT_H ""
#define PACKAGE_STRING "LincityNG 0.1-svn"
#define SIZEOF_SHORT 2

